from generatorLib import StickDiagram
from generatorLib import DesignParameters
import copy
import math
from generatorLib import DRC
from generatorLib.generator_models import Inverter_iksu2
from generatorLib.generator_models import NAND3_ver2
from generatorLib.generator_models import ViaMet12Met2
from generatorLib.generator_models import ViaMet22Met3
from generatorLib.generator_models import ViaMet32Met4
from generatorLib.generator_models import Transmission_gate

class EasyDebugModule(StickDiagram._StickDiagram):
	def __init__(self, _DesignParameter=None, _Name='MuxModuleVer2'):
		if _DesignParameter != None:
			self._DesignParameter = _DesignParameter
		else:
			self._DesignParameter = dict(_Name=self._NameDeclaration(_Name=_Name), _GDSFile=self._GDSObjDeclaration(_GDSFile=None))
		self._DesignParameter['_Name']['Name'] = _Name

	def _CalculateDesignParameter(self,INV_nmos_width=200,INV_finger=1,VDD2PMOS=380,gate_length=30,gate_spacing=100,XVT='RVT',NMOS_y=420,Cell_height=1800,TG_pmos_width=600,TG_nmos_width=300,TG_poly_y=800,NANDIN_y=900,TG_finger=3,MUX_module_num=1,Input_offset=0):
	
		drc = DRC.DRC()
		_Name = self._DesignParameter['_Name']['_Name']
		
		self._DesignParameter['INV'] = self._SrefElementDeclaration(_DesignObj=Inverter_iksu2._Inverter(_Name='INVIn{}'.format(_Name)))[0]
		self._DesignParameter['INV']['_DesignObj']._CalculateDesignParameter_v3(**dict(_Finger=INV_finger, _ChannelWidth=INV_nmos_width, _ChannelLength=gate_length, _NPRatio=2, _VDD2VSSHeight=Cell_height, _VDD2PMOSHeight=VDD2PMOS, _VSS2NMOSHeight=NMOS_y, _YCoordOfInput=None, _Dummy=True, _XVT=XVT, _GateSpacing=gate_spacing, _SDWidth=66, _NumViaPMOSMet12Met2CoY=None, _NumViaNMOSMet12Met2CoY=None, _SupplyRailType=2))
		self._DesignParameter['INV']['_XYCoordinates'] = [[0.0, 0.0]]

		##dummy for INV
		self._DesignParameter['POLY_dummy_inv_pmos'] = self._BoundaryElementDeclaration(_Layer=DesignParameters._LayerMapping['POLY'][0], _Datatype=DesignParameters._LayerMapping['POLY'][1], _XWidth=gate_length)
		self._DesignParameter['POLY_dummy_inv_pmos']['_YWidth'] = self._DesignParameter['INV']['_DesignObj']._DesignParameter['_PMOS']['_DesignObj']._DesignParameter['_PODummyLayer']['_YWidth']
		self._DesignParameter['POLY_dummy_inv_nmos'] = self._BoundaryElementDeclaration(_Layer=DesignParameters._LayerMapping['POLY'][0], _Datatype=DesignParameters._LayerMapping['POLY'][1], _XWidth=gate_length)
		self._DesignParameter['POLY_dummy_inv_nmos']['_YWidth'] = self._DesignParameter['INV']['_DesignObj']._DesignParameter['_NMOS']['_DesignObj']._DesignParameter['_PODummyLayer']['_YWidth']

		if float(self._DesignParameter['POLY_dummy_inv_pmos']['_XWidth']) * float(self._DesignParameter['POLY_dummy_inv_pmos']['_YWidth']) < drc._PODummyMinArea:
			self._DesignParameter['POLY_dummy_inv_pmos']['_YWidth'] = self.CeilMinSnapSpacing(float(drc._PODummyMinArea) / float(self._DesignParameter['POLY_dummy_inv_pmos']['_XWidth']), drc._MinSnapSpacing * 2)
		else:
			pass

		if float(self._DesignParameter['POLY_dummy_inv_nmos']['_XWidth']) * float(self._DesignParameter['POLY_dummy_inv_nmos']['_YWidth']) < drc._PODummyMinArea:
			self._DesignParameter['POLY_dummy_inv_nmos']['_YWidth'] = self.CeilMinSnapSpacing(float(drc._PODummyMinArea) / float(self._DesignParameter['POLY_dummy_inv_nmos']['_XWidth']), drc._MinSnapSpacing * 2)
		else:
			pass

		Dummy_inv_pmos_height = self._DesignParameter['POLY_dummy_inv_pmos']['_YWidth']
		Dummy_inv_nmos_height = self._DesignParameter['POLY_dummy_inv_nmos']['_YWidth']

		self._DesignParameter['POLY_dummy_inv_pmos']['_XYCoordinates'] = [[(((self._DesignParameter['INV']['_XYCoordinates'][0][0]) + self._DesignParameter['INV']['_DesignObj']._DesignParameter['_PMOS']['_XYCoordinates'][0][0]) + self._DesignParameter['INV']['_DesignObj']._DesignParameter['_PMOS']['_DesignObj']._DesignParameter['_PODummyLayer']['_XYCoordinates'][0][0]),
																		(((self._DesignParameter['INV']['_XYCoordinates'][0][1]) + self._DesignParameter['INV']['_DesignObj']._DesignParameter['_PMOS']['_XYCoordinates'][0][1]) + self._DesignParameter['INV']['_DesignObj']._DesignParameter['_PMOS']['_DesignObj']._DesignParameter['_PODummyLayer']['_XYCoordinates'][0][1] - (self._DesignParameter['INV']['_DesignObj']._DesignParameter['_PMOS']['_DesignObj']._DesignParameter['_PODummyLayer']['_YWidth'] / 2) + (Dummy_inv_pmos_height / 2))],
																		  [(((self._DesignParameter['INV']['_XYCoordinates'][0][0]) + self._DesignParameter['INV']['_DesignObj']._DesignParameter['_PMOS']['_XYCoordinates'][0][0]) + self._DesignParameter['INV']['_DesignObj']._DesignParameter['_PMOS']['_DesignObj']._DesignParameter['_PODummyLayer']['_XYCoordinates'][1][0]),
																		(((self._DesignParameter['INV']['_XYCoordinates'][0][1]) + self._DesignParameter['INV']['_DesignObj']._DesignParameter['_PMOS']['_XYCoordinates'][0][1]) + self._DesignParameter['INV']['_DesignObj']._DesignParameter['_PMOS']['_DesignObj']._DesignParameter['_PODummyLayer']['_XYCoordinates'][1][1] - (self._DesignParameter['INV']['_DesignObj']._DesignParameter['_PMOS']['_DesignObj']._DesignParameter['_PODummyLayer']['_YWidth'] / 2) + (Dummy_inv_pmos_height / 2))]
																		  ]
		self._DesignParameter['POLY_dummy_inv_nmos']['_XYCoordinates'] = [[(((self._DesignParameter['INV']['_XYCoordinates'][0][0]) + self._DesignParameter['INV']['_DesignObj']._DesignParameter['_NMOS']['_XYCoordinates'][0][0]) + self._DesignParameter['INV']['_DesignObj']._DesignParameter['_NMOS']['_DesignObj']._DesignParameter['_PODummyLayer']['_XYCoordinates'][0][0]),
																		(((self._DesignParameter['INV']['_XYCoordinates'][0][1]) + self._DesignParameter['INV']['_DesignObj']._DesignParameter['_NMOS']['_XYCoordinates'][0][1]) + self._DesignParameter['INV']['_DesignObj']._DesignParameter['_NMOS']['_DesignObj']._DesignParameter['_PODummyLayer']['_XYCoordinates'][0][1] + (self._DesignParameter['INV']['_DesignObj']._DesignParameter['_NMOS']['_DesignObj']._DesignParameter['_PODummyLayer']['_YWidth'] / 2) - (Dummy_inv_nmos_height / 2))],
																		  [(((self._DesignParameter['INV']['_XYCoordinates'][0][0]) + self._DesignParameter['INV']['_DesignObj']._DesignParameter['_NMOS']['_XYCoordinates'][0][0]) + self._DesignParameter['INV']['_DesignObj']._DesignParameter['_NMOS']['_DesignObj']._DesignParameter['_PODummyLayer']['_XYCoordinates'][1][0]),
																		(((self._DesignParameter['INV']['_XYCoordinates'][0][1]) + self._DesignParameter['INV']['_DesignObj']._DesignParameter['_NMOS']['_XYCoordinates'][0][1]) + self._DesignParameter['INV']['_DesignObj']._DesignParameter['_NMOS']['_DesignObj']._DesignParameter['_PODummyLayer']['_XYCoordinates'][1][1] + (self._DesignParameter['INV']['_DesignObj']._DesignParameter['_NMOS']['_DesignObj']._DesignParameter['_PODummyLayer']['_YWidth'] / 2) - (Dummy_inv_nmos_height / 2))]
																		  ]

		nand_mos_finger = (INV_finger * 2)
		self._DesignParameter['NAND'] = self._SrefElementDeclaration(_DesignObj=NAND3_ver2.NAND3(_Name='NANDIn{}'.format(_Name)))[0]
		self._DesignParameter['NAND']['_DesignObj']._CalculateDesignParameter(**dict(gate_spacing=gate_spacing, nmos_width1=((3 * INV_nmos_width) / 2), nmos_width2=((3 * INV_nmos_width) / 2), pmos_width1=(2 * INV_nmos_width), pmos_width2=INV_nmos_width, nmos1_y=NMOS_y, nmos2_y=NMOS_y, pmos1_y=VDD2PMOS, pmos2_y=(VDD2PMOS + (INV_nmos_width / 2)), nmos_gate_a=nand_mos_finger, pmos_gate_a=nand_mos_finger, nmos_gate_b=nand_mos_finger, pmos_gate_b=INV_finger, nmos_gate_c=nand_mos_finger, pmos_gate_c=INV_finger, vss2vdd_height=Cell_height, sdwidth=66, supply_xdistance=300, length=gate_length, XVT=XVT, gate_y=NANDIN_y, _PCCrit=False))
		self._DesignParameter['NAND']['_XYCoordinates'] = [[(((((- self._DesignParameter['INV']['_DesignObj']._DesignParameter['XVTLayer']['_XWidth']) / 2) - (self._DesignParameter['NAND']['_DesignObj']._DesignParameter['xvtlayer']['_XWidth'] / 2)) - gate_spacing) - gate_length), self._DesignParameter['INV']['_XYCoordinates'][0][1]]]

		##dummy for NAND
		self._DesignParameter['POLY_dummy_nand_pmos_1'] = self._BoundaryElementDeclaration(_Layer=DesignParameters._LayerMapping['POLY'][0], _Datatype=DesignParameters._LayerMapping['POLY'][1], _XWidth=gate_length)
		self._DesignParameter['POLY_dummy_nand_pmos_1']['_YWidth'] = self._DesignParameter['NAND']['_DesignObj']._DesignParameter['pmos1']['_DesignObj']._DesignParameter['_PODummyLayer']['_YWidth']
		self._DesignParameter['POLY_dummy_nand_pmos_2'] = self._BoundaryElementDeclaration(_Layer=DesignParameters._LayerMapping['POLY'][0], _Datatype=DesignParameters._LayerMapping['POLY'][1], _XWidth=gate_length)
		self._DesignParameter['POLY_dummy_nand_pmos_2']['_YWidth'] = self._DesignParameter['NAND']['_DesignObj']._DesignParameter['pmos2']['_DesignObj']._DesignParameter['_PODummyLayer']['_YWidth']
		self._DesignParameter['POLY_dummy_nand_nmos_1'] = self._BoundaryElementDeclaration(_Layer=DesignParameters._LayerMapping['POLY'][0], _Datatype=DesignParameters._LayerMapping['POLY'][1], _XWidth=gate_length)
		self._DesignParameter['POLY_dummy_nand_nmos_1']['_YWidth'] = self._DesignParameter['NAND']['_DesignObj']._DesignParameter['nmos1']['_DesignObj']._DesignParameter['_PODummyLayer']['_YWidth']
		self._DesignParameter['POLY_dummy_nand_nmos_2'] = self._BoundaryElementDeclaration(_Layer=DesignParameters._LayerMapping['POLY'][0], _Datatype=DesignParameters._LayerMapping['POLY'][1], _XWidth=gate_length)
		self._DesignParameter['POLY_dummy_nand_nmos_2']['_YWidth'] = self._DesignParameter['NAND']['_DesignObj']._DesignParameter['nmos2']['_DesignObj']._DesignParameter['_PODummyLayer']['_YWidth']

		if float(self._DesignParameter['POLY_dummy_nand_pmos_1']['_XWidth']) * float(self._DesignParameter['POLY_dummy_nand_pmos_1']['_YWidth']) < drc._PODummyMinArea:
			self._DesignParameter['POLY_dummy_nand_pmos_1']['_YWidth'] = self.CeilMinSnapSpacing(float(drc._PODummyMinArea) / float(self._DesignParameter['POLY_dummy_nand_pmos_1']['_XWidth']), drc._MinSnapSpacing * 2)
		else:
			pass

		if float(self._DesignParameter['POLY_dummy_nand_pmos_2']['_XWidth']) * float(self._DesignParameter['POLY_dummy_nand_pmos_2']['_YWidth']) < drc._PODummyMinArea:
			self._DesignParameter['POLY_dummy_nand_pmos_2']['_YWidth'] = self.CeilMinSnapSpacing(float(drc._PODummyMinArea) / float(self._DesignParameter['POLY_dummy_nand_pmos_2']['_XWidth']), drc._MinSnapSpacing * 2)
		else:
			pass

		if float(self._DesignParameter['POLY_dummy_nand_nmos_1']['_XWidth']) * float(self._DesignParameter['POLY_dummy_nand_nmos_1']['_YWidth']) < drc._PODummyMinArea:
			self._DesignParameter['POLY_dummy_nand_nmos_1']['_YWidth'] = self.CeilMinSnapSpacing(float(drc._PODummyMinArea) / float(self._DesignParameter['POLY_dummy_nand_nmos_1']['_XWidth']), drc._MinSnapSpacing * 2)
		else:
			pass

		if float(self._DesignParameter['POLY_dummy_nand_nmos_2']['_XWidth']) * float(self._DesignParameter['POLY_dummy_nand_nmos_2']['_YWidth']) < drc._PODummyMinArea:
			self._DesignParameter['POLY_dummy_nand_nmos_2']['_YWidth'] = self.CeilMinSnapSpacing(float(drc._PODummyMinArea) / float(self._DesignParameter['POLY_dummy_nand_nmos_2']['_XWidth']), drc._MinSnapSpacing * 2)
		else:
			pass

		Dummy_nand_pmos1_height = self._DesignParameter['POLY_dummy_nand_pmos_1']['_YWidth']
		Dummy_nand_pmos2_height = self._DesignParameter['POLY_dummy_nand_pmos_2']['_YWidth']
		Dummy_nand_nmos1_height = self._DesignParameter['POLY_dummy_nand_nmos_1']['_YWidth']
		Dummy_nand_nmos2_height = self._DesignParameter['POLY_dummy_nand_nmos_2']['_YWidth']

		self._DesignParameter['POLY_dummy_nand_pmos_1']['_XYCoordinates'] = [[(((self._DesignParameter['NAND']['_XYCoordinates'][0][0]) + self._DesignParameter['NAND']['_DesignObj']._DesignParameter['pmos1']['_XYCoordinates'][0][0]) + self._DesignParameter['NAND']['_DesignObj']._DesignParameter['pmos1']['_DesignObj']._DesignParameter['_PODummyLayer']['_XYCoordinates'][0][0]),
																		(((self._DesignParameter['NAND']['_XYCoordinates'][0][1]) + self._DesignParameter['NAND']['_DesignObj']._DesignParameter['pmos1']['_XYCoordinates'][0][1]) + self._DesignParameter['NAND']['_DesignObj']._DesignParameter['pmos1']['_DesignObj']._DesignParameter['_PODummyLayer']['_XYCoordinates'][0][1] - (self._DesignParameter['NAND']['_DesignObj']._DesignParameter['pmos1']['_DesignObj']._DesignParameter['_PODummyLayer']['_YWidth'] / 2) + (Dummy_nand_pmos1_height / 2))],
																		  [(((self._DesignParameter['NAND']['_XYCoordinates'][0][0]) + self._DesignParameter['NAND']['_DesignObj']._DesignParameter['pmos1']['_XYCoordinates'][0][0]) + self._DesignParameter['NAND']['_DesignObj']._DesignParameter['pmos1']['_DesignObj']._DesignParameter['_PODummyLayer']['_XYCoordinates'][1][0]),
																		(((self._DesignParameter['NAND']['_XYCoordinates'][0][1]) + self._DesignParameter['NAND']['_DesignObj']._DesignParameter['pmos1']['_XYCoordinates'][0][1]) + self._DesignParameter['NAND']['_DesignObj']._DesignParameter['pmos1']['_DesignObj']._DesignParameter['_PODummyLayer']['_XYCoordinates'][1][1] - (self._DesignParameter['NAND']['_DesignObj']._DesignParameter['pmos1']['_DesignObj']._DesignParameter['_PODummyLayer']['_YWidth'] / 2) + (Dummy_nand_pmos1_height / 2))]
																		  ]
		self._DesignParameter['POLY_dummy_nand_pmos_2']['_XYCoordinates'] = [[(((self._DesignParameter['NAND']['_XYCoordinates'][0][0]) + self._DesignParameter['NAND']['_DesignObj']._DesignParameter['pmos2']['_XYCoordinates'][0][0]) + self._DesignParameter['NAND']['_DesignObj']._DesignParameter['pmos2']['_DesignObj']._DesignParameter['_PODummyLayer']['_XYCoordinates'][0][0]),
																		(((self._DesignParameter['NAND']['_XYCoordinates'][0][1]) + self._DesignParameter['NAND']['_DesignObj']._DesignParameter['pmos2']['_XYCoordinates'][0][1]) + self._DesignParameter['NAND']['_DesignObj']._DesignParameter['pmos2']['_DesignObj']._DesignParameter['_PODummyLayer']['_XYCoordinates'][0][1] - (self._DesignParameter['NAND']['_DesignObj']._DesignParameter['pmos2']['_DesignObj']._DesignParameter['_PODummyLayer']['_YWidth'] / 2) + (Dummy_nand_pmos2_height / 2))],
																		  [(((self._DesignParameter['NAND']['_XYCoordinates'][0][0]) + self._DesignParameter['NAND']['_DesignObj']._DesignParameter['pmos2']['_XYCoordinates'][0][0]) + self._DesignParameter['NAND']['_DesignObj']._DesignParameter['pmos2']['_DesignObj']._DesignParameter['_PODummyLayer']['_XYCoordinates'][1][0]),
																		(((self._DesignParameter['NAND']['_XYCoordinates'][0][1]) + self._DesignParameter['NAND']['_DesignObj']._DesignParameter['pmos2']['_XYCoordinates'][0][1]) + self._DesignParameter['NAND']['_DesignObj']._DesignParameter['pmos2']['_DesignObj']._DesignParameter['_PODummyLayer']['_XYCoordinates'][1][1] - (self._DesignParameter['NAND']['_DesignObj']._DesignParameter['pmos2']['_DesignObj']._DesignParameter['_PODummyLayer']['_YWidth'] / 2) + (Dummy_nand_pmos2_height / 2))]
																		  ]
		self._DesignParameter['POLY_dummy_nand_nmos_1']['_XYCoordinates'] = [[(((self._DesignParameter['NAND']['_XYCoordinates'][0][0]) + self._DesignParameter['NAND']['_DesignObj']._DesignParameter['nmos1']['_XYCoordinates'][0][0]) + self._DesignParameter['NAND']['_DesignObj']._DesignParameter['nmos1']['_DesignObj']._DesignParameter['_PODummyLayer']['_XYCoordinates'][0][0]),
																		(((self._DesignParameter['NAND']['_XYCoordinates'][0][1]) + self._DesignParameter['NAND']['_DesignObj']._DesignParameter['nmos1']['_XYCoordinates'][0][1]) + self._DesignParameter['NAND']['_DesignObj']._DesignParameter['nmos1']['_DesignObj']._DesignParameter['_PODummyLayer']['_XYCoordinates'][0][1] + (self._DesignParameter['NAND']['_DesignObj']._DesignParameter['nmos1']['_DesignObj']._DesignParameter['_PODummyLayer']['_YWidth'] / 2) - (Dummy_nand_nmos1_height / 2))],
																		  [(((self._DesignParameter['NAND']['_XYCoordinates'][0][0]) + self._DesignParameter['NAND']['_DesignObj']._DesignParameter['nmos1']['_XYCoordinates'][0][0]) + self._DesignParameter['NAND']['_DesignObj']._DesignParameter['nmos1']['_DesignObj']._DesignParameter['_PODummyLayer']['_XYCoordinates'][1][0]),
																		(((self._DesignParameter['NAND']['_XYCoordinates'][0][1]) + self._DesignParameter['NAND']['_DesignObj']._DesignParameter['nmos1']['_XYCoordinates'][0][1]) + self._DesignParameter['NAND']['_DesignObj']._DesignParameter['nmos1']['_DesignObj']._DesignParameter['_PODummyLayer']['_XYCoordinates'][1][1] + (self._DesignParameter['NAND']['_DesignObj']._DesignParameter['nmos1']['_DesignObj']._DesignParameter['_PODummyLayer']['_YWidth'] / 2) - (Dummy_nand_nmos1_height / 2))]
																		  ]
		self._DesignParameter['POLY_dummy_nand_nmos_2']['_XYCoordinates'] = [[(((self._DesignParameter['NAND']['_XYCoordinates'][0][0]) + self._DesignParameter['NAND']['_DesignObj']._DesignParameter['nmos2']['_XYCoordinates'][0][0]) + self._DesignParameter['NAND']['_DesignObj']._DesignParameter['nmos2']['_DesignObj']._DesignParameter['_PODummyLayer']['_XYCoordinates'][0][0]),
																		(((self._DesignParameter['NAND']['_XYCoordinates'][0][1]) + self._DesignParameter['NAND']['_DesignObj']._DesignParameter['nmos2']['_XYCoordinates'][0][1]) + self._DesignParameter['NAND']['_DesignObj']._DesignParameter['nmos2']['_DesignObj']._DesignParameter['_PODummyLayer']['_XYCoordinates'][0][1] + (self._DesignParameter['NAND']['_DesignObj']._DesignParameter['nmos2']['_DesignObj']._DesignParameter['_PODummyLayer']['_YWidth'] / 2) - (Dummy_nand_nmos2_height / 2))],
																		  [(((self._DesignParameter['NAND']['_XYCoordinates'][0][0]) + self._DesignParameter['NAND']['_DesignObj']._DesignParameter['nmos2']['_XYCoordinates'][0][0]) + self._DesignParameter['NAND']['_DesignObj']._DesignParameter['nmos2']['_DesignObj']._DesignParameter['_PODummyLayer']['_XYCoordinates'][1][0]),
																		(((self._DesignParameter['NAND']['_XYCoordinates'][0][1]) + self._DesignParameter['NAND']['_DesignObj']._DesignParameter['nmos2']['_XYCoordinates'][0][1]) + self._DesignParameter['NAND']['_DesignObj']._DesignParameter['nmos2']['_DesignObj']._DesignParameter['_PODummyLayer']['_XYCoordinates'][1][1] + (self._DesignParameter['NAND']['_DesignObj']._DesignParameter['nmos2']['_DesignObj']._DesignParameter['_PODummyLayer']['_YWidth'] / 2) - (Dummy_nand_nmos2_height / 2))]
																		  ]


		self._DesignParameter['NAND2TG_via1'] = self._SrefElementDeclaration(_DesignObj=ViaMet12Met2._ViaMet12Met2(_Name='NAND2TG_via1In{}'.format(_Name)))[0]
		self._DesignParameter['NAND2TG_via1']['_DesignObj']._CalculateDesignParameterSameEnclosure(**dict(_ViaMet12Met2NumberOfCOX=1, _ViaMet12Met2NumberOfCOY=2))
		self._DesignParameter['NAND2TG_via1']['_XYCoordinates'] = None
		XYList = []
		xy_offset = (0, (self._DesignParameter['NAND']['_DesignObj']._DesignParameter['pmos2']['_DesignObj']._DesignParameter['_METAL1PINDrawing']['_YWidth'] / 2  + drc.DRCVIAxMinSpace(2,1)/2 + drc._VIAxMinWidth/2))
		for i in range(len(self._DesignParameter['NAND']['_DesignObj']._DesignParameter['pmos2']['_DesignObj']._DesignParameter['_METAL1PINDrawing']['_XYCoordinates'])):
			if ((i % 2) == 1):
				xy = (self._DesignParameter['NAND']['_DesignObj']._DesignParameter['pmos2']['_DesignObj']._DesignParameter['_METAL1PINDrawing']['_XYCoordinates'][i][0] if (type(self._DesignParameter['NAND']['_DesignObj']._DesignParameter['pmos2']['_DesignObj']._DesignParameter['_METAL1PINDrawing']['_XYCoordinates'][i][0]) == list) else self._DesignParameter['NAND']['_DesignObj']._DesignParameter['pmos2']['_DesignObj']._DesignParameter['_METAL1PINDrawing']['_XYCoordinates'][i])
				XYList.append([((x + y) + z) for (x, y, z) in zip([(self._DesignParameter['NAND']['_XYCoordinates'][0][0] + self._DesignParameter['NAND']['_DesignObj']._DesignParameter['pmos2']['_XYCoordinates'][0][0]), (self._DesignParameter['NAND']['_XYCoordinates'][0][1] + self._DesignParameter['NAND']['_DesignObj']._DesignParameter['pmos2']['_XYCoordinates'][0][1])], xy, xy_offset)])
		self._DesignParameter['NAND2TG_via1']['_XYCoordinates'] = XYList

		self._DesignParameter['NAND2TG_via2'] = self._SrefElementDeclaration(_DesignObj=ViaMet22Met3._ViaMet22Met3(_Name='NAND2TG_via2In{}'.format(_Name)))[0]
		self._DesignParameter['NAND2TG_via2']['_DesignObj']._CalculateDesignParameterSameEnclosure(**dict(_ViaMet22Met3NumberOfCOX=1, _ViaMet22Met3NumberOfCOY=2))
		self._DesignParameter['NAND2TG_via2']['_XYCoordinates'] = XYList

		self._DesignParameter['NAND2TG_via3'] = self._SrefElementDeclaration(_DesignObj=ViaMet32Met4._ViaMet32Met4(_Name='NAND2TG_via3In{}'.format(_Name)))[0]
		self._DesignParameter['NAND2TG_via3']['_DesignObj']._CalculateDesignParameterSameEnclosure(**dict(_ViaMet32Met4NumberOfCOX=1, _ViaMet32Met4NumberOfCOY=2))
		self._DesignParameter['NAND2TG_via3']['_XYCoordinates'] = XYList

		del XYList

		if INV_finger in (1, 2):
			self._DesignParameter['INVIN_M1'] = self._PathElementDeclaration(_Layer=DesignParameters._LayerMapping['METAL1'][0], _Datatype=DesignParameters._LayerMapping['METAL1'][1], _Width=self._DesignParameter['INV']['_DesignObj']._DesignParameter['_VIAPoly2Met1_F1']['_DesignObj']._DesignParameter['_Met1Layer']['_XWidth'])
			self._DesignParameter['INVIN_M1']['_XYCoordinates'] = [[[(+ ((self._DesignParameter['INV']['_XYCoordinates'][0][0] + self._DesignParameter['INV']['_DesignObj']._DesignParameter['_VIAPoly2Met1_F1']['_XYCoordinates'][0][0]) + self._DesignParameter['INV']['_DesignObj']._DesignParameter['_VIAPoly2Met1_F1']['_DesignObj']._DesignParameter['_Met1Layer']['_XYCoordinates'][0][0])), (+ ((self._DesignParameter['INV']['_XYCoordinates'][0][1] + self._DesignParameter['INV']['_DesignObj']._DesignParameter['_VIAPoly2Met1_F1']['_XYCoordinates'][0][1]) + self._DesignParameter['INV']['_DesignObj']._DesignParameter['_VIAPoly2Met1_F1']['_DesignObj']._DesignParameter['_Met1Layer']['_XYCoordinates'][0][1]))], [((self._DesignParameter['INV']['_XYCoordinates'][0][0] + self._DesignParameter['INV']['_DesignObj']._DesignParameter['_VIAPoly2Met1_F1']['_XYCoordinates'][0][0]) + self._DesignParameter['INV']['_DesignObj']._DesignParameter['_VIAPoly2Met1_F1']['_DesignObj']._DesignParameter['_Met1Layer']['_XYCoordinates'][0][0]), ((self._DesignParameter['NAND']['_XYCoordinates'][0][1] + self._DesignParameter['NAND']['_DesignObj']._DesignParameter['m1_pmos_parallel_routing_x']['_XYCoordinates'][0][0][1]) + (self._DesignParameter['INV']['_DesignObj']._DesignParameter['_VIAPoly2Met1_F1']['_DesignObj']._DesignParameter['_Met1Layer']['_XWidth'] / 2))]]]
			self._DesignParameter['NAND2INV'] = self._PathElementDeclaration(_Layer=DesignParameters._LayerMapping['METAL1'][0], _Datatype=DesignParameters._LayerMapping['METAL1'][1], _Width=self._DesignParameter['INV']['_DesignObj']._DesignParameter['_VIAPoly2Met1_F1']['_DesignObj']._DesignParameter['_Met1Layer']['_XWidth'])
			self._DesignParameter['NAND2INV']['_XYCoordinates'] = [[[(self._DesignParameter['NAND']['_XYCoordinates'][0][0] + self._DesignParameter['NAND']['_DesignObj']._DesignParameter['m1_nmos1_out']['_XYCoordinates'][0][0][0]), (self._DesignParameter['INVIN_M1']['_XYCoordinates'][0][1][1] - (self._DesignParameter['INV']['_DesignObj']._DesignParameter['_VIAPoly2Met1_F1']['_DesignObj']._DesignParameter['_Met1Layer']['_XWidth'] / 2))], [self._DesignParameter['INVIN_M1']['_XYCoordinates'][0][0][0], (self._DesignParameter['INVIN_M1']['_XYCoordinates'][0][1][1] - (self._DesignParameter['INV']['_DesignObj']._DesignParameter['_VIAPoly2Met1_F1']['_DesignObj']._DesignParameter['_Met1Layer']['_XWidth'] / 2))]]]
		else :
			self._DesignParameter['nand2inv_m1_1'] = self._PathElementDeclaration(_Layer=DesignParameters._LayerMapping['METAL1'][0], _Datatype=DesignParameters._LayerMapping['METAL1'][1], _Width=self._DesignParameter['NAND']['_DesignObj']._DesignParameter['m1_pmos_parallel_routing_x']['_Width'])
			self._DesignParameter['nand2inv_m1_1']['_XYCoordinates'] = [[[(self._DesignParameter['NAND']['_XYCoordinates'][0][0] + self._DesignParameter['NAND']['_DesignObj']._DesignParameter['m1_nmos1_out']['_XYCoordinates'][0][0][0]), (self._DesignParameter['NAND']['_XYCoordinates'][0][1] + self._DesignParameter['NAND']['_DesignObj']._DesignParameter['m1_pmos_parallel_routing_x']['_XYCoordinates'][0][0][1])],
																		 [((((self._DesignParameter['NAND']['_XYCoordinates'][0][0] + self._DesignParameter['NAND']['_DesignObj']._DesignParameter['pmos2']['_XYCoordinates'][0][0]) + self._DesignParameter['NAND']['_DesignObj']._DesignParameter['pmos2']['_DesignObj']._DesignParameter['_PODummyLayer']['_XYCoordinates'][1][0]) / 2) + (((self._DesignParameter['INV']['_XYCoordinates'][0][0] + self._DesignParameter['INV']['_DesignObj']._DesignParameter['_PMOS']['_XYCoordinates'][0][0]) + self._DesignParameter['INV']['_DesignObj']._DesignParameter['_PMOS']['_DesignObj']._DesignParameter['_PODummyLayer']['_XYCoordinates'][0][0]) / 2) + self._DesignParameter['NAND']['_DesignObj']._DesignParameter['m1_pmos_parallel_routing_x']['_Width']/2), (self._DesignParameter['NAND']['_XYCoordinates'][0][1] + self._DesignParameter['NAND']['_DesignObj']._DesignParameter['m1_pmos_parallel_routing_x']['_XYCoordinates'][0][0][1])]]]
			self._DesignParameter['nand2inv_m1_2'] = self._PathElementDeclaration(_Layer=DesignParameters._LayerMapping['METAL1'][0], _Datatype=DesignParameters._LayerMapping['METAL1'][1], _Width=self._DesignParameter['NAND']['_DesignObj']._DesignParameter['m1_pmos_parallel_routing_x']['_Width'])
			self._DesignParameter['nand2inv_m1_2']['_XYCoordinates'] = [[[(+ self._DesignParameter['nand2inv_m1_1']['_XYCoordinates'][0][1][0] - self._DesignParameter['NAND']['_DesignObj']._DesignParameter['m1_pmos_parallel_routing_x']['_Width']/2), (+ self._DesignParameter['nand2inv_m1_1']['_XYCoordinates'][0][1][1])], [self._DesignParameter['nand2inv_m1_1']['_XYCoordinates'][0][1][0] - self._DesignParameter['NAND']['_DesignObj']._DesignParameter['m1_pmos_parallel_routing_x']['_Width']/2, (((self._DesignParameter['INV']['_XYCoordinates'][0][1] + self._DesignParameter['INV']['_DesignObj']._DesignParameter['_InputRouting']['_XYCoordinates'][0][0][1]) / 2) + ((self._DesignParameter['INV']['_XYCoordinates'][0][1] + self._DesignParameter['INV']['_DesignObj']._DesignParameter['_InputRouting']['_XYCoordinates'][0][1][1]) / 2))]]]
			self._DesignParameter['nand2m1_3'] = self._PathElementDeclaration(_Layer=DesignParameters._LayerMapping['METAL1'][0], _Datatype=DesignParameters._LayerMapping['METAL1'][1], _Width=self._DesignParameter['NAND']['_DesignObj']._DesignParameter['m1_pmos_parallel_routing_x']['_Width'])
			self._DesignParameter['nand2m1_3']['_XYCoordinates'] = [[[(+ self._DesignParameter['nand2inv_m1_2']['_XYCoordinates'][0][1][0] - self._DesignParameter['NAND']['_DesignObj']._DesignParameter['m1_pmos_parallel_routing_x']['_Width']/2), (+ self._DesignParameter['nand2inv_m1_2']['_XYCoordinates'][0][1][1])], [(self._DesignParameter['INV']['_XYCoordinates'][0][0] + self._DesignParameter['INV']['_DesignObj']._DesignParameter['_InputRouting']['_XYCoordinates'][0][0][0]), self._DesignParameter['nand2inv_m1_2']['_XYCoordinates'][0][1][1]]]]

		TG_PMOS_y = (VDD2PMOS + ((TG_pmos_width - (INV_nmos_width * 2)) / 2))
		# self._DesignParameter['TR_GATE'] = self._SrefElementDeclaration(_DesignObj=TG_2X_CRIT_SLVT_v1.TG_2X_CRIT_SLVT_v1(_Name='TR_GATEIn{}'.format(_Name)))[0]
		# self._DesignParameter['TR_GATE']['_DesignObj']._CalculateDesignParameter(**dict(nmos_gate=TG_finger, pmos_gate=TG_finger, nmos_width=TG_nmos_width, pmos_width=TG_pmos_width, length=gate_length, XVT=XVT, nmos_y=NMOS_y, pmos_y=TG_PMOS_y, gate_y=TG_poly_y, vss2vdd_height=Cell_height, gate_spacing=gate_spacing, sdwidth=66, power_xnum=2, power_xdistance=130, out_even_up_mode=True))
		# self._DesignParameter['TR_GATE']['_XYCoordinates'] = [[((((self._DesignParameter['INV']['_DesignObj']._DesignParameter['XVTLayer']['_XWidth'] / 2) + (self._DesignParameter['TR_GATE']['_DesignObj']._DesignParameter['XVT_boundary_1']['_XWidth'] / 2)) + gate_length) + gate_spacing), self._DesignParameter['INV']['_XYCoordinates'][0][1]]]
		self._DesignParameter['TR_GATE'] = self._SrefElementDeclaration(_DesignObj=Transmission_gate.Transmission_gate(_Name='TR_GATEIn{}'.format(_Name)))[0]
		self._DesignParameter['TR_GATE']['_DesignObj']._CalculateDesignParameter(**dict(nmos_gate=TG_finger, pmos_gate=TG_finger, nmos_width=TG_nmos_width, pmos_width=TG_pmos_width, length=gate_length, XVT=XVT, vss2nmos=NMOS_y, vdd2pmos=TG_PMOS_y, gate_y=TG_poly_y, vss2vdd_height=Cell_height, gate_spacing=gate_spacing, sdwidth=66, power_xdistance=130))
		self._DesignParameter['TR_GATE']['_XYCoordinates'] = [[((((self._DesignParameter['INV']['_DesignObj']._DesignParameter['XVTLayer']['_XWidth'] / 2) + (self._DesignParameter['TR_GATE']['_DesignObj']._DesignParameter['XVT_boundary_1']['_XWidth'] / 2)) + gate_length) + gate_spacing), self._DesignParameter['INV']['_XYCoordinates'][0][1]]]
		self._DesignParameter['TR_GATE']['_Reflect'] = [1, 0, 0]
		self._DesignParameter['TR_GATE']['_Angle'] = 180
		##dummy for tr_gate
		self._DesignParameter['POLY_dummy_trgate_pmos'] = self._BoundaryElementDeclaration(_Layer=DesignParameters._LayerMapping['POLY'][0], _Datatype=DesignParameters._LayerMapping['POLY'][1], _XWidth=gate_length)
		self._DesignParameter['POLY_dummy_trgate_pmos']['_YWidth'] = self._DesignParameter['TR_GATE']['_DesignObj']._DesignParameter['pmos']['_DesignObj']._DesignParameter['_PODummyLayer']['_YWidth']
		self._DesignParameter['POLY_dummy_trgate_nmos'] = self._BoundaryElementDeclaration(_Layer=DesignParameters._LayerMapping['POLY'][0], _Datatype=DesignParameters._LayerMapping['POLY'][1], _XWidth=gate_length)
		self._DesignParameter['POLY_dummy_trgate_nmos']['_YWidth'] = self._DesignParameter['TR_GATE']['_DesignObj']._DesignParameter['nmos']['_DesignObj']._DesignParameter['_PODummyLayer']['_YWidth']


		if float(self._DesignParameter['POLY_dummy_trgate_pmos']['_XWidth']) * float(self._DesignParameter['POLY_dummy_trgate_pmos']['_YWidth']) < drc._PODummyMinArea:
			self._DesignParameter['POLY_dummy_trgate_pmos']['_YWidth'] = self.CeilMinSnapSpacing(float(drc._PODummyMinArea) / float(self._DesignParameter['POLY_dummy_trgate_pmos']['_XWidth']), drc._MinSnapSpacing * 2)
		else:
			pass

		if float(self._DesignParameter['POLY_dummy_trgate_nmos']['_XWidth']) * float(self._DesignParameter['POLY_dummy_trgate_nmos']['_YWidth']) < drc._PODummyMinArea:
			self._DesignParameter['POLY_dummy_trgate_nmos']['_YWidth'] = self.CeilMinSnapSpacing(float(drc._PODummyMinArea) / float(self._DesignParameter['POLY_dummy_trgate_nmos']['_XWidth']), drc._MinSnapSpacing * 2)
		else:
			pass

		Dummy_trgate_pmos_height = self._DesignParameter['POLY_dummy_trgate_pmos']['_YWidth']
		Dummy_trgate_nmos_height = self._DesignParameter['POLY_dummy_trgate_nmos']['_YWidth']
		self._DesignParameter['POLY_dummy_trgate_pmos']['_XYCoordinates'] = [[(((self._DesignParameter['TR_GATE']['_XYCoordinates'][0][0]) + self._DesignParameter['TR_GATE']['_DesignObj']._DesignParameter['pmos']['_XYCoordinates'][0][0]) + self._DesignParameter['TR_GATE']['_DesignObj']._DesignParameter['pmos']['_DesignObj']._DesignParameter['_PODummyLayer']['_XYCoordinates'][0][0]),
																			((self._DesignParameter['TR_GATE']['_XYCoordinates'][0][1]) + self._DesignParameter['TR_GATE']['_DesignObj']._DesignParameter['pmos']['_XYCoordinates'][0][1]) + self._DesignParameter['TR_GATE']['_DesignObj']._DesignParameter['pmos']['_DesignObj']._DesignParameter['_PODummyLayer']['_XYCoordinates'][0][1] - (self._DesignParameter['TR_GATE']['_DesignObj']._DesignParameter['pmos']['_DesignObj']._DesignParameter['_PODummyLayer']['_YWidth'] / 2) + (Dummy_trgate_pmos_height / 2)],
																			   [(((self._DesignParameter['TR_GATE']['_XYCoordinates'][0][0]) + self._DesignParameter['TR_GATE']['_DesignObj']._DesignParameter['pmos']['_XYCoordinates'][0][0]) + self._DesignParameter['TR_GATE']['_DesignObj']._DesignParameter['pmos']['_DesignObj']._DesignParameter['_PODummyLayer']['_XYCoordinates'][1][0]),
																			((self._DesignParameter['TR_GATE']['_XYCoordinates'][0][1]) + self._DesignParameter['TR_GATE']['_DesignObj']._DesignParameter['pmos']['_XYCoordinates'][0][1]) + self._DesignParameter['TR_GATE']['_DesignObj']._DesignParameter['pmos']['_DesignObj']._DesignParameter['_PODummyLayer']['_XYCoordinates'][1][1] - (self._DesignParameter['TR_GATE']['_DesignObj']._DesignParameter['pmos']['_DesignObj']._DesignParameter['_PODummyLayer']['_YWidth'] / 2) + (Dummy_trgate_pmos_height / 2)],
																			   [((self._DesignParameter['TR_GATE']['_XYCoordinates'][0][0]) + self._DesignParameter['TR_GATE']['_DesignObj']._DesignParameter['pmos_second_podummy']['_XYCoordinates'][0][0]),
																			((self._DesignParameter['TR_GATE']['_XYCoordinates'][0][1]) + self._DesignParameter['TR_GATE']['_DesignObj']._DesignParameter['pmos_second_podummy']['_XYCoordinates'][0][1])- (self._DesignParameter['TR_GATE']['_DesignObj']._DesignParameter['pmos_second_podummy']['_YWidth'] / 2) + (Dummy_trgate_pmos_height / 2)],
																			   [((self._DesignParameter['TR_GATE']['_XYCoordinates'][0][0]) + self._DesignParameter['TR_GATE']['_DesignObj']._DesignParameter['pmos_second_podummy']['_XYCoordinates'][1][0]),
																			((self._DesignParameter['TR_GATE']['_XYCoordinates'][0][1]) + self._DesignParameter['TR_GATE']['_DesignObj']._DesignParameter['pmos_second_podummy']['_XYCoordinates'][1][1]) - (self._DesignParameter['TR_GATE']['_DesignObj']._DesignParameter['pmos_second_podummy']['_YWidth'] / 2) + (Dummy_trgate_pmos_height / 2)],
																			   ]
		self._DesignParameter['POLY_dummy_trgate_nmos']['_XYCoordinates'] = [[(((self._DesignParameter['TR_GATE']['_XYCoordinates'][0][0]) + self._DesignParameter['TR_GATE']['_DesignObj']._DesignParameter['nmos']['_XYCoordinates'][0][0]) + self._DesignParameter['TR_GATE']['_DesignObj']._DesignParameter['nmos']['_DesignObj']._DesignParameter['_PODummyLayer']['_XYCoordinates'][0][0]),
																			((self._DesignParameter['TR_GATE']['_XYCoordinates'][0][1]) + self._DesignParameter['TR_GATE']['_DesignObj']._DesignParameter['nmos']['_XYCoordinates'][0][1]) + self._DesignParameter['TR_GATE']['_DesignObj']._DesignParameter['nmos']['_DesignObj']._DesignParameter['_PODummyLayer']['_XYCoordinates'][0][1] + (self._DesignParameter['TR_GATE']['_DesignObj']._DesignParameter['nmos']['_DesignObj']._DesignParameter['_PODummyLayer']['_YWidth'] / 2) - (Dummy_trgate_nmos_height / 2)],
																			   [(((self._DesignParameter['TR_GATE']['_XYCoordinates'][0][0]) + self._DesignParameter['TR_GATE']['_DesignObj']._DesignParameter['nmos']['_XYCoordinates'][0][0]) + self._DesignParameter['TR_GATE']['_DesignObj']._DesignParameter['nmos']['_DesignObj']._DesignParameter['_PODummyLayer']['_XYCoordinates'][1][0]),
																			((self._DesignParameter['TR_GATE']['_XYCoordinates'][0][1]) + self._DesignParameter['TR_GATE']['_DesignObj']._DesignParameter['nmos']['_XYCoordinates'][0][1]) + self._DesignParameter['TR_GATE']['_DesignObj']._DesignParameter['nmos']['_DesignObj']._DesignParameter['_PODummyLayer']['_XYCoordinates'][1][1] + (self._DesignParameter['TR_GATE']['_DesignObj']._DesignParameter['nmos']['_DesignObj']._DesignParameter['_PODummyLayer']['_YWidth'] / 2) - (Dummy_trgate_nmos_height / 2)],
																			   [((self._DesignParameter['TR_GATE']['_XYCoordinates'][0][0]) + self._DesignParameter['TR_GATE']['_DesignObj']._DesignParameter['nmos_second_podummy']['_XYCoordinates'][0][0]),
																			((self._DesignParameter['TR_GATE']['_XYCoordinates'][0][1]) + self._DesignParameter['TR_GATE']['_DesignObj']._DesignParameter['nmos_second_podummy']['_XYCoordinates'][0][1]) + (self._DesignParameter['TR_GATE']['_DesignObj']._DesignParameter['nmos_second_podummy']['_YWidth'] / 2) - (Dummy_trgate_nmos_height / 2)],
																			   [((self._DesignParameter['TR_GATE']['_XYCoordinates'][0][0]) + self._DesignParameter['TR_GATE']['_DesignObj']._DesignParameter['nmos_second_podummy']['_XYCoordinates'][1][0]),
																			((self._DesignParameter['TR_GATE']['_XYCoordinates'][0][1]) + self._DesignParameter['TR_GATE']['_DesignObj']._DesignParameter['nmos_second_podummy']['_XYCoordinates'][1][1]) + (self._DesignParameter['TR_GATE']['_DesignObj']._DesignParameter['nmos_second_podummy']['_YWidth'] / 2) - (Dummy_trgate_nmos_height / 2)],
																			   ]

		self._DesignParameter['VDD_M2'] = self._PathElementDeclaration(_Layer=DesignParameters._LayerMapping['METAL2'][0], _Datatype=DesignParameters._LayerMapping['METAL2'][1], _Width=self._DesignParameter['INV']['_DesignObj']._DesignParameter['NbodyContact']['_DesignObj']._DesignParameter['_Met2Layer']['_YWidth'])
		self._DesignParameter['VDD_M2']['_XYCoordinates'] = [[[(+ (self._DesignParameter['NAND']['_XYCoordinates'][0][0] + self._DesignParameter['NAND']['_DesignObj']._DesignParameter['m2_supply']['_XYCoordinates'][1][0])), (+ (self._DesignParameter['NAND']['_XYCoordinates'][0][1] + self._DesignParameter['NAND']['_DesignObj']._DesignParameter['m2_supply']['_XYCoordinates'][1][1]))], [(+ (self._DesignParameter['TR_GATE']['_XYCoordinates'][0][0] + self._DesignParameter['TR_GATE']['_DesignObj']._DesignParameter['vdd_supply_m2_y']['_XYCoordinates'][0][0])), (+ (self._DesignParameter['TR_GATE']['_XYCoordinates'][0][1] + self._DesignParameter['TR_GATE']['_DesignObj']._DesignParameter['vdd_supply_m2_y']['_XYCoordinates'][0][1]))]]]
		self._DesignParameter['VDD_DIFF'] = self._PathElementDeclaration(_Layer=DesignParameters._LayerMapping['DIFF'][0], _Datatype=DesignParameters._LayerMapping['DIFF'][1], _Width=self._DesignParameter['NAND']['_DesignObj']._DesignParameter['supply_od']['_YWidth'])
		self._DesignParameter['VDD_DIFF']['_XYCoordinates'] = [[[((self._DesignParameter['TR_GATE']['_XYCoordinates'][0][0] + self._DesignParameter['TR_GATE']['_DesignObj']._DesignParameter['vdd_odlayer']['_XYCoordinates'][0][0]) + (self._DesignParameter['TR_GATE']['_DesignObj']._DesignParameter['vdd_odlayer']['_XWidth'] / 2)), (self._DesignParameter['TR_GATE']['_XYCoordinates'][0][1] + self._DesignParameter['TR_GATE']['_DesignObj']._DesignParameter['vdd_odlayer']['_XYCoordinates'][0][1])], [(self._DesignParameter['NAND']['_XYCoordinates'][0][0] + self._DesignParameter['NAND']['_DesignObj']._DesignParameter['supply_od']['_XYCoordinates'][1][0]), (self._DesignParameter['TR_GATE']['_XYCoordinates'][0][1] + self._DesignParameter['TR_GATE']['_DesignObj']._DesignParameter['vdd_odlayer']['_XYCoordinates'][0][1])]]]
		self._DesignParameter['XVT_Around'] = self._PathElementDeclaration(_Layer=DesignParameters._LayerMapping['RVT'][0], _Datatype=DesignParameters._LayerMapping['RVT'][1], _Width=self._DesignParameter['TR_GATE']['_DesignObj']._DesignParameter['XVT_boundary_1']['_YWidth'])
		self._DesignParameter['XVT_Around']['_XYCoordinates'] = [[[((self._DesignParameter['NAND']['_XYCoordinates'][0][0] + self._DesignParameter['NAND']['_DesignObj']._DesignParameter['xvtlayer']['_XYCoordinates'][0][0]) - (self._DesignParameter['NAND']['_DesignObj']._DesignParameter['xvtlayer']['_XWidth'] / 2)), (self._DesignParameter['NAND']['_XYCoordinates'][0][1] + self._DesignParameter['NAND']['_DesignObj']._DesignParameter['xvtlayer']['_XYCoordinates'][0][1])], [((self._DesignParameter['TR_GATE']['_XYCoordinates'][0][0] + self._DesignParameter['TR_GATE']['_DesignObj']._DesignParameter['XVT_boundary_1']['_XYCoordinates'][0][0]) + (self._DesignParameter['TR_GATE']['_DesignObj']._DesignParameter['XVT_boundary_1']['_XWidth'] / 2)), (self._DesignParameter['NAND']['_XYCoordinates'][0][1] + self._DesignParameter['NAND']['_DesignObj']._DesignParameter['xvtlayer']['_XYCoordinates'][0][1])]]]
		self._DesignParameter['VSS_M2'] = self._PathElementDeclaration(_Layer=DesignParameters._LayerMapping['METAL2'][0], _Datatype=DesignParameters._LayerMapping['METAL2'][1], _Width=self._DesignParameter['NAND']['_DesignObj']._DesignParameter['m2_supply']['_YWidth'])
		self._DesignParameter['VSS_M2']['_XYCoordinates'] = [[[(+ (self._DesignParameter['NAND']['_XYCoordinates'][0][0] + self._DesignParameter['NAND']['_DesignObj']._DesignParameter['m2_supply']['_XYCoordinates'][0][0])), (+ (self._DesignParameter['NAND']['_XYCoordinates'][0][1] + self._DesignParameter['NAND']['_DesignObj']._DesignParameter['m2_supply']['_XYCoordinates'][0][1]))], [(self._DesignParameter['TR_GATE']['_XYCoordinates'][0][0] + self._DesignParameter['TR_GATE']['_DesignObj']._DesignParameter['vss_supply_m2_y']['_XYCoordinates'][0][0]), (self._DesignParameter['NAND']['_XYCoordinates'][0][1] + self._DesignParameter['NAND']['_DesignObj']._DesignParameter['m2_supply']['_XYCoordinates'][0][1])]]]
		self._DesignParameter['VSS_DIFF'] = self._PathElementDeclaration(_Layer=DesignParameters._LayerMapping['DIFF'][0], _Datatype=DesignParameters._LayerMapping['DIFF'][1], _Width=self._DesignParameter['NAND']['_DesignObj']._DesignParameter['supply_od']['_YWidth'])
		self._DesignParameter['VSS_DIFF']['_XYCoordinates'] = [[[(+ (self._DesignParameter['NAND']['_XYCoordinates'][0][0] + self._DesignParameter['NAND']['_DesignObj']._DesignParameter['supply_od']['_XYCoordinates'][0][0])), (+ (self._DesignParameter['NAND']['_XYCoordinates'][0][1] + self._DesignParameter['NAND']['_DesignObj']._DesignParameter['supply_od']['_XYCoordinates'][0][1]))], [((self._DesignParameter['TR_GATE']['_XYCoordinates'][0][0] + self._DesignParameter['TR_GATE']['_DesignObj']._DesignParameter['vss_odlayer']['_XYCoordinates'][0][0]) + (self._DesignParameter['TR_GATE']['_DesignObj']._DesignParameter['vss_odlayer']['_XWidth'] / 2)), (self._DesignParameter['NAND']['_XYCoordinates'][0][1] + self._DesignParameter['NAND']['_DesignObj']._DesignParameter['supply_od']['_XYCoordinates'][0][1])]]]
		self._DesignParameter['VSS_PIMP'] = self._PathElementDeclaration(_Layer=DesignParameters._LayerMapping['PIMP'][0], _Datatype=DesignParameters._LayerMapping['PIMP'][1], _Width=self._DesignParameter['NAND']['_DesignObj']._DesignParameter['pp_vss']['_YWidth'])
		self._DesignParameter['VSS_PIMP']['_XYCoordinates'] = [[[(+ (self._DesignParameter['NAND']['_XYCoordinates'][0][0] + self._DesignParameter['NAND']['_DesignObj']._DesignParameter['pp_vss']['_XYCoordinates'][0][0])), (+ (self._DesignParameter['NAND']['_XYCoordinates'][0][1] + self._DesignParameter['NAND']['_DesignObj']._DesignParameter['pp_vss']['_XYCoordinates'][0][1]))], [((self._DesignParameter['TR_GATE']['_XYCoordinates'][0][0] + self._DesignParameter['TR_GATE']['_DesignObj']._DesignParameter['vss_pplayer']['_XYCoordinates'][0][0]) + (self._DesignParameter['TR_GATE']['_DesignObj']._DesignParameter['vss_pplayer']['_XWidth'] / 2)), (self._DesignParameter['NAND']['_XYCoordinates'][0][1] + self._DesignParameter['NAND']['_DesignObj']._DesignParameter['pp_vss']['_XYCoordinates'][0][1])]]]
		self._DesignParameter['INV2TG'] = self._PathElementDeclaration(_Layer=DesignParameters._LayerMapping['METAL1'][0], _Datatype=DesignParameters._LayerMapping['METAL1'][1], _Width=self._DesignParameter['INV']['_DesignObj']._DesignParameter['_OutputRouting']['_Width']) ##(self._DesignParameter['TR_GATE']['_DesignObj']._DesignParameter['gate_input']['_DesignObj']._DesignParameter['_Met1Layer']['_YWidth'])
		self._DesignParameter['INV2TG']['_XYCoordinates'] = [[[(+ ((self._DesignParameter['TR_GATE']['_XYCoordinates'][0][0] + self._DesignParameter['TR_GATE']['_DesignObj']._DesignParameter['gate_input']['_XYCoordinates'][0][0]) + self._DesignParameter['TR_GATE']['_DesignObj']._DesignParameter['gate_input']['_DesignObj']._DesignParameter['_Met1Layer']['_XYCoordinates'][0][0])), (+ ((self._DesignParameter['TR_GATE']['_XYCoordinates'][0][1] + self._DesignParameter['TR_GATE']['_DesignObj']._DesignParameter['gate_input']['_XYCoordinates'][0][1]) + self._DesignParameter['TR_GATE']['_DesignObj']._DesignParameter['gate_input']['_DesignObj']._DesignParameter['_Met1Layer']['_XYCoordinates'][0][1]))], [(self._DesignParameter['INV']['_XYCoordinates'][0][0] + self._DesignParameter['INV']['_DesignObj']._DesignParameter['_OutputRouting']['_XYCoordinates'][0][0][0]), ((self._DesignParameter['TR_GATE']['_XYCoordinates'][0][1] + self._DesignParameter['TR_GATE']['_DesignObj']._DesignParameter['gate_input']['_XYCoordinates'][0][1]) + self._DesignParameter['TR_GATE']['_DesignObj']._DesignParameter['gate_input']['_DesignObj']._DesignParameter['_Met1Layer']['_XYCoordinates'][0][1])]]]

		self._DesignParameter['NAND2TG_M4_1'] = self._PathElementDeclaration(_Layer=DesignParameters._LayerMapping['METAL4'][0], _Datatype=DesignParameters._LayerMapping['METAL4'][1], _Width=self._DesignParameter['NAND2TG_via1']['_DesignObj']._DesignParameter['_Met2Layer']['_XWidth'])
		self._DesignParameter['NAND2TG_M4_1']['_XYCoordinates'] = [[[(+ self._DesignParameter['NAND2TG_via1']['_XYCoordinates'][0][0]), (+ self._DesignParameter['NAND2TG_via1']['_XYCoordinates'][0][1] - drc.DRCVIAxMinSpace(2,1)/2 - drc._VIAxMinWidth/2)], [(self._DesignParameter['TR_GATE']['_XYCoordinates'][0][0] + self._DesignParameter['TR_GATE']['_DesignObj']._DesignParameter['gate_output']['_XYCoordinates'][0][0]), self._DesignParameter['NAND2TG_via1']['_XYCoordinates'][0][1] - drc.DRCVIAxMinSpace(2,1)/2 - drc._VIAxMinWidth/2]]]

		self._DesignParameter['nand2tg_via_3'] = self._SrefElementDeclaration(_DesignObj=ViaMet32Met4._ViaMet32Met4(_Name='nand2tg_via_3In{}'.format(_Name)))[0]
		self._DesignParameter['nand2tg_via_3']['_DesignObj']._CalculateDesignParameterSameEnclosure(**dict(_ViaMet32Met4NumberOfCOX=1, _ViaMet32Met4NumberOfCOY=2))
		self._DesignParameter['nand2tg_via_3']['_XYCoordinates'] = [[(+ self._DesignParameter['NAND2TG_M4_1']['_XYCoordinates'][0][1][0]), (+ self._DesignParameter['NAND2TG_M4_1']['_XYCoordinates'][0][1][1] + drc.DRCVIAxMinSpace(2,1)/2 + drc._VIAxMinWidth/2)]]

		self._DesignParameter['nand2tg_M3'] = self._PathElementDeclaration(_Layer=DesignParameters._LayerMapping['METAL3'][0], _Datatype=DesignParameters._LayerMapping['METAL3'][1], _Width=self._DesignParameter['nand2tg_via_3']['_DesignObj']._DesignParameter['_Met3Layer']['_XWidth'])
		self._DesignParameter['nand2tg_M3']['_XYCoordinates'] = [[[(+ self._DesignParameter['nand2tg_via_3']['_XYCoordinates'][0][0]), (+ self._DesignParameter['nand2tg_via_3']['_XYCoordinates'][0][1])], [self._DesignParameter['nand2tg_via_3']['_XYCoordinates'][0][0], (((self._DesignParameter['TR_GATE']['_XYCoordinates'][0][1] + self._DesignParameter['TR_GATE']['_DesignObj']._DesignParameter['gate_output']['_XYCoordinates'][0][1]) + self._DesignParameter['TR_GATE']['_DesignObj']._DesignParameter['gate_output']['_DesignObj']._DesignParameter['_Met1Layer']['_XYCoordinates'][0][1]) - (self._DesignParameter['TR_GATE']['_DesignObj']._DesignParameter['gate_output']['_DesignObj']._DesignParameter['_Met1Layer']['_YWidth'] / 2))]]]

		self._DesignParameter['nand2tg_via'] = self._SrefElementDeclaration(_DesignObj=ViaMet12Met2._ViaMet12Met2(_Name='nand2tg_viaIn{}'.format(_Name)))[0]
		self._DesignParameter['nand2tg_via']['_DesignObj']._CalculateDesignParameterSameEnclosure(**dict(_ViaMet12Met2NumberOfCOX=1, _ViaMet12Met2NumberOfCOY=2))
		self._DesignParameter['nand2tg_via']['_XYCoordinates'] = [[(+ self._DesignParameter['NAND2TG_M4_1']['_XYCoordinates'][0][1][0]), (self._DesignParameter['TR_GATE']['_XYCoordinates'][0][1] + self._DesignParameter['TR_GATE']['_DesignObj']._DesignParameter['gate_output']['_XYCoordinates'][0][1] + self._DesignParameter['TR_GATE']['_DesignObj']._DesignParameter['gate_output']['_DesignObj']._DesignParameter['_Met1Layer']['_XYCoordinates'][0][1] - self._DesignParameter['TR_GATE']['_DesignObj']._DesignParameter['gate_output']['_DesignObj']._DesignParameter['_Met1Layer']['_YWidth'] / 2)]]

		self._DesignParameter['nand2tg_via_2'] = self._SrefElementDeclaration(_DesignObj=ViaMet22Met3._ViaMet22Met3(_Name='nand2tg_via_2In{}'.format(_Name)))[0]
		self._DesignParameter['nand2tg_via_2']['_DesignObj']._CalculateDesignParameterSameEnclosure(**dict(_ViaMet22Met3NumberOfCOX=1, _ViaMet22Met3NumberOfCOY=2))
		self._DesignParameter['nand2tg_via_2']['_XYCoordinates'] = [[(+ self._DesignParameter['NAND2TG_M4_1']['_XYCoordinates'][0][1][0]), (self._DesignParameter['TR_GATE']['_XYCoordinates'][0][1] + self._DesignParameter['TR_GATE']['_DesignObj']._DesignParameter['gate_output']['_XYCoordinates'][0][1] + self._DesignParameter['TR_GATE']['_DesignObj']._DesignParameter['gate_output']['_DesignObj']._DesignParameter['_Met1Layer']['_XYCoordinates'][0][1] - self._DesignParameter['TR_GATE']['_DesignObj']._DesignParameter['gate_output']['_DesignObj']._DesignParameter['_Met1Layer']['_YWidth'] / 2)]]

		self._DesignParameter['NW_all'] = self._PathElementDeclaration(_Layer=DesignParameters._LayerMapping['NWELL'][0], _Datatype=DesignParameters._LayerMapping['NWELL'][1], _Width=self._DesignParameter['TR_GATE']['_DesignObj']._DesignParameter['NWELL_boundary_0']['_YWidth'])
		self._DesignParameter['NW_all']['_XYCoordinates'] = [[[((self._DesignParameter['NAND']['_XYCoordinates'][0][0] + self._DesignParameter['NAND']['_DesignObj']._DesignParameter['nw_layer']['_XYCoordinates'][0][0]) - (self._DesignParameter['NAND']['_DesignObj']._DesignParameter['nw_layer']['_XWidth'] / 2)),
															   ((((self._DesignParameter['TR_GATE']['_XYCoordinates'][0][1] + self._DesignParameter['TR_GATE']['_DesignObj']._DesignParameter['NWELL_boundary_0']['_XYCoordinates'][0][1]))))],
															  [((self._DesignParameter['TR_GATE']['_XYCoordinates'][0][0] + self._DesignParameter['TR_GATE']['_DesignObj']._DesignParameter['NWELL_boundary_0']['_XYCoordinates'][0][0]) + (self._DesignParameter['TR_GATE']['_DesignObj']._DesignParameter['NWELL_boundary_0']['_XWidth'] / 2)),
															   ((((self._DesignParameter['TR_GATE']['_XYCoordinates'][0][1] + self._DesignParameter['TR_GATE']['_DesignObj']._DesignParameter['NWELL_boundary_0']['_XYCoordinates'][0][1]))))]]]
		self._DesignParameter['pmos_all_pimp'] = self._PathElementDeclaration(_Layer=DesignParameters._LayerMapping['PIMP'][0], _Datatype=DesignParameters._LayerMapping['PIMP'][1], _Width=self._DesignParameter['NAND']['_DesignObj']._DesignParameter['pp_pmos']['_YWidth'])
		self._DesignParameter['pmos_all_pimp']['_XYCoordinates'] = [[[self._DesignParameter['NW_all']['_XYCoordinates'][0][0][0], (self._DesignParameter['NAND']['_XYCoordinates'][0][1] + self._DesignParameter['NAND']['_DesignObj']._DesignParameter['pp_pmos']['_XYCoordinates'][0][1])], [self._DesignParameter['NW_all']['_XYCoordinates'][0][1][0], (self._DesignParameter['NAND']['_XYCoordinates'][0][1] + self._DesignParameter['NAND']['_DesignObj']._DesignParameter['pp_pmos']['_XYCoordinates'][0][1])]]]

		self._DesignParameter['INb_m2_1'] = self._PathElementDeclaration(_Layer=DesignParameters._LayerMapping['METAL2'][0], _Datatype=DesignParameters._LayerMapping['METAL2'][1], _Width=drc._Metal1MinWidth)
		self._DesignParameter['INb_m2_1']['_XYCoordinates'] = [[[(((self._DesignParameter['NAND']['_XYCoordinates'][0][0] + self._DesignParameter['NAND']['_DesignObj']._DesignParameter['gate_b_input']['_XYCoordinates'][0][0]) + self._DesignParameter['NAND']['_DesignObj']._DesignParameter['gate_b_input']['_DesignObj']._DesignParameter['_Met1Layer']['_XYCoordinates'][0][0]) + (self._DesignParameter['NAND']['_DesignObj']._DesignParameter['gate_b_input']['_DesignObj']._DesignParameter['_Met1Layer']['_XWidth'] / 2)), (((self._DesignParameter['NAND']['_XYCoordinates'][0][1] + self._DesignParameter['NAND']['_DesignObj']._DesignParameter['gate_b_input']['_XYCoordinates'][0][1]) + self._DesignParameter['NAND']['_DesignObj']._DesignParameter['gate_b_input']['_DesignObj']._DesignParameter['_Met1Layer']['_XYCoordinates'][0][1]) + (self._DesignParameter['NAND']['_DesignObj']._DesignParameter['gate_b_input']['_DesignObj']._DesignParameter['_Met1Layer']['_YWidth'] / 2))], [(((self._DesignParameter['NAND']['_XYCoordinates'][0][0] + self._DesignParameter['NAND']['_DesignObj']._DesignParameter['pmos1']['_XYCoordinates'][0][0]) + self._DesignParameter['NAND']['_DesignObj']._DesignParameter['pmos1']['_DesignObj']._DesignParameter['_METAL1PINDrawing']['_XYCoordinates'][0][0]) - (drc._Metal1MinWidth / 2)), (((self._DesignParameter['NAND']['_XYCoordinates'][0][1] + self._DesignParameter['NAND']['_DesignObj']._DesignParameter['gate_b_input']['_XYCoordinates'][0][1]) + self._DesignParameter['NAND']['_DesignObj']._DesignParameter['gate_b_input']['_DesignObj']._DesignParameter['_Met1Layer']['_XYCoordinates'][0][1]) + (self._DesignParameter['NAND']['_DesignObj']._DesignParameter['gate_b_input']['_DesignObj']._DesignParameter['_Met1Layer']['_YWidth'] / 2))]]]
		self._DesignParameter['INb_m2_2'] = self._PathElementDeclaration(_Layer=DesignParameters._LayerMapping['METAL2'][0], _Datatype=DesignParameters._LayerMapping['METAL2'][1], _Width=drc._Metal1MinWidth)
		self._DesignParameter['INb_m2_2']['_XYCoordinates'] = [[[((self._DesignParameter['NAND']['_XYCoordinates'][0][0] + self._DesignParameter['NAND']['_DesignObj']._DesignParameter['pmos1']['_XYCoordinates'][0][0]) + self._DesignParameter['NAND']['_DesignObj']._DesignParameter['pmos1']['_DesignObj']._DesignParameter['_METAL1PINDrawing']['_XYCoordinates'][0][0]), self._DesignParameter['INb_m2_1']['_XYCoordinates'][0][0][1]], [((self._DesignParameter['NAND']['_XYCoordinates'][0][0] + self._DesignParameter['NAND']['_DesignObj']._DesignParameter['pmos1']['_XYCoordinates'][0][0]) + self._DesignParameter['NAND']['_DesignObj']._DesignParameter['pmos1']['_DesignObj']._DesignParameter['_METAL1PINDrawing']['_XYCoordinates'][0][0]), (((self._DesignParameter['NAND2TG_via1']['_XYCoordinates'][0][1] - drc.DRCVIAxMinSpace(2,1)/2 - drc._VIAxMinWidth/2 - (2 * drc._VIAxMinWidth)) - (4 * drc._Metal1MinEnclosureVia3)) - (2 * drc._MetalxMinSpace2))]]]
		self._DesignParameter['INb_m2_3'] = self._PathElementDeclaration(_Layer=DesignParameters._LayerMapping['METAL2'][0], _Datatype=DesignParameters._LayerMapping['METAL2'][1], _Width=((drc._Metal1MinEnclosureVia3 * 2) + drc._VIAxMinWidth))
		self._DesignParameter['INb_m2_3']['_XYCoordinates'] = [[[(self._DesignParameter['INb_m2_2']['_XYCoordinates'][0][0][0] + (drc._Metal1MinWidth / 2)), self._DesignParameter['INb_m2_2']['_XYCoordinates'][0][1][1]], [(self._DesignParameter['NAND']['_XYCoordinates'][0][0] + self._DesignParameter['NAND']['_DesignObj']._DesignParameter['gate_a_input']['_XYCoordinates'][0][0]), self._DesignParameter['INb_m2_2']['_XYCoordinates'][0][1][1]]]]
		self._DesignParameter['INb_m2_4'] = self._PathElementDeclaration(_Layer=DesignParameters._LayerMapping['METAL2'][0], _Datatype=DesignParameters._LayerMapping['METAL2'][1], _Width=(drc._VIAxMinWidth + (2 * drc._Metal1MinEnclosureVia3)))
		self._DesignParameter['INb_m2_4']['_XYCoordinates'] = [[[self._DesignParameter['INb_m2_3']['_XYCoordinates'][0][1][0], ((self._DesignParameter['INb_m2_3']['_XYCoordinates'][0][0][1] - (drc._VIAxMinWidth / 2)) - drc._Metal1MinEnclosureVia3)], [self._DesignParameter['INb_m2_3']['_XYCoordinates'][0][1][0], ((((self._DesignParameter['NAND']['_DesignObj']._DesignParameter['pmos2']['_XYCoordinates'][0][1] + self._DesignParameter['NAND']['_DesignObj']._DesignParameter['pmos2']['_DesignObj']._DesignParameter['_METAL1PINDrawing']['_XYCoordinates'][0][1] + self._DesignParameter['NAND']['_DesignObj']._DesignParameter['pmos2']['_DesignObj']._DesignParameter['_METAL1PINDrawing']['_YWidth']/2  - drc._VIAxMinWidth) - (2 * drc._Metal1MinEnclosureVia3)) - drc._MetalxMinSpace2))]]]

		if (MUX_module_num//2) % 2 == 0:
			self._DesignParameter['INb_via1_0'] = self._SrefElementDeclaration(_DesignObj=ViaMet12Met2._ViaMet12Met2(_Name='INb_via1_0In{}'.format(_Name)))[0]
			self._DesignParameter['INb_via1_0']['_DesignObj']._CalculateViaMet12Met2DesignParameterMinimumEnclosureX(**dict(_ViaMet12Met2NumberOfCOX=1, _ViaMet12Met2NumberOfCOY=2))
			self._DesignParameter['INb_via1_0']['_XYCoordinates'] = [[(self._DesignParameter['NAND']['_XYCoordinates'][0][0] + self._DesignParameter['NAND']['_DesignObj']._DesignParameter['gate_b_input']['_XYCoordinates'][0][0]), (self._DesignParameter['NAND']['_XYCoordinates'][0][1] + self._DesignParameter['NAND']['_DesignObj']._DesignParameter['gate_b_input']['_XYCoordinates'][0][1])]]
																	 #(((((self._DesignParameter['NAND2TG_via1']['_XYCoordinates'][0][1] - drc.DRCVIAxMinSpace(2,1)/2 - drc._VIAxMinWidth/2 + self._DesignParameter['NAND2TG_via1']['_DesignObj']._DesignParameter['_Met2Layer']['_XYCoordinates'][0][1]) - (self._DesignParameter['NAND2TG_via1']['_DesignObj']._DesignParameter['_Met2Layer']['_YWidth'] / 2)) - drc._MetalxMinSpace2) - drc._Metal1MinEnclosureVia3) - (drc._VIAxMinWidth / 2))]]
			self._DesignParameter['INb_m2_1']['_Width'] = ((((self._DesignParameter['INb_via1_0']['_XYCoordinates'][0][1] + self._DesignParameter['INb_via1_0']['_DesignObj']._DesignParameter['_Met2Layer']['_XYCoordinates'][0][1]) + (self._DesignParameter['INb_via1_0']['_DesignObj']._DesignParameter['_Met2Layer']['_YWidth'] / 2)) - (self._DesignParameter['INb_m2_1']['_XYCoordinates'][0][0][1])) * 2)


			self._DesignParameter['INb_via2_0'] = self._SrefElementDeclaration(_DesignObj=ViaMet22Met3._ViaMet22Met3(_Name='INb_via2_0In{}'.format(_Name)))[0]
			self._DesignParameter['INb_via2_0']['_DesignObj']._CalculateDesignParameterSameEnclosure(**dict(_ViaMet22Met3NumberOfCOX=2, _ViaMet22Met3NumberOfCOY=1))
			self._DesignParameter['INb_via2_0']['_XYCoordinates'] = [[(self._DesignParameter['NAND']['_XYCoordinates'][0][0] + self._DesignParameter['NAND']['_DesignObj']._DesignParameter['gate_a_input']['_XYCoordinates'][0][0] - drc.DRCVIAxMinSpace(2,1)/2 - drc._VIAxMinWidth/2), (((self._DesignParameter['INb_m2_4']['_XYCoordinates'][0][1][1])))]]

			self._DesignParameter['INb_via3_0'] = self._SrefElementDeclaration(_DesignObj=ViaMet32Met4._ViaMet32Met4(_Name='INb_via3_0In{}'.format(_Name)))[0]
			self._DesignParameter['INb_via3_0']['_DesignObj']._CalculateDesignParameterSameEnclosure(**dict(_ViaMet32Met4NumberOfCOX=2, _ViaMet32Met4NumberOfCOY=1))
			self._DesignParameter['INb_via3_0']['_XYCoordinates'] = [[(self._DesignParameter['NAND']['_XYCoordinates'][0][0] + self._DesignParameter['NAND']['_DesignObj']._DesignParameter['gate_a_input']['_XYCoordinates'][0][0] - drc.DRCVIAxMinSpace(2,1)/2 - drc._VIAxMinWidth/2), (((self._DesignParameter['INb_m2_4']['_XYCoordinates'][0][1][1])))]]


		else:
			self._DesignParameter['INb_via1_1'] = self._SrefElementDeclaration(_DesignObj=ViaMet12Met2._ViaMet12Met2(_Name='INb_via1_1In{}'.format(_Name)))[0]
			self._DesignParameter['INb_via1_1']['_DesignObj']._CalculateViaMet12Met2DesignParameterMinimumEnclosureX(**dict(_ViaMet12Met2NumberOfCOX=1, _ViaMet12Met2NumberOfCOY=2))
			self._DesignParameter['INb_via1_1']['_XYCoordinates'] = [[(self._DesignParameter['NAND']['_XYCoordinates'][0][0] + self._DesignParameter['NAND']['_DesignObj']._DesignParameter['gate_b_input']['_XYCoordinates'][0][0]), (self._DesignParameter['NAND']['_XYCoordinates'][0][1] + self._DesignParameter['NAND']['_DesignObj']._DesignParameter['gate_b_input']['_XYCoordinates'][0][1])]]

			self._DesignParameter['INb_m2_1']['_Width'] = ((((self._DesignParameter['INb_via1_1']['_XYCoordinates'][0][1] + self._DesignParameter['INb_via1_1']['_DesignObj']._DesignParameter['_Met2Layer']['_XYCoordinates'][0][1]) + (self._DesignParameter['INb_via1_1']['_DesignObj']._DesignParameter['_Met2Layer']['_YWidth'] / 2)) - (self._DesignParameter['INb_m2_1']['_XYCoordinates'][0][0][1])) * 2)


			self._DesignParameter['INb_via2_1'] = self._SrefElementDeclaration(_DesignObj=ViaMet22Met3._ViaMet22Met3(_Name='INb_via_21In{}'.format(_Name)))[0]
			self._DesignParameter['INb_via2_1']['_DesignObj']._CalculateDesignParameterSameEnclosure(**dict(_ViaMet22Met3NumberOfCOX=2, _ViaMet22Met3NumberOfCOY=1))
			self._DesignParameter['INb_via2_1']['_XYCoordinates'] = [[(self._DesignParameter['NAND']['_XYCoordinates'][0][0] + self._DesignParameter['NAND']['_DesignObj']._DesignParameter['gate_a_input']['_XYCoordinates'][0][0] - drc.DRCVIAxMinSpace(2,1)/2 - drc._VIAxMinWidth/2), (((self._DesignParameter['INb_m2_4']['_XYCoordinates'][0][1][1] - drc._VIAxMinWidth) - (2 * drc._Metal1MinEnclosureVia3)) - drc._MetalxMinSpace2)]]

			self._DesignParameter['INb_via3_1'] = self._SrefElementDeclaration(_DesignObj=ViaMet32Met4._ViaMet32Met4(_Name='INb_via3_1In{}'.format(_Name)))[0]
			self._DesignParameter['INb_via3_1']['_DesignObj']._CalculateDesignParameterSameEnclosure(**dict(_ViaMet32Met4NumberOfCOX=2, _ViaMet32Met4NumberOfCOY=1))
			self._DesignParameter['INb_via3_1']['_XYCoordinates'] = [[(self._DesignParameter['NAND']['_XYCoordinates'][0][0] + self._DesignParameter['NAND']['_DesignObj']._DesignParameter['gate_a_input']['_XYCoordinates'][0][0] - drc.DRCVIAxMinSpace(2,1)/2 - drc._VIAxMinWidth/2), (((self._DesignParameter['INb_m2_4']['_XYCoordinates'][0][1][1] - drc._VIAxMinWidth) - (2 * drc._Metal1MinEnclosureVia3)) - drc._MetalxMinSpace2)]]

		self._DesignParameter['INVa_m1'] = self._PathElementDeclaration(_Layer=DesignParameters._LayerMapping['METAL1'][0], _Datatype=DesignParameters._LayerMapping['METAL1'][1], _Width=(drc._VIAxMinWidth + (2 * drc._Metal1MinEnclosureVia3)))
		self._DesignParameter['INVa_m1']['_XYCoordinates'] = [[[self._DesignParameter['INb_m2_3']['_XYCoordinates'][0][1][0], (((self._DesignParameter['INb_m2_3']['_XYCoordinates'][0][0][1] - (drc._Metal1MinEnclosureVia3 * 2)) - drc._VIAxMinWidth) - drc._MetalxMinSpace2)], [self._DesignParameter['INb_m2_3']['_XYCoordinates'][0][1][0], (((self._DesignParameter['NAND']['_XYCoordinates'][0][1] + self._DesignParameter['NAND']['_DesignObj']._DesignParameter['gate_a_input']['_XYCoordinates'][0][1]) + self._DesignParameter['NAND']['_DesignObj']._DesignParameter['gate_a_input']['_DesignObj']._DesignParameter['_Met1Layer']['_XYCoordinates'][0][1]) - (self._DesignParameter['NAND']['_DesignObj']._DesignParameter['gate_a_input']['_DesignObj']._DesignParameter['_Met1Layer']['_YWidth'] / 2))]]]

		if MUX_module_num//4 == 0:
			self._DesignParameter['INa_via1_0'] = self._SrefElementDeclaration(_DesignObj=ViaMet12Met2._ViaMet12Met2(_Name='INa_via1_0In{}'.format(_Name)))[0]
			self._DesignParameter['INa_via1_0']['_DesignObj']._CalculateDesignParameterSameEnclosure(**dict(_ViaMet12Met2NumberOfCOX=2, _ViaMet12Met2NumberOfCOY=1))
			self._DesignParameter['INa_via1_0']['_XYCoordinates'] = [[self._DesignParameter['INVa_m1']['_XYCoordinates'][0][0][0] - drc.DRCVIAxMinSpace(2,1)/2 - drc._VIAxMinWidth/2, self._DesignParameter['INVa_m1']['_XYCoordinates'][0][0][1]]]

			self._DesignParameter['INa_via2_0'] = self._SrefElementDeclaration(_DesignObj=ViaMet22Met3._ViaMet22Met3(_Name='INa_via2_0In{}'.format(_Name)))[0]
			self._DesignParameter['INa_via2_0']['_DesignObj']._CalculateDesignParameterSameEnclosure(**dict(_ViaMet22Met3NumberOfCOX=2, _ViaMet22Met3NumberOfCOY=1))
			self._DesignParameter['INa_via2_0']['_XYCoordinates'] = [[self._DesignParameter['INVa_m1']['_XYCoordinates'][0][0][0] - drc.DRCVIAxMinSpace(2,1)/2 - drc._VIAxMinWidth/2, self._DesignParameter['INVa_m1']['_XYCoordinates'][0][0][1]]]

			self._DesignParameter['INa_via3_0'] = self._SrefElementDeclaration(_DesignObj=ViaMet32Met4._ViaMet32Met4(_Name='INa_via3_0In{}'.format(_Name)))[0]
			self._DesignParameter['INa_via3_0']['_DesignObj']._CalculateDesignParameterSameEnclosure(**dict(_ViaMet32Met4NumberOfCOX=2, _ViaMet32Met4NumberOfCOY=1))
			self._DesignParameter['INa_via3_0']['_XYCoordinates'] = [[self._DesignParameter['INVa_m1']['_XYCoordinates'][0][0][0] - drc.DRCVIAxMinSpace(2,1)/2 - drc._VIAxMinWidth/2, self._DesignParameter['INVa_m1']['_XYCoordinates'][0][0][1]]]

		else:
			self._DesignParameter['INa_via1_1'] = self._SrefElementDeclaration(_DesignObj=ViaMet12Met2._ViaMet12Met2(_Name='INa_via1_1In{}'.format(_Name)))[0]
			self._DesignParameter['INa_via1_1']['_DesignObj']._CalculateDesignParameterSameEnclosure(**dict(_ViaMet12Met2NumberOfCOX=2, _ViaMet12Met2NumberOfCOY=1))
			self._DesignParameter['INa_via1_1']['_XYCoordinates'] = [[self._DesignParameter['INVa_m1']['_XYCoordinates'][0][0][0] - drc.DRCVIAxMinSpace(2,1)/2 - drc._VIAxMinWidth/2, (((self._DesignParameter['INVa_m1']['_XYCoordinates'][0][0][1] - drc._VIAxMinWidth) - (2 * drc._Metal1MinEnclosureVia3)) - drc._MetalxMinSpace2)]]

			self._DesignParameter['INa_via2_1'] = self._SrefElementDeclaration(_DesignObj=ViaMet22Met3._ViaMet22Met3(_Name='INa_via2_1In{}'.format(_Name)))[0]
			self._DesignParameter['INa_via2_1']['_DesignObj']._CalculateDesignParameterSameEnclosure(**dict(_ViaMet22Met3NumberOfCOX=2, _ViaMet22Met3NumberOfCOY=1))
			self._DesignParameter['INa_via2_1']['_XYCoordinates'] = [[self._DesignParameter['INVa_m1']['_XYCoordinates'][0][0][0] - drc.DRCVIAxMinSpace(2,1)/2 - drc._VIAxMinWidth/2, (((self._DesignParameter['INVa_m1']['_XYCoordinates'][0][0][1] - drc._VIAxMinWidth) - (2 * drc._Metal1MinEnclosureVia3)) - drc._MetalxMinSpace2)]]

			self._DesignParameter['INa_via3_1'] = self._SrefElementDeclaration(_DesignObj=ViaMet32Met4._ViaMet32Met4(_Name='INa_via3_1In{}'.format(_Name)))[0]
			self._DesignParameter['INa_via3_1']['_DesignObj']._CalculateDesignParameterSameEnclosure(**dict(_ViaMet32Met4NumberOfCOX=2, _ViaMet32Met4NumberOfCOY=1))
			self._DesignParameter['INa_via3_1']['_XYCoordinates'] = [[self._DesignParameter['INVa_m1']['_XYCoordinates'][0][0][0] - drc.DRCVIAxMinSpace(2,1)/2 - drc._VIAxMinWidth/2, (((self._DesignParameter['INVa_m1']['_XYCoordinates'][0][0][1] - drc._VIAxMinWidth) - (2 * drc._Metal1MinEnclosureVia3)) - drc._MetalxMinSpace2)]]

		self._DesignParameter['INc_m1'] = self._PathElementDeclaration(_Layer=DesignParameters._LayerMapping['METAL2'][0], _Datatype=DesignParameters._LayerMapping['METAL2'][1], _Width=((2 * drc._Metal1MinEnclosureVia3) + drc._VIAxMinWidth))
		self._DesignParameter['INc_m1']['_XYCoordinates'] = [[[(self._DesignParameter['NAND']['_XYCoordinates'][0][0] + self._DesignParameter['NAND']['_DesignObj']._DesignParameter['gate_c_input']['_XYCoordinates'][0][0]), ((((((self._DesignParameter['INVa_m1']['_XYCoordinates'][0][0][1] - drc._VIAxMinWidth) - (2 * drc._Metal1MinEnclosureVia3)) - drc._MetalxMinSpace2) - (drc._VIAxMinWidth * 2)) - (4 * drc._Metal1MinEnclosureVia3)) - (2 * drc._MetalxMinSpace2))], [(self._DesignParameter['NAND']['_XYCoordinates'][0][0] + self._DesignParameter['NAND']['_DesignObj']._DesignParameter['gate_c_input']['_XYCoordinates'][0][0]), (((self._DesignParameter['NAND']['_XYCoordinates'][0][1] + self._DesignParameter['NAND']['_DesignObj']._DesignParameter['gate_c_input']['_XYCoordinates'][0][1]) + self._DesignParameter['NAND']['_DesignObj']._DesignParameter['gate_c_input']['_DesignObj']._DesignParameter['_Met1Layer']['_XYCoordinates'][0][1]) + (self._DesignParameter['NAND']['_DesignObj']._DesignParameter['gate_c_input']['_DesignObj']._DesignParameter['_Met1Layer']['_YWidth'] / 2))]]]

		if MUX_module_num % 2 == 0:
			self._DesignParameter['INc_via1_0'] = self._SrefElementDeclaration(_DesignObj=ViaMet12Met2._ViaMet12Met2(_Name='INc_via1_0In{}'.format(_Name)))[0]
			self._DesignParameter['INc_via1_0']['_DesignObj']._CalculateDesignParameterSameEnclosure(**dict(_ViaMet12Met2NumberOfCOX=1, _ViaMet12Met2NumberOfCOY=2))
			self._DesignParameter['INc_via1_0']['_XYCoordinates'] = [[(self._DesignParameter['NAND']['_XYCoordinates'][0][0] + self._DesignParameter['NAND']['_DesignObj']._DesignParameter['gate_c_input']['_XYCoordinates'][0][0]), (self._DesignParameter['NAND']['_XYCoordinates'][0][1] + self._DesignParameter['NAND']['_DesignObj']._DesignParameter['gate_c_input']['_XYCoordinates'][0][1])]]

			self._DesignParameter['INc_via2_0'] = self._SrefElementDeclaration(_DesignObj=ViaMet22Met3._ViaMet22Met3(_Name='INc_via2_0In{}'.format(_Name)))[0]
			self._DesignParameter['INc_via2_0']['_DesignObj']._CalculateDesignParameterSameEnclosure(**dict(_ViaMet22Met3NumberOfCOX=2, _ViaMet22Met3NumberOfCOY=1))
			self._DesignParameter['INc_via2_0']['_XYCoordinates'] = [[self._DesignParameter['INc_m1']['_XYCoordinates'][0][0][0] + drc.DRCVIAxMinSpace(2,1)/2 + drc._VIAxMinWidth/2, (((self._DesignParameter['INc_m1']['_XYCoordinates'][0][0][1] + drc._VIAxMinWidth) + (2 * drc._Metal1MinEnclosureVia3)) + drc._MetalxMinSpace2)]]

			self._DesignParameter['INc_via3_0'] = self._SrefElementDeclaration(_DesignObj=ViaMet32Met4._ViaMet32Met4(_Name='INc_via3_0In{}'.format(_Name)))[0]
			self._DesignParameter['INc_via3_0']['_DesignObj']._CalculateDesignParameterSameEnclosure(**dict(_ViaMet32Met4NumberOfCOX=2, _ViaMet32Met4NumberOfCOY=1))
			self._DesignParameter['INc_via3_0']['_XYCoordinates'] = [[self._DesignParameter['INc_m1']['_XYCoordinates'][0][0][0] + drc.DRCVIAxMinSpace(2,1)/2 + drc._VIAxMinWidth/2, (((self._DesignParameter['INc_m1']['_XYCoordinates'][0][0][1] + drc._VIAxMinWidth) + (2 * drc._Metal1MinEnclosureVia3)) + drc._MetalxMinSpace2)]]

		else:
			self._DesignParameter['INc_via1_1'] = self._SrefElementDeclaration(_DesignObj=ViaMet12Met2._ViaMet12Met2(_Name='INc_via1_1In{}'.format(_Name)))[0]
			self._DesignParameter['INc_via1_1']['_DesignObj']._CalculateDesignParameterSameEnclosure(**dict(_ViaMet12Met2NumberOfCOX=1, _ViaMet12Met2NumberOfCOY=2))
			self._DesignParameter['INc_via1_1']['_XYCoordinates'] = [[(self._DesignParameter['NAND']['_XYCoordinates'][0][0] + self._DesignParameter['NAND']['_DesignObj']._DesignParameter['gate_c_input']['_XYCoordinates'][0][0]), (self._DesignParameter['NAND']['_XYCoordinates'][0][1] + self._DesignParameter['NAND']['_DesignObj']._DesignParameter['gate_c_input']['_XYCoordinates'][0][1])]]

			self._DesignParameter['INc_via2_1'] = self._SrefElementDeclaration(_DesignObj=ViaMet22Met3._ViaMet22Met3(_Name='INc_via2_1In{}'.format(_Name)))[0]
			self._DesignParameter['INc_via2_1']['_DesignObj']._CalculateDesignParameterSameEnclosure(**dict(_ViaMet22Met3NumberOfCOX=2, _ViaMet22Met3NumberOfCOY=1))
			self._DesignParameter['INc_via2_1']['_XYCoordinates'] = [[(+ self._DesignParameter['INc_m1']['_XYCoordinates'][0][0][0] + drc.DRCVIAxMinSpace(2,1)/2 + drc._VIAxMinWidth/2), (+ self._DesignParameter['INc_m1']['_XYCoordinates'][0][0][1])]]

			self._DesignParameter['INc_via3_1'] = self._SrefElementDeclaration(_DesignObj=ViaMet32Met4._ViaMet32Met4(_Name='INc_via3_1In{}'.format(_Name)))[0]
			self._DesignParameter['INc_via3_1']['_DesignObj']._CalculateDesignParameterSameEnclosure(**dict(_ViaMet32Met4NumberOfCOX=2, _ViaMet32Met4NumberOfCOY=1))
			self._DesignParameter['INc_via3_1']['_XYCoordinates'] = [[(+ self._DesignParameter['INc_m1']['_XYCoordinates'][0][0][0] + drc.DRCVIAxMinSpace(2,1)/2 + drc._VIAxMinWidth/2), (+ self._DesignParameter['INc_m1']['_XYCoordinates'][0][0][1])]]

		self._DesignParameter['OUTvia1'] = self._SrefElementDeclaration(_DesignObj=ViaMet12Met2._ViaMet12Met2(_Name='OUTvia1In{}'.format(_Name)))[0]
		self._DesignParameter['OUTvia1']['_DesignObj']._CalculateViaMet12Met2DesignParameterMinimumEnclosureX(**dict(_ViaMet12Met2NumberOfCOX=1, _ViaMet12Met2NumberOfCOY=max(2, int(self._DesignParameter['TR_GATE']['_DesignObj']._DesignParameter['nmos']['_DesignObj']._DesignParameter['_Met1Layer']['_YWidth'] / (drc._VIAxMinWidth + drc._VIAxMinSpace)))))
		self._DesignParameter['OUTvia1']['_XYCoordinates'] = [[(+ ((self._DesignParameter['TR_GATE']['_XYCoordinates'][0][0] + self._DesignParameter['TR_GATE']['_DesignObj']._DesignParameter['nmos']['_XYCoordinates'][0][0]) - self._DesignParameter['TR_GATE']['_DesignObj']._DesignParameter['output_nm']['_XYCoordinates'][-1][0])), (+ ((self._DesignParameter['TR_GATE']['_XYCoordinates'][0][1] + self._DesignParameter['TR_GATE']['_DesignObj']._DesignParameter['output_nm']['_XYCoordinates'][0][1])))]]
		self._DesignParameter['OUTvia2'] = self._SrefElementDeclaration(_DesignObj=ViaMet22Met3._ViaMet22Met3(_Name='OUTvia2In{}'.format(_Name)))[0]
		self._DesignParameter['OUTvia2']['_DesignObj']._CalculateViaMet22Met3DesignParameterMinimumEnclosureX(**dict(_ViaMet22Met3NumberOfCOX=1, _ViaMet22Met3NumberOfCOY=2))
		self._DesignParameter['OUTvia2']['_XYCoordinates'] = [[(+ ((self._DesignParameter['TR_GATE']['_XYCoordinates'][0][0] + self._DesignParameter['TR_GATE']['_DesignObj']._DesignParameter['nmos']['_XYCoordinates'][0][0]) - self._DesignParameter['TR_GATE']['_DesignObj']._DesignParameter['output_nm']['_XYCoordinates'][-1][0])), (+ ((self._DesignParameter['TR_GATE']['_XYCoordinates'][0][1] + self._DesignParameter['TR_GATE']['_DesignObj']._DesignParameter['output_nm']['_XYCoordinates'][0][1])))]]
		self._DesignParameter['OUTvia3'] = self._SrefElementDeclaration(_DesignObj=ViaMet32Met4._ViaMet32Met4(_Name='OUTvia3In{}'.format(_Name)))[0]
		self._DesignParameter['OUTvia3']['_DesignObj']._CalculateDesignParameterSameEnclosure(**dict(_ViaMet32Met4NumberOfCOX=1, _ViaMet32Met4NumberOfCOY=2))
		self._DesignParameter['OUTvia3']['_XYCoordinates'] = [[(+ ((self._DesignParameter['TR_GATE']['_XYCoordinates'][0][0] + self._DesignParameter['TR_GATE']['_DesignObj']._DesignParameter['nmos']['_XYCoordinates'][0][0]) - self._DesignParameter['TR_GATE']['_DesignObj']._DesignParameter['output_nm']['_XYCoordinates'][-1][0])), (+ ((self._DesignParameter['TR_GATE']['_XYCoordinates'][0][1] + self._DesignParameter['TR_GATE']['_DesignObj']._DesignParameter['output_nm']['_XYCoordinates'][0][1])))]]

		self._DesignParameter['OUTvia_m3_boundary'] = self._BoundaryElementDeclaration(_Layer=DesignParameters._LayerMapping['METAL3'][0], _Datatype=DesignParameters._LayerMapping['METAL3'][1], _XWidth=self._DesignParameter['OUTvia3']['_DesignObj']._DesignParameter['_Met3Layer']['_XWidth'], _YWidth=self._DesignParameter['OUTvia2']['_DesignObj']._DesignParameter['_Met3Layer']['_YWidth'])
		self._DesignParameter['OUTvia_m3_boundary']['_XYCoordinates'] = [self._DesignParameter['OUTvia2']['_XYCoordinates'][0]]

		self._DesignParameter['Vref_in_via1'] = self._SrefElementDeclaration(_DesignObj=ViaMet12Met2._ViaMet12Met2(_Name='Vref_in_via1In{}'.format(_Name)))[0]
		self._DesignParameter['Vref_in_via1']['_DesignObj']._CalculateDesignParameterSameEnclosure(**dict(_ViaMet12Met2NumberOfCOX=1, _ViaMet12Met2NumberOfCOY=2))
		self._DesignParameter['Vref_in_via1']['_XYCoordinates'] = [[((self._DesignParameter['TR_GATE']['_XYCoordinates'][0][0] + self._DesignParameter['TR_GATE']['_DesignObj']._DesignParameter['pmos']['_XYCoordinates'][0][0]) - self._DesignParameter['TR_GATE']['_DesignObj']._DesignParameter['output_pm']['_XYCoordinates'][-1][0]), TG_poly_y]]
																   #(((self._DesignParameter['nand2tg_via']['_XYCoordinates'][0][1] - drc.DRCVIAxMinSpace(2,1)/2 - drc._VIAxMinWidth/2 + drc._VIAxMinWidth) + (2 * drc._Metal1MinEnclosureVia3)) + drc._MetalxMinSpace2)]]
		self._DesignParameter['Vref_in_via2'] = self._SrefElementDeclaration(_DesignObj=ViaMet22Met3._ViaMet22Met3(_Name='Vref_in_via2In{}'.format(_Name)))[0]
		self._DesignParameter['Vref_in_via2']['_DesignObj']._CalculateDesignParameterSameEnclosure(**dict(_ViaMet22Met3NumberOfCOX=1, _ViaMet22Met3NumberOfCOY=2))
		self._DesignParameter['Vref_in_via2']['_XYCoordinates'] = [[((self._DesignParameter['TR_GATE']['_XYCoordinates'][0][0] + self._DesignParameter['TR_GATE']['_DesignObj']._DesignParameter['pmos']['_XYCoordinates'][0][0]) - self._DesignParameter['TR_GATE']['_DesignObj']._DesignParameter['output_pm']['_XYCoordinates'][-1][0]), TG_poly_y]]
		self._DesignParameter['Vref_in_m3'] = self._PathElementDeclaration(_Layer=DesignParameters._LayerMapping['METAL3'][0], _Datatype=DesignParameters._LayerMapping['METAL3'][1], _Width=self._DesignParameter['Vref_in_via2']['_DesignObj']._DesignParameter['_Met3Layer']['_XWidth'])
		self._DesignParameter['Vref_in_m3']['_XYCoordinates'] = [[[(self._DesignParameter['Vref_in_via2']['_XYCoordinates'][0][0]), ((((self._DesignParameter['TR_GATE']['_XYCoordinates'][0][1]) + self._DesignParameter['TR_GATE']['_DesignObj']._DesignParameter['pmos']['_XYCoordinates'][0][1]) + self._DesignParameter['TR_GATE']['_DesignObj']._DesignParameter['pmos']['_DesignObj']._DesignParameter['_METAL1PINDrawing']['_XYCoordinates'][0][1]) + (self._DesignParameter['TR_GATE']['_DesignObj']._DesignParameter['pmos']['_DesignObj']._DesignParameter['_METAL1PINDrawing']['_YWidth'] / 2))],
																  [(self._DesignParameter['Vref_in_via2']['_XYCoordinates'][0][0]), self._DesignParameter['Vref_in_via2']['_XYCoordinates'][0][1]]]]
		self._DesignParameter['Vref_in_m3_2'] = self._PathElementDeclaration(_Layer=DesignParameters._LayerMapping['METAL3'][0], _Datatype=DesignParameters._LayerMapping['METAL3'][1], _Width=self._DesignParameter['Vref_in_via2']['_DesignObj']._DesignParameter['_Met3Layer']['_XWidth'])
		self._DesignParameter['Vref_in_m3_2']['_XYCoordinates'] = [[[(self._DesignParameter['TR_GATE']['_XYCoordinates'][0][0] + self._DesignParameter['TR_GATE']['_DesignObj']._DesignParameter['gate_input']['_XYCoordinates'][0][0] - Input_offset * (self._DesignParameter['Vref_in_via2']['_DesignObj']._DesignParameter['_Met3Layer']['_XWidth'] + drc._MetalxMinSpace2)), (self._DesignParameter['Vref_in_m3']['_XYCoordinates'][0][0][1] - self._DesignParameter['Vref_in_via2']['_DesignObj']._DesignParameter['_Met3Layer']['_XWidth']/2)],
																  [(self._DesignParameter['Vref_in_m3']['_XYCoordinates'][0][0][0]), (self._DesignParameter['Vref_in_m3']['_XYCoordinates'][0][0][1] - self._DesignParameter['Vref_in_via2']['_DesignObj']._DesignParameter['_Met3Layer']['_XWidth']/2)]]]
		self._DesignParameter['m3_boundary'] = self._BoundaryElementDeclaration(_Layer=DesignParameters._LayerMapping['METAL3'][0], _Datatype=DesignParameters._LayerMapping['METAL3'][1], _XWidth=self._DesignParameter['Vref_in_via2']['_DesignObj']._DesignParameter['_Met3Layer']['_XWidth'], _YWidth=self._DesignParameter['Vref_in_via2']['_DesignObj']._DesignParameter['_Met3Layer']['_XWidth'])
		self._DesignParameter['m3_boundary']['_XYCoordinates'] = [self._DesignParameter['Vref_in_m3_2']['_XYCoordinates'][0][0]]


#		self._DesignParameter['Vref+in_m2'] = self._PathElementDeclaration(_Layer=DesignParameters._LayerMapping['METAL2'][0], _Datatype=DesignParameters._LayerMapping['METAL2'][1], _Width=self._DesignParameter['Vref_in_via']['_DesignObj']._DesignParameter['_Met2Layer']['_YWidth'])
#		self._DesignParameter['Vref+in_m2']['_XYCoordinates'] = [[[(+ (self._DesignParameter['Vref_in_via']['_XYCoordinates'][0][0] + self._DesignParameter['Vref_in_via']['_DesignObj']._DesignParameter['_Met2Layer']['_XYCoordinates'][0][0])), (+ (self._DesignParameter['Vref_in_via']['_XYCoordinates'][0][1] + self._DesignParameter['Vref_in_via']['_DesignObj']._DesignParameter['_Met2Layer']['_XYCoordinates'][0][1]))], [(self._DesignParameter['TR_GATE']['_XYCoordinates'][0][0] + self._DesignParameter['TR_GATE']['_DesignObj']._DesignParameter['gate_input']['_XYCoordinates'][0][0]), self._DesignParameter['Vref_in_via']['_XYCoordinates'][0][1]]]]
		