from generatorLib import StickDiagram
from generatorLib import DesignParameters
import copy
import math
from generatorLib import DRC
from generatorLib.generator_models.rx_project import StrongArmLatch
from generatorLib.generator_models.rx_project import ViaMet42Met5
from generatorLib.generator_models.rx_project import Inverter
from generatorLib.generator_models.rx_project import ViaStack
from generatorLib.generator_models.rx_project import ViaMet12Met2
from generatorLib.generator_models.rx_project import ViaMet52Met6
from generatorLib.generator_models.rx_project import SRLatch

class SlicerWithSRLatchInSlicerWithSRLatchX4_3(StickDiagram._StickDiagram):
	def __init__(self, _DesignParameter=None, _Name='SlicerWithSRLatchInSlicerWithSRLatchX4_3'):
		if _DesignParameter != None:
			self._DesignParameter = _DesignParameter
		else:
			self._DesignParameter = dict(_Name=self._NameDeclaration(_Name=_Name), _GDSFile=self._GDSObjDeclaration(_GDSFile=None))
		self._DesignParameter['_Name']['Name'] = _Name

	def _CalculateDesignParameter(self,StrongArm_parms={'subring_option': {'via_num': 2, 'nmos_subring_addi_width': 100, 'additional_np_distance': 0, 'additional_outer_height': 0}, 'pmos_outer_gate': 3, 'pmos_inner_gate': 3, 'nmos_parms': {'common_width': 1000, 'nmos_bot_gate': 20, 'nmos_inner_gate': 1, 'nmos_outer_gate': 8, 'bot_width': 300, 'nmos_inner_width': 1000}, 'pmos_parms': {'common_width': 500, 'inner_gate': 2}},SRLatch_parms={'supply_coy': 2, 'gate_1': 2, 'gate_2': 1, 'gate_3': 1, 'gate_4': 1, 'supply_height': 1708, 'pmos_parms': {'width_1': 400, 'width_2': 400, 'width_3': 400, 'width_4': 400}, 'nmos_parms': {'width_1': 200, 'width_2': 200, 'width_3': 200, 'width_4': 200}},INV_parms={'gate': 15, 'nmos_width': 200, 'length': 30, 'supply_coy': 2, 'pmos_width': 600}):
	
		drc = DRC.DRC()
		_Name = self._DesignParameter['_Name']['_Name']
		
		self._DesignParameter['SlicerInSlicerWithSRLatch_0'] = self._SrefElementDeclaration(_DesignObj=StrongArmLatch.SlicerInSlicerWithSRLatch_0(_Name='SlicerInSlicerWithSRLatch_0In{}'.format(_Name)))[0]
		self._DesignParameter['SlicerInSlicerWithSRLatch_0']['_DesignObj']._CalculateDesignParameter(**dict(**StrongArm_parms))
		self._DesignParameter['SlicerInSlicerWithSRLatch_0']['_XYCoordinates'] = [[0, 0]]
		self._DesignParameter['InverterInSlicerWithSRLatch_0'] = self._SrefElementDeclaration(_DesignObj=Inverter.InverterInSlicerWithSRLatch_0(_Name='InverterInSlicerWithSRLatch_0In{}'.format(_Name)))[0]
		self._DesignParameter['InverterInSlicerWithSRLatch_0']['_DesignObj']._CalculateDesignParameter(**dict(**INV_parms))
		self._DesignParameter['InverterInSlicerWithSRLatch_0']['_XYCoordinates'] = [[(+ self._DesignParameter['SlicerInSlicerWithSRLatch_0']['_XYCoordinates'][0][0]), (+ self._DesignParameter['SlicerInSlicerWithSRLatch_0']['_XYCoordinates'][0][1])]]
		self._DesignParameter['SRLatchInSlicerWithSRLatch_0'] = self._SrefElementDeclaration(_DesignObj=SRLatch.SRLatchInSlicerWithSRLatch_0(_Name='SRLatchInSlicerWithSRLatch_0In{}'.format(_Name)))[0]
		self._DesignParameter['SRLatchInSlicerWithSRLatch_0']['_DesignObj']._CalculateDesignParameter(**dict(**SRLatch_parms))
		self._DesignParameter['SRLatchInSlicerWithSRLatch_0']['_XYCoordinates'] = [[(round((((((((((self._DesignParameter['SlicerInSlicerWithSRLatch_0']['_XYCoordinates'][0][0] + self._DesignParameter['SlicerInSlicerWithSRLatch_0']['_DesignObj']._DesignParameter['GuardringInSlicer_0']['_XYCoordinates'][0][0]) + self._DesignParameter['SlicerInSlicerWithSRLatch_0']['_DesignObj']._DesignParameter['GuardringInSlicer_0']['_DesignObj']._DesignParameter['right']['_XYCoordinates'][0][0]) + self._DesignParameter['SlicerInSlicerWithSRLatch_0']['_DesignObj']._DesignParameter['GuardringInSlicer_0']['_DesignObj']._DesignParameter['right']['_DesignObj']._DesignParameter['_PPLayer']['_XYCoordinates'][0][0]) + (self._DesignParameter['SlicerInSlicerWithSRLatch_0']['_DesignObj']._DesignParameter['GuardringInSlicer_0']['_DesignObj']._DesignParameter['right']['_DesignObj']._DesignParameter['_PPLayer']['_XWidth'] / 2)) + drc._PpMinSpace) + (max(self._DesignParameter['InverterInSlicerWithSRLatch_0']['_DesignObj']._DesignParameter['PMOSInInverter_0']['_DesignObj']._DesignParameter['_PPLayer']['_XWidth'], self._DesignParameter['SRLatchInSlicerWithSRLatch_0']['_DesignObj']._DesignParameter['PbodyContactInSRLatch_0']['_DesignObj']._DesignParameter['_PPLayer']['_XWidth'], self._DesignParameter['InverterInSlicerWithSRLatch_0']['_DesignObj']._DesignParameter['PbodyContactInInverter_0']['_DesignObj']._DesignParameter['_PPLayer']['_XWidth']) / 2)) - self._DesignParameter['SRLatchInSlicerWithSRLatch_0']['_DesignObj']._DesignParameter['NbodyContactInSRLatch_0']['_XYCoordinates'][0][0]) + drc._MinSnapSpacing) / (2 * drc._MinSnapSpacing))) * (drc._MinSnapSpacing * 2)), (((((self._DesignParameter['SlicerInSlicerWithSRLatch_0']['_XYCoordinates'][0][1] + self._DesignParameter['SlicerInSlicerWithSRLatch_0']['_DesignObj']._DesignParameter['GuardringInNMOSSetofSlicer_0']['_XYCoordinates'][0][1]) + self._DesignParameter['SlicerInSlicerWithSRLatch_0']['_DesignObj']._DesignParameter['GuardringInNMOSSetofSlicer_0']['_DesignObj']._DesignParameter['top']['_XYCoordinates'][0][1]) + ((self._DesignParameter['SlicerInSlicerWithSRLatch_0']['_XYCoordinates'][0][1] + self._DesignParameter['SlicerInSlicerWithSRLatch_0']['_DesignObj']._DesignParameter['GuardringInPMOSSetofSlicer_0']['_XYCoordinates'][0][1]) + self._DesignParameter['SlicerInSlicerWithSRLatch_0']['_DesignObj']._DesignParameter['GuardringInPMOSSetofSlicer_0']['_DesignObj']._DesignParameter['bot']['_XYCoordinates'][0][1])) / 2) + (- self._DesignParameter['SRLatchInSlicerWithSRLatch_0']['_DesignObj']._DesignParameter['PbodyContactInSRLatch_0']['_XYCoordinates'][0][1]))]]
		self._DesignParameter['InverterInSlicerWithSRLatch_0']['_DesignObj']._CalculateDesignParameter(**dict(**INV_parms))
		self._DesignParameter['InverterInSlicerWithSRLatch_0']['_XYCoordinates'] = [[(self._DesignParameter['SRLatchInSlicerWithSRLatch_0']['_XYCoordinates'][0][0] + self._DesignParameter['SRLatchInSlicerWithSRLatch_0']['_DesignObj']._DesignParameter['NbodyContactInSRLatch_0']['_XYCoordinates'][0][0]), ((self._DesignParameter['SRLatchInSlicerWithSRLatch_0']['_XYCoordinates'][0][1] + self._DesignParameter['SRLatchInSlicerWithSRLatch_0']['_DesignObj']._DesignParameter['NbodyContactInSRLatch_0']['_XYCoordinates'][0][1]) + (- self._DesignParameter['InverterInSlicerWithSRLatch_0']['_DesignObj']._DesignParameter['NbodyContactInInverter_0']['_XYCoordinates'][0][1]))]]
		self._DesignParameter['METAL3_path_38'] = self._PathElementDeclaration(_Layer=DesignParameters._LayerMapping['METAL3'][0], _Datatype=DesignParameters._LayerMapping['METAL3'][1], _Width=self._DesignParameter['SlicerInSlicerWithSRLatch_0']['_DesignObj']._DesignParameter['VDD_viastack']['_DesignObj']._DesignParameter['ViaMet22Met3']['_DesignObj']._DesignParameter['_Met3Layer']['_YWidth'])
		self._DesignParameter['METAL3_path_38']['_XYCoordinates'] = [[[((self._DesignParameter['SlicerInSlicerWithSRLatch_0']['_XYCoordinates'][0][0] + self._DesignParameter['SlicerInSlicerWithSRLatch_0']['_DesignObj']._DesignParameter['GuardringInSlicer_0']['_XYCoordinates'][0][0]) + self._DesignParameter['SlicerInSlicerWithSRLatch_0']['_DesignObj']._DesignParameter['GuardringInSlicer_0']['_DesignObj']._DesignParameter['left']['_XYCoordinates'][0][0]), (((self._DesignParameter['SlicerInSlicerWithSRLatch_0']['_XYCoordinates'][0][1] + self._DesignParameter['SlicerInSlicerWithSRLatch_0']['_DesignObj']._DesignParameter['VDD_viastack']['_XYCoordinates'][0][1]) + self._DesignParameter['SlicerInSlicerWithSRLatch_0']['_DesignObj']._DesignParameter['VDD_viastack']['_DesignObj']._DesignParameter['ViaMet22Met3']['_XYCoordinates'][0][1]) + self._DesignParameter['SlicerInSlicerWithSRLatch_0']['_DesignObj']._DesignParameter['VDD_viastack']['_DesignObj']._DesignParameter['ViaMet22Met3']['_DesignObj']._DesignParameter['_Met3Layer']['_XYCoordinates'][0][1])], [((self._DesignParameter['SlicerInSlicerWithSRLatch_0']['_XYCoordinates'][0][0] + self._DesignParameter['SlicerInSlicerWithSRLatch_0']['_DesignObj']._DesignParameter['GuardringInSlicer_0']['_XYCoordinates'][0][0]) + self._DesignParameter['SlicerInSlicerWithSRLatch_0']['_DesignObj']._DesignParameter['GuardringInSlicer_0']['_DesignObj']._DesignParameter['right']['_XYCoordinates'][0][0]), (((self._DesignParameter['SlicerInSlicerWithSRLatch_0']['_XYCoordinates'][0][1] + self._DesignParameter['SlicerInSlicerWithSRLatch_0']['_DesignObj']._DesignParameter['VDD_viastack']['_XYCoordinates'][0][1]) + self._DesignParameter['SlicerInSlicerWithSRLatch_0']['_DesignObj']._DesignParameter['VDD_viastack']['_DesignObj']._DesignParameter['ViaMet22Met3']['_XYCoordinates'][0][1]) + self._DesignParameter['SlicerInSlicerWithSRLatch_0']['_DesignObj']._DesignParameter['VDD_viastack']['_DesignObj']._DesignParameter['ViaMet22Met3']['_DesignObj']._DesignParameter['_Met3Layer']['_XYCoordinates'][0][1])]]]
		self._DesignParameter['inverter_gate_via'] = self._SrefElementDeclaration(_DesignObj=ViaStack._ViaStack(_Name='inverter_gate_viaIn{}'.format(_Name)))[0]
		self._DesignParameter['inverter_gate_via']['_DesignObj']._CalculateStackMinimumEnclosureY(**dict(COX=max(1, (1 + int(((((((((self._DesignParameter['InverterInSlicerWithSRLatch_0']['_XYCoordinates'][0][0] + self._DesignParameter['InverterInSlicerWithSRLatch_0']['_DesignObj']._DesignParameter['input_vias']['_XYCoordinates'][(- 1)][0]) + self._DesignParameter['InverterInSlicerWithSRLatch_0']['_DesignObj']._DesignParameter['input_vias']['_DesignObj']._DesignParameter['ViaMet22Met3']['_XYCoordinates'][0][0]) + self._DesignParameter['InverterInSlicerWithSRLatch_0']['_DesignObj']._DesignParameter['input_vias']['_DesignObj']._DesignParameter['ViaMet22Met3']['_DesignObj']._DesignParameter['_Met3Layer']['_XYCoordinates'][0][0]) + (self._DesignParameter['InverterInSlicerWithSRLatch_0']['_DesignObj']._DesignParameter['input_vias']['_DesignObj']._DesignParameter['ViaMet22Met3']['_DesignObj']._DesignParameter['_Met3Layer']['_XWidth'] / 2)) - ((((self._DesignParameter['InverterInSlicerWithSRLatch_0']['_XYCoordinates'][0][0] + self._DesignParameter['InverterInSlicerWithSRLatch_0']['_DesignObj']._DesignParameter['input_vias']['_XYCoordinates'][0][0]) + self._DesignParameter['InverterInSlicerWithSRLatch_0']['_DesignObj']._DesignParameter['input_vias']['_DesignObj']._DesignParameter['ViaMet22Met3']['_XYCoordinates'][0][0]) + self._DesignParameter['InverterInSlicerWithSRLatch_0']['_DesignObj']._DesignParameter['input_vias']['_DesignObj']._DesignParameter['ViaMet22Met3']['_DesignObj']._DesignParameter['_Met3Layer']['_XYCoordinates'][0][0]) - (self._DesignParameter['InverterInSlicerWithSRLatch_0']['_DesignObj']._DesignParameter['input_vias']['_DesignObj']._DesignParameter['ViaMet22Met3']['_DesignObj']._DesignParameter['_Met3Layer']['_XWidth'] / 2))) - drc._VIAxMinSpace) - (2 * drc._VIAxMinEnclosureByMetx)) / (drc._VIAxMinWidth + drc._VIAxMinSpace))))), COY=1, start_layer=3, end_layer=5))
		self._DesignParameter['inverter_gate_via']['_XYCoordinates'] = [[(((self._DesignParameter['InverterInSlicerWithSRLatch_0']['_XYCoordinates'][0][0] + self._DesignParameter['InverterInSlicerWithSRLatch_0']['_DesignObj']._DesignParameter['input_vias']['_XYCoordinates'][0][0]) + (self._DesignParameter['InverterInSlicerWithSRLatch_0']['_XYCoordinates'][0][0] + self._DesignParameter['InverterInSlicerWithSRLatch_0']['_DesignObj']._DesignParameter['input_vias']['_XYCoordinates'][(- 1)][0])) / 2), (self._DesignParameter['InverterInSlicerWithSRLatch_0']['_XYCoordinates'][0][1] + self._DesignParameter['InverterInSlicerWithSRLatch_0']['_DesignObj']._DesignParameter['input_vias']['_XYCoordinates'][0][1])]]
		inv_coy = max(1, (1 + int((((self._DesignParameter['InverterInSlicerWithSRLatch_0']['_DesignObj']._DesignParameter['pmos_drain_via']['_DesignObj']._DesignParameter['_Met2Layer']['_YWidth'] - drc._VIAxMinSpace) - (2 * drc._VIAxMinEnclosureByMetx)) / (drc._VIAxMinWidth + drc._VIAxMinSpace)))))
		self._DesignParameter['inv_output_via'] = self._SrefElementDeclaration(_DesignObj=ViaStack._ViaStack(_Name='inv_output_viaIn{}'.format(_Name)))[0]
		self._DesignParameter['inv_output_via']['_DesignObj']._CalculateStackMinimumEnclosureX(**dict(COX=1, COY=inv_coy, start_layer=2, end_layer=5))
		self._DesignParameter['inv_output_via']['_XYCoordinates'] = None
		XYList = []
		xy_offset = [0, 0]
		for i in range(len(self._DesignParameter['InverterInSlicerWithSRLatch_0']['_DesignObj']._DesignParameter['pmos_drain_via']['_XYCoordinates'])):
		    xy = (self._DesignParameter['InverterInSlicerWithSRLatch_0']['_DesignObj']._DesignParameter['pmos_drain_via']['_XYCoordinates'][i][0] if (type(self._DesignParameter['InverterInSlicerWithSRLatch_0']['_DesignObj']._DesignParameter['pmos_drain_via']['_XYCoordinates'][i][0]) == list) else self._DesignParameter['InverterInSlicerWithSRLatch_0']['_DesignObj']._DesignParameter['pmos_drain_via']['_XYCoordinates'][i])
		    XYList.append([((x + y) + z) for (x, y, z) in zip([(0 + self._DesignParameter['InverterInSlicerWithSRLatch_0']['_XYCoordinates'][0][0]), (0 + self._DesignParameter['InverterInSlicerWithSRLatch_0']['_XYCoordinates'][0][1])], xy, xy_offset)])
		self._DesignParameter['inv_output_via']['_XYCoordinates'] = XYList
		self._DesignParameter['M5V5M6_CDNS_6375475055648_0'] = self._SrefElementDeclaration(_DesignObj=ViaMet52Met6._ViaMet52Met6(_Name='M5V5M6_CDNS_6375475055648_0In{}'.format(_Name)))[0]
		self._DesignParameter['M5V5M6_CDNS_6375475055648_0']['_DesignObj']._CalculateViaMet52Met6DesignParameterMinimumEnclosureY(**dict(_ViaMet52Met6NumberOfCOX=2, _ViaMet52Met6NumberOfCOY=2, _MetalType={'METAL1': 'X', 'METAL2': 'X', 'METAL3': 'X', 'METAL4': 'X', 'METAL5': 'X', 'METAL6': 'X', 'METAL7': 'X', 'METAL8': 'Z', 'METAL9': 'Z'}))
		self._DesignParameter['M5V5M6_CDNS_6375475055648_0']['_XYCoordinates'] = [[self._DesignParameter['SlicerInSlicerWithSRLatch_0']['_XYCoordinates'][0][0], self._DesignParameter['inv_output_via']['_XYCoordinates'][0][1]]]
		self._DesignParameter['METAL5_path_11'] = self._PathElementDeclaration(_Layer=DesignParameters._LayerMapping['METAL5'][0], _Datatype=DesignParameters._LayerMapping['METAL5'][1], _Width=self._DesignParameter['M5V5M6_CDNS_6375475055648_0']['_DesignObj']._DesignParameter['_Met6Layer']['_YWidth'])
		self._DesignParameter['METAL5_path_11']['_XYCoordinates'] = [[[(+ self._DesignParameter['M5V5M6_CDNS_6375475055648_0']['_XYCoordinates'][0][0]), (+ self._DesignParameter['M5V5M6_CDNS_6375475055648_0']['_XYCoordinates'][0][1])], [self._DesignParameter['inv_output_via']['_XYCoordinates'][(- 1)][0], self._DesignParameter['M5V5M6_CDNS_6375475055648_0']['_XYCoordinates'][0][1]]]]
		self._DesignParameter['METAL3_path_39'] = self._PathElementDeclaration(_Layer=DesignParameters._LayerMapping['METAL3'][0], _Datatype=DesignParameters._LayerMapping['METAL3'][1], _Width=self._DesignParameter['METAL5_path_11']['_Width'])
		self._DesignParameter['METAL3_path_39']['_XYCoordinates'] = [[[(+ self._DesignParameter['inv_output_via']['_XYCoordinates'][0][0]), (+ self._DesignParameter['inv_output_via']['_XYCoordinates'][0][1])], [(+ self._DesignParameter['inv_output_via']['_XYCoordinates'][(- 1)][0]), (+ self._DesignParameter['inv_output_via']['_XYCoordinates'][(- 1)][1])]]]
		self._DesignParameter['M5V5M6_CDNS_6375475055648_1'] = self._SrefElementDeclaration(_DesignObj=ViaMet52Met6._ViaMet52Met6(_Name='M5V5M6_CDNS_6375475055648_1In{}'.format(_Name)))[0]
		self._DesignParameter['M5V5M6_CDNS_6375475055648_1']['_DesignObj']._CalculateViaMet52Met6DesignParameterMinimumEnclosureY(**dict(_ViaMet52Met6NumberOfCOX=2, _ViaMet52Met6NumberOfCOY=2, _MetalType={'METAL1': 'X', 'METAL2': 'X', 'METAL3': 'X', 'METAL4': 'X', 'METAL5': 'X', 'METAL6': 'X', 'METAL7': 'X', 'METAL8': 'Z', 'METAL9': 'Z'}))
		self._DesignParameter['M5V5M6_CDNS_6375475055648_1']['_XYCoordinates'] = [[self._DesignParameter['M5V5M6_CDNS_6375475055648_0']['_XYCoordinates'][0][0], (((self._DesignParameter['SlicerInSlicerWithSRLatch_0']['_XYCoordinates'][0][1] + self._DesignParameter['SlicerInSlicerWithSRLatch_0']['_DesignObj']._DesignParameter['METAL4_path_15']['_XYCoordinates'][0][0][1]) + (self._DesignParameter['SlicerInSlicerWithSRLatch_0']['_XYCoordinates'][0][1] + self._DesignParameter['SlicerInSlicerWithSRLatch_0']['_DesignObj']._DesignParameter['METAL4_path_15']['_XYCoordinates'][0][(- 1)][1])) / 2)]]
		self._DesignParameter['METAL6_path_8'] = self._PathElementDeclaration(_Layer=DesignParameters._LayerMapping['METAL6'][0], _Datatype=DesignParameters._LayerMapping['METAL6'][1], _Width=self._DesignParameter['M5V5M6_CDNS_6375475055648_0']['_DesignObj']._DesignParameter['_Met6Layer']['_XWidth'])
		self._DesignParameter['METAL6_path_8']['_XYCoordinates'] = [[[(+ self._DesignParameter['M5V5M6_CDNS_6375475055648_1']['_XYCoordinates'][0][0]), (+ self._DesignParameter['M5V5M6_CDNS_6375475055648_1']['_XYCoordinates'][0][1])], [(+ self._DesignParameter['M5V5M6_CDNS_6375475055648_0']['_XYCoordinates'][0][0]), (+ self._DesignParameter['M5V5M6_CDNS_6375475055648_0']['_XYCoordinates'][0][1])]]]
		self._DesignParameter['M4V4M5_CDNS_6375475055650_1'] = self._SrefElementDeclaration(_DesignObj=ViaMet42Met5._ViaMet42Met5(_Name='M4V4M5_CDNS_6375475055650_1In{}'.format(_Name)))[0]
		self._DesignParameter['M4V4M5_CDNS_6375475055650_1']['_DesignObj']._CalculateViaMet42Met5DesignParameterMinimumEnclosureY(**dict(_ViaMet42Met5NumberOfCOX=2, _ViaMet42Met5NumberOfCOY=2))
		self._DesignParameter['M4V4M5_CDNS_6375475055650_1']['_XYCoordinates'] = [[(self._DesignParameter['SlicerInSlicerWithSRLatch_0']['_XYCoordinates'][0][0] + self._DesignParameter['SlicerInSlicerWithSRLatch_0']['_DesignObj']._DesignParameter['METAL4_path_16']['_XYCoordinates'][0][0][0]), self._DesignParameter['M5V5M6_CDNS_6375475055648_1']['_XYCoordinates'][0][1]]]
		self._DesignParameter['M4V4M5_CDNS_6375475055650_0'] = self._SrefElementDeclaration(_DesignObj=ViaMet42Met5._ViaMet42Met5(_Name='M4V4M5_CDNS_6375475055650_0In{}'.format(_Name)))[0]
		self._DesignParameter['M4V4M5_CDNS_6375475055650_0']['_DesignObj']._CalculateViaMet42Met5DesignParameterMinimumEnclosureY(**dict(_ViaMet42Met5NumberOfCOX=2, _ViaMet42Met5NumberOfCOY=2))
		self._DesignParameter['M4V4M5_CDNS_6375475055650_0']['_XYCoordinates'] = [[(self._DesignParameter['SlicerInSlicerWithSRLatch_0']['_XYCoordinates'][0][0] + self._DesignParameter['SlicerInSlicerWithSRLatch_0']['_DesignObj']._DesignParameter['METAL4_path_15']['_XYCoordinates'][0][0][0]), self._DesignParameter['M5V5M6_CDNS_6375475055648_1']['_XYCoordinates'][0][1]]]
		self._DesignParameter['METAL5_path_10'] = self._PathElementDeclaration(_Layer=DesignParameters._LayerMapping['METAL5'][0], _Datatype=DesignParameters._LayerMapping['METAL5'][1], _Width=self._DesignParameter['M4V4M5_CDNS_6375475055650_1']['_DesignObj']._DesignParameter['_Met5Layer']['_YWidth'])
		self._DesignParameter['METAL5_path_10']['_XYCoordinates'] = [[[(+ self._DesignParameter['M4V4M5_CDNS_6375475055650_1']['_XYCoordinates'][0][0]), (+ self._DesignParameter['M4V4M5_CDNS_6375475055650_1']['_XYCoordinates'][0][1])], [(+ self._DesignParameter['M4V4M5_CDNS_6375475055650_0']['_XYCoordinates'][0][0]), (+ self._DesignParameter['M4V4M5_CDNS_6375475055650_0']['_XYCoordinates'][0][1])]]]
		self._DesignParameter['M1V1M2_CDNS_6375475055646_0'] = self._SrefElementDeclaration(_DesignObj=ViaMet12Met2._ViaMet12Met2(_Name='M1V1M2_CDNS_6375475055646_0In{}'.format(_Name)))[0]
		self._DesignParameter['M1V1M2_CDNS_6375475055646_0']['_DesignObj']._CalculateDesignParameterSameEnclosure(**dict(_ViaMet12Met2NumberOfCOX=max(1, (1 + int((((self._DesignParameter['InverterInSlicerWithSRLatch_0']['_DesignObj']._DesignParameter['PbodyContactInInverter_0']['_DesignObj']._DesignParameter['_Met1Layer']['_XWidth'] - drc._VIAxMinSpace2) - (2 * drc._VIAxMinEnclosureByMetx)) / (drc._VIAxMinWidth + drc._VIAxMinSpace2))))), _ViaMet12Met2NumberOfCOY=INV_parms['supply_coy']))
		self._DesignParameter['M1V1M2_CDNS_6375475055646_0']['_XYCoordinates'] = [[(+ (self._DesignParameter['InverterInSlicerWithSRLatch_0']['_XYCoordinates'][0][0] + self._DesignParameter['InverterInSlicerWithSRLatch_0']['_DesignObj']._DesignParameter['PbodyContactInInverter_0']['_XYCoordinates'][0][0])), (+ (self._DesignParameter['InverterInSlicerWithSRLatch_0']['_XYCoordinates'][0][1] + self._DesignParameter['InverterInSlicerWithSRLatch_0']['_DesignObj']._DesignParameter['PbodyContactInInverter_0']['_XYCoordinates'][0][1]))]]
		self._DesignParameter['met2_gnd_routing'] = self._PathElementDeclaration(_Layer=DesignParameters._LayerMapping['METAL2'][0], _Datatype=DesignParameters._LayerMapping['METAL2'][1], _Width=self._DesignParameter['M1V1M2_CDNS_6375475055646_0']['_DesignObj']._DesignParameter['_Met2Layer']['_YWidth'])
		self._DesignParameter['met2_gnd_routing']['_XYCoordinates'] = [[[((((self._DesignParameter['SlicerInSlicerWithSRLatch_0']['_XYCoordinates'][0][0] + self._DesignParameter['SlicerInSlicerWithSRLatch_0']['_DesignObj']._DesignParameter['GuardringInSlicer_0']['_XYCoordinates'][0][0]) + self._DesignParameter['SlicerInSlicerWithSRLatch_0']['_DesignObj']._DesignParameter['GuardringInSlicer_0']['_DesignObj']._DesignParameter['right']['_XYCoordinates'][0][0]) + self._DesignParameter['SlicerInSlicerWithSRLatch_0']['_DesignObj']._DesignParameter['GuardringInSlicer_0']['_DesignObj']._DesignParameter['right']['_DesignObj']._DesignParameter['_Met1Layer']['_XYCoordinates'][0][0]) - (self._DesignParameter['SlicerInSlicerWithSRLatch_0']['_DesignObj']._DesignParameter['GuardringInSlicer_0']['_DesignObj']._DesignParameter['right']['_DesignObj']._DesignParameter['_Met1Layer']['_XWidth'] / 2)), self._DesignParameter['M1V1M2_CDNS_6375475055646_0']['_XYCoordinates'][0][1]], [((self._DesignParameter['M1V1M2_CDNS_6375475055646_0']['_XYCoordinates'][0][0] + self._DesignParameter['M1V1M2_CDNS_6375475055646_0']['_DesignObj']._DesignParameter['_Met2Layer']['_XYCoordinates'][0][0]) + (self._DesignParameter['M1V1M2_CDNS_6375475055646_0']['_DesignObj']._DesignParameter['_Met2Layer']['_XWidth'] / 2)), self._DesignParameter['M1V1M2_CDNS_6375475055646_0']['_XYCoordinates'][0][1]]]]
		self._DesignParameter['M4V4M5_CDNS_6375475055645_3'] = self._SrefElementDeclaration(_DesignObj=ViaMet42Met5._ViaMet42Met5(_Name='M4V4M5_CDNS_6375475055645_3In{}'.format(_Name)))[0]
		self._DesignParameter['M4V4M5_CDNS_6375475055645_3']['_DesignObj']._CalculateViaMet42Met5DesignParameterMinimumEnclosureX(**dict(_ViaMet42Met5NumberOfCOX=2, _ViaMet42Met5NumberOfCOY=2))
		self._DesignParameter['M4V4M5_CDNS_6375475055645_3']['_XYCoordinates'] = [[(((self._DesignParameter['SlicerInSlicerWithSRLatch_0']['_XYCoordinates'][0][0] + self._DesignParameter['SlicerInSlicerWithSRLatch_0']['_DesignObj']._DesignParameter['METAL4_path_18']['_XYCoordinates'][0][0][0]) - (self._DesignParameter['SlicerInSlicerWithSRLatch_0']['_DesignObj']._DesignParameter['METAL4_path_18']['_Width'] / 2)) + (self._DesignParameter['M4V4M5_CDNS_6375475055645_3']['_DesignObj']._DesignParameter['_Met5Layer']['_XWidth'] / 2)), ((self._DesignParameter['SlicerInSlicerWithSRLatch_0']['_XYCoordinates'][0][1] + self._DesignParameter['SlicerInSlicerWithSRLatch_0']['_DesignObj']._DesignParameter['GuardringInPMOSSetofSlicer_0']['_XYCoordinates'][0][1]) + self._DesignParameter['SlicerInSlicerWithSRLatch_0']['_DesignObj']._DesignParameter['GuardringInPMOSSetofSlicer_0']['_DesignObj']._DesignParameter['bot']['_XYCoordinates'][0][1])]]
		self._DesignParameter['M4V4M5_CDNS_6375475055645_1'] = self._SrefElementDeclaration(_DesignObj=ViaMet42Met5._ViaMet42Met5(_Name='M4V4M5_CDNS_6375475055645_1In{}'.format(_Name)))[0]
		self._DesignParameter['M4V4M5_CDNS_6375475055645_1']['_DesignObj']._CalculateViaMet42Met5DesignParameterMinimumEnclosureX(**dict(_ViaMet42Met5NumberOfCOX=2, _ViaMet42Met5NumberOfCOY=2))
		self._DesignParameter['M4V4M5_CDNS_6375475055645_1']['_XYCoordinates'] = [[(self._DesignParameter['SRLatchInSlicerWithSRLatch_0']['_XYCoordinates'][0][0] + self._DesignParameter['SRLatchInSlicerWithSRLatch_0']['_DesignObj']._DesignParameter['METAL4_path_9']['_XYCoordinates'][0][0][0]), self._DesignParameter['M4V4M5_CDNS_6375475055645_3']['_XYCoordinates'][0][1]]]
		self._DesignParameter['METAL5_path_13'] = self._PathElementDeclaration(_Layer=DesignParameters._LayerMapping['METAL5'][0], _Datatype=DesignParameters._LayerMapping['METAL5'][1], _Width=self._DesignParameter['M4V4M5_CDNS_6375475055645_1']['_DesignObj']._DesignParameter['_Met5Layer']['_YWidth'])
		self._DesignParameter['METAL5_path_13']['_XYCoordinates'] = [[[(+ self._DesignParameter['M4V4M5_CDNS_6375475055645_3']['_XYCoordinates'][0][0]), (+ self._DesignParameter['M4V4M5_CDNS_6375475055645_3']['_XYCoordinates'][0][1])], [(+ self._DesignParameter['M4V4M5_CDNS_6375475055645_1']['_XYCoordinates'][0][0]), (+ self._DesignParameter['M4V4M5_CDNS_6375475055645_1']['_XYCoordinates'][0][1])]]]
		self._DesignParameter['M4V4M5_CDNS_6375475055645_0'] = self._SrefElementDeclaration(_DesignObj=ViaMet42Met5._ViaMet42Met5(_Name='M4V4M5_CDNS_6375475055645_0In{}'.format(_Name)))[0]
		self._DesignParameter['M4V4M5_CDNS_6375475055645_0']['_DesignObj']._CalculateViaMet42Met5DesignParameterMinimumEnclosureX(**dict(_ViaMet42Met5NumberOfCOX=2, _ViaMet42Met5NumberOfCOY=2))
		self._DesignParameter['M4V4M5_CDNS_6375475055645_0']['_XYCoordinates'] = [[(((self._DesignParameter['SlicerInSlicerWithSRLatch_0']['_XYCoordinates'][0][0] + self._DesignParameter['SlicerInSlicerWithSRLatch_0']['_DesignObj']._DesignParameter['METAL4_path_19']['_XYCoordinates'][0][0][0]) + (self._DesignParameter['SlicerInSlicerWithSRLatch_0']['_DesignObj']._DesignParameter['METAL4_path_19']['_Width'] / 2)) + ((- self._DesignParameter['M4V4M5_CDNS_6375475055645_0']['_DesignObj']._DesignParameter['_Met5Layer']['_XWidth']) / 2)), ((self._DesignParameter['SlicerInSlicerWithSRLatch_0']['_XYCoordinates'][0][1] + self._DesignParameter['SlicerInSlicerWithSRLatch_0']['_DesignObj']._DesignParameter['GuardringInNMOSSetofSlicer_0']['_XYCoordinates'][0][1]) + self._DesignParameter['SlicerInSlicerWithSRLatch_0']['_DesignObj']._DesignParameter['GuardringInNMOSSetofSlicer_0']['_DesignObj']._DesignParameter['top']['_XYCoordinates'][0][1])]]
		self._DesignParameter['M4V4M5_CDNS_6375475055645_2'] = self._SrefElementDeclaration(_DesignObj=ViaMet42Met5._ViaMet42Met5(_Name='M4V4M5_CDNS_6375475055645_2In{}'.format(_Name)))[0]
		self._DesignParameter['M4V4M5_CDNS_6375475055645_2']['_DesignObj']._CalculateViaMet42Met5DesignParameterMinimumEnclosureX(**dict(_ViaMet42Met5NumberOfCOX=2, _ViaMet42Met5NumberOfCOY=2))
		self._DesignParameter['M4V4M5_CDNS_6375475055645_2']['_XYCoordinates'] = [[(self._DesignParameter['SRLatchInSlicerWithSRLatch_0']['_XYCoordinates'][0][0] + self._DesignParameter['SRLatchInSlicerWithSRLatch_0']['_DesignObj']._DesignParameter['METAL4_path_11']['_XYCoordinates'][0][0][0]), self._DesignParameter['M4V4M5_CDNS_6375475055645_0']['_XYCoordinates'][0][1]]]
		self._DesignParameter['METAL5_path_12'] = self._PathElementDeclaration(_Layer=DesignParameters._LayerMapping['METAL5'][0], _Datatype=DesignParameters._LayerMapping['METAL5'][1], _Width=self._DesignParameter['M4V4M5_CDNS_6375475055645_1']['_DesignObj']._DesignParameter['_Met5Layer']['_YWidth'])
		self._DesignParameter['METAL5_path_12']['_XYCoordinates'] = [[[(+ self._DesignParameter['M4V4M5_CDNS_6375475055645_0']['_XYCoordinates'][0][0]), (+ self._DesignParameter['M4V4M5_CDNS_6375475055645_0']['_XYCoordinates'][0][1])], [(+ self._DesignParameter['M4V4M5_CDNS_6375475055645_2']['_XYCoordinates'][0][0]), (+ self._DesignParameter['M4V4M5_CDNS_6375475055645_2']['_XYCoordinates'][0][1])]]]
		self._DesignParameter['METAL1_path_74'] = self._PathElementDeclaration(_Layer=DesignParameters._LayerMapping['METAL1'][0], _Datatype=DesignParameters._LayerMapping['METAL1'][1], _Width=self._DesignParameter['SRLatchInSlicerWithSRLatch_0']['_DesignObj']._DesignParameter['PbodyContactInSRLatch_0']['_DesignObj']._DesignParameter['_Met1Layer']['_YWidth'])
		self._DesignParameter['METAL1_path_74']['_XYCoordinates'] = [[[(+ (self._DesignParameter['SRLatchInSlicerWithSRLatch_0']['_XYCoordinates'][0][0] + self._DesignParameter['SRLatchInSlicerWithSRLatch_0']['_DesignObj']._DesignParameter['PbodyContactInSRLatch_0']['_XYCoordinates'][0][0])), (+ (self._DesignParameter['SRLatchInSlicerWithSRLatch_0']['_XYCoordinates'][0][1] + self._DesignParameter['SRLatchInSlicerWithSRLatch_0']['_DesignObj']._DesignParameter['PbodyContactInSRLatch_0']['_XYCoordinates'][0][1]))], [((self._DesignParameter['SlicerInSlicerWithSRLatch_0']['_XYCoordinates'][0][0] + self._DesignParameter['SlicerInSlicerWithSRLatch_0']['_DesignObj']._DesignParameter['GuardringInSlicer_0']['_XYCoordinates'][0][0]) + self._DesignParameter['SlicerInSlicerWithSRLatch_0']['_DesignObj']._DesignParameter['GuardringInSlicer_0']['_DesignObj']._DesignParameter['right']['_XYCoordinates'][0][0]), (self._DesignParameter['SRLatchInSlicerWithSRLatch_0']['_XYCoordinates'][0][1] + self._DesignParameter['SRLatchInSlicerWithSRLatch_0']['_DesignObj']._DesignParameter['PbodyContactInSRLatch_0']['_XYCoordinates'][0][1])]]]
		self._DesignParameter['VDD_pin'] = self._TextElementDeclaration(_Layer=DesignParameters._LayerMapping['METAL1PIN'][0], _Datatype=DesignParameters._LayerMapping['METAL1PIN'][1], _Presentation=[0, 1, 2], _Reflect=[0, 0, 0], _XYCoordinates=[[(+ (self._DesignParameter['SlicerInSlicerWithSRLatch_0']['_XYCoordinates'][0][0] + self._DesignParameter['SlicerInSlicerWithSRLatch_0']['_DesignObj']._DesignParameter['VDD_viastack']['_XYCoordinates'][0][0])), (+ (self._DesignParameter['SlicerInSlicerWithSRLatch_0']['_XYCoordinates'][0][1] + self._DesignParameter['SlicerInSlicerWithSRLatch_0']['_DesignObj']._DesignParameter['VDD_viastack']['_XYCoordinates'][0][1]))], [(+ (self._DesignParameter['SRLatchInSlicerWithSRLatch_0']['_XYCoordinates'][0][0] + self._DesignParameter['SRLatchInSlicerWithSRLatch_0']['_DesignObj']._DesignParameter['VDD_top_vias']['_XYCoordinates'][0][0])), (+ (self._DesignParameter['SRLatchInSlicerWithSRLatch_0']['_XYCoordinates'][0][1] + self._DesignParameter['SRLatchInSlicerWithSRLatch_0']['_DesignObj']._DesignParameter['VDD_top_vias']['_XYCoordinates'][0][1]))], [(+ (self._DesignParameter['SRLatchInSlicerWithSRLatch_0']['_XYCoordinates'][0][0] + self._DesignParameter['SRLatchInSlicerWithSRLatch_0']['_DesignObj']._DesignParameter['VDD_down_vias']['_XYCoordinates'][0][0])), (+ (self._DesignParameter['SRLatchInSlicerWithSRLatch_0']['_XYCoordinates'][0][1] + self._DesignParameter['SRLatchInSlicerWithSRLatch_0']['_DesignObj']._DesignParameter['VDD_down_vias']['_XYCoordinates'][0][1]))]], _Mag=0.1, _Angle=0, _TEXT='VDD')
		self._DesignParameter['OUTb'] = self._TextElementDeclaration(_Layer=DesignParameters._LayerMapping['METAL1PIN'][0], _Datatype=DesignParameters._LayerMapping['METAL1PIN'][1], _Presentation=[0, 1, 2], _Reflect=[0, 0, 0], _XYCoordinates=[[(+ (self._DesignParameter['SRLatchInSlicerWithSRLatch_0']['_XYCoordinates'][0][0] + self._DesignParameter['SRLatchInSlicerWithSRLatch_0']['_DesignObj']._DesignParameter['M1V1M2_CDNS_6375475055616_7']['_XYCoordinates'][0][0])), (+ (self._DesignParameter['SRLatchInSlicerWithSRLatch_0']['_XYCoordinates'][0][1] + self._DesignParameter['SRLatchInSlicerWithSRLatch_0']['_DesignObj']._DesignParameter['M1V1M2_CDNS_6375475055616_7']['_XYCoordinates'][0][1]))]], _Mag=0.1, _Angle=0, _TEXT='OUTb')
		self._DesignParameter['OUT'] = self._TextElementDeclaration(_Layer=DesignParameters._LayerMapping['METAL1PIN'][0], _Datatype=DesignParameters._LayerMapping['METAL1PIN'][1], _Presentation=[0, 1, 2], _Reflect=[0, 0, 0], _XYCoordinates=[[(+ (self._DesignParameter['SRLatchInSlicerWithSRLatch_0']['_XYCoordinates'][0][0] + self._DesignParameter['SRLatchInSlicerWithSRLatch_0']['_DesignObj']._DesignParameter['up_output_viatack']['_XYCoordinates'][0][0])), (+ (self._DesignParameter['SRLatchInSlicerWithSRLatch_0']['_XYCoordinates'][0][1] + self._DesignParameter['SRLatchInSlicerWithSRLatch_0']['_DesignObj']._DesignParameter['up_output_viatack']['_XYCoordinates'][0][1]))]], _Mag=0.1, _Angle=0, _TEXT='OUT')
		self._DesignParameter['INn'] = self._TextElementDeclaration(_Layer=DesignParameters._LayerMapping['METAL1PIN'][0], _Datatype=DesignParameters._LayerMapping['METAL1PIN'][1], _Presentation=[0, 1, 2], _Reflect=[0, 0, 0], _XYCoordinates=[[(+ (self._DesignParameter['SlicerInSlicerWithSRLatch_0']['_XYCoordinates'][0][0] + self._DesignParameter['SlicerInSlicerWithSRLatch_0']['_DesignObj']._DesignParameter['pccam_nmos_right']['_XYCoordinates'][0][0])), (+ (self._DesignParameter['SlicerInSlicerWithSRLatch_0']['_XYCoordinates'][0][1] + self._DesignParameter['SlicerInSlicerWithSRLatch_0']['_DesignObj']._DesignParameter['pccam_nmos_right']['_XYCoordinates'][0][1]))]], _Mag=0.1, _Angle=0, _TEXT='INn')
		self._DesignParameter['INp'] = self._TextElementDeclaration(_Layer=DesignParameters._LayerMapping['METAL1PIN'][0], _Datatype=DesignParameters._LayerMapping['METAL1PIN'][1], _Presentation=[0, 1, 2], _Reflect=[0, 0, 0], _XYCoordinates=[[(+ (self._DesignParameter['SlicerInSlicerWithSRLatch_0']['_XYCoordinates'][0][0] + self._DesignParameter['SlicerInSlicerWithSRLatch_0']['_DesignObj']._DesignParameter['pccam_nmos_left']['_XYCoordinates'][0][0])), (+ (self._DesignParameter['SlicerInSlicerWithSRLatch_0']['_XYCoordinates'][0][1] + self._DesignParameter['SlicerInSlicerWithSRLatch_0']['_DesignObj']._DesignParameter['pccam_nmos_left']['_XYCoordinates'][0][1]))]], _Mag=0.1, _Angle=0, _TEXT='INp')
		self._DesignParameter['VSS_pin'] = self._TextElementDeclaration(_Layer=DesignParameters._LayerMapping['METAL1PIN'][0], _Datatype=DesignParameters._LayerMapping['METAL1PIN'][1], _Presentation=[0, 1, 2], _Reflect=[0, 0, 0], _XYCoordinates=[[(+ (self._DesignParameter['SlicerInSlicerWithSRLatch_0']['_XYCoordinates'][0][0] + self._DesignParameter['SlicerInSlicerWithSRLatch_0']['_DesignObj']._DesignParameter['VSS_viastack_1to3']['_XYCoordinates'][0][0])), (+ (self._DesignParameter['SlicerInSlicerWithSRLatch_0']['_XYCoordinates'][0][1] + self._DesignParameter['SlicerInSlicerWithSRLatch_0']['_DesignObj']._DesignParameter['VSS_viastack_1to3']['_XYCoordinates'][0][1]))]], _Mag=0.1, _Angle=0, _TEXT='VSS')
		self._DesignParameter['CLK'] = self._TextElementDeclaration(_Layer=DesignParameters._LayerMapping['METAL1PIN'][0], _Datatype=DesignParameters._LayerMapping['METAL1PIN'][1], _Presentation=[0, 1, 2], _Reflect=[0, 0, 0], _XYCoordinates=[[(+ (self._DesignParameter['InverterInSlicerWithSRLatch_0']['_XYCoordinates'][0][0] + self._DesignParameter['InverterInSlicerWithSRLatch_0']['_DesignObj']._DesignParameter['PCCAM1_CDNS_6375475055681_1']['_XYCoordinates'][0][0])), (+ (self._DesignParameter['InverterInSlicerWithSRLatch_0']['_XYCoordinates'][0][1] + self._DesignParameter['InverterInSlicerWithSRLatch_0']['_DesignObj']._DesignParameter['PCCAM1_CDNS_6375475055681_1']['_XYCoordinates'][0][1]))]], _Mag=0.1, _Angle=0, _TEXT='CLK')
		self._DesignParameter['met2_vss_vertical'] = self._PathElementDeclaration(_Layer=DesignParameters._LayerMapping['METAL2'][0], _Datatype=DesignParameters._LayerMapping['METAL2'][1], _Width=self._DesignParameter['met2_gnd_routing']['_Width'])
		self._DesignParameter['met2_vss_vertical']['_XYCoordinates'] = [[[((self._DesignParameter['met2_gnd_routing']['_Width'] / 2) + self._DesignParameter['met2_gnd_routing']['_XYCoordinates'][0][0][0]), (+ self._DesignParameter['met2_gnd_routing']['_XYCoordinates'][0][0][1])], [((self._DesignParameter['met2_gnd_routing']['_Width'] / 2) + self._DesignParameter['met2_gnd_routing']['_XYCoordinates'][0][0][0]), ((self._DesignParameter['SlicerInSlicerWithSRLatch_0']['_XYCoordinates'][0][1] + self._DesignParameter['SlicerInSlicerWithSRLatch_0']['_DesignObj']._DesignParameter['METAL2_boundary_46']['_XYCoordinates'][0][1]) - (self._DesignParameter['SlicerInSlicerWithSRLatch_0']['_DesignObj']._DesignParameter['METAL2_boundary_46']['_YWidth'] / 2))]]]
		if (self._DesignParameter['InverterInSlicerWithSRLatch_0']['_DesignObj']._DesignParameter['NbodyContactInInverter_0']['_DesignObj']._DesignParameter['_Met1Layer']['_XWidth'] >= self._DesignParameter['SRLatchInSlicerWithSRLatch_0']['_DesignObj']._DesignParameter['NbodyContactInSRLatch_0']['_DesignObj']._DesignParameter['_Met1Layer']['_XWidth']):
		    self._DesignParameter['SRLatchInSlicerWithSRLatch_0']['_DesignObj']._DesignParameter['NbodyContactInSRLatch_0']['_Ignore'] = True
		else:
		    self._DesignParameter['InverterInSlicerWithSRLatch_0']['_DesignObj']._DesignParameter['NbodyContactInInverter_0']['_Ignore'] = True
		self._DesignParameter['met1_drc'] = self._BoundaryElementDeclaration(_Layer=DesignParameters._LayerMapping['METAL1'][0], _Datatype=DesignParameters._LayerMapping['METAL1'][1], _XWidth=max(self._DesignParameter['M1V1M2_CDNS_6375475055646_0']['_DesignObj']._DesignParameter['_Met1Layer']['_XWidth'], self._DesignParameter['InverterInSlicerWithSRLatch_0']['_DesignObj']._DesignParameter['PbodyContactInInverter_0']['_DesignObj']._DesignParameter['_Met1Layer']['_XWidth']), _YWidth=max(self._DesignParameter['M1V1M2_CDNS_6375475055646_0']['_DesignObj']._DesignParameter['_Met1Layer']['_YWidth'], self._DesignParameter['InverterInSlicerWithSRLatch_0']['_DesignObj']._DesignParameter['PbodyContactInInverter_0']['_DesignObj']._DesignParameter['_Met1Layer']['_YWidth']))
		self._DesignParameter['met1_drc']['_XYCoordinates'] = [[(+ self._DesignParameter['M1V1M2_CDNS_6375475055646_0']['_XYCoordinates'][0][0]), (+ self._DesignParameter['M1V1M2_CDNS_6375475055646_0']['_XYCoordinates'][0][1])]]
		