from generatorLib import StickDiagram
from generatorLib import DesignParameters
import copy
import math
from generatorLib import DRC
from generatorLib.generator_models.rx_project import ViaMet22Met3
from generatorLib.generator_models.rx_project import ViaMet12Met2
from generatorLib.generator_models.rx_project import NSubRing
from generatorLib.generator_models.rx_project import ViaPoly2Met1
from generatorLib.generator_models.rx_project import PSubRing
from generatorLib.generator_models.rx_project import ViaStack
from generatorLib.generator_models.rx_project import PMOSWithDummy
from generatorLib.generator_models.rx_project import NMOSWithDummy

class transmission_gate(StickDiagram._StickDiagram):
	def __init__(self, _DesignParameter=None, _Name='transmission_gate'):
		if _DesignParameter != None:
			self._DesignParameter = _DesignParameter
		else:
			self._DesignParameter = dict(_Name=self._NameDeclaration(_Name=_Name), _GDSFile=self._GDSObjDeclaration(_GDSFile=None))
		self._DesignParameter['_Name']['Name'] = _Name

	def _CalculateDesignParameter(self,number_of_gate=10,nmos_width=300,pmos_width=600,subring_contact=2,SLVT=None,nmos_coy=None,pmos_coy=None):
	
		drc = DRC.DRC()
		_Name = self._DesignParameter['_Name']['_Name']
		
		self._DesignParameter['NMOSInTransmissionGate_0'] = self._SrefElementDeclaration(_DesignObj=NMOSWithDummy._NMOS(_Name='NMOSInTransmissionGate_0In{}'.format(_Name)))[0]
		self._DesignParameter['NMOSInTransmissionGate_0']['_DesignObj']._CalculateNMOSDesignParameter(**dict(_NMOSNumberofGate=number_of_gate, _NMOSChannelWidth=nmos_width, _NMOSChannellength=30, _NMOSDummy=True, _GateSpacing=None, _SDWidth=None, _XVT='SLVT', _PCCrit=None))
		self._DesignParameter['NMOSInTransmissionGate_0']['_XYCoordinates'] = [[0, 379]]
		nmos_coy = max(max(1, (1 + int((((self._DesignParameter['NMOSInTransmissionGate_0']['_DesignObj']._DesignParameter['_Met1Layer']['_YWidth'] - drc._VIAxMinSpace) - (2 * drc._VIAxMinEnclosureByMetx)) / (drc._VIAxMinWidth + drc._VIAxMinSpace))))), 2)
		self._DesignParameter['nmos_source_via'] = self._SrefElementDeclaration(_DesignObj=ViaStack._ViaStack(_Name='nmos_source_viaIn{}'.format(_Name)))[0]
		self._DesignParameter['nmos_source_via']['_DesignObj']._CalculateStackMinimumEnclosureX(**dict(COX=1, COY=nmos_coy, start_layer=1, end_layer=3))
		self._DesignParameter['nmos_source_via']['_XYCoordinates'] = None
		XYList = []
		xy_offset = (0, (- int(((drc._VIAxMinWidth + drc._VIAxMinSpace) / 4))))
		for i in range(len(self._DesignParameter['NMOSInTransmissionGate_0']['_DesignObj']._DesignParameter['_Met1Layer']['_XYCoordinates'])):
		    if ((i % 2) == 0):
		        xy = (self._DesignParameter['NMOSInTransmissionGate_0']['_DesignObj']._DesignParameter['_Met1Layer']['_XYCoordinates'][i][0] if (type(self._DesignParameter['NMOSInTransmissionGate_0']['_DesignObj']._DesignParameter['_Met1Layer']['_XYCoordinates'][i][0]) == list) else self._DesignParameter['NMOSInTransmissionGate_0']['_DesignObj']._DesignParameter['_Met1Layer']['_XYCoordinates'][i])
		        XYList.append([((x + y) + z) for (x, y, z) in zip([(0 + self._DesignParameter['NMOSInTransmissionGate_0']['_XYCoordinates'][0][0]), (0 + self._DesignParameter['NMOSInTransmissionGate_0']['_XYCoordinates'][0][1])], xy, xy_offset)])
		self._DesignParameter['nmos_source_via']['_XYCoordinates'] = XYList
		self._DesignParameter['nmos_drain_via'] = self._SrefElementDeclaration(_DesignObj=ViaMet12Met2._ViaMet12Met2(_Name='nmos_drain_viaIn{}'.format(_Name)))[0]
		self._DesignParameter['nmos_drain_via']['_DesignObj']._CalculateViaMet12Met2DesignParameterMinimumEnclosureX(**dict(_ViaMet12Met2NumberOfCOX=1, _ViaMet12Met2NumberOfCOY=nmos_coy))
		self._DesignParameter['nmos_drain_via']['_XYCoordinates'] = None
		XYList = []
		xy_offset = (0, int(((drc._VIAxMinWidth + drc._VIAxMinSpace) / 4)))
		for i in range(len(self._DesignParameter['NMOSInTransmissionGate_0']['_DesignObj']._DesignParameter['_Met1Layer']['_XYCoordinates'])):
		    if ((i % 2) == 1):
		        xy = (self._DesignParameter['NMOSInTransmissionGate_0']['_DesignObj']._DesignParameter['_Met1Layer']['_XYCoordinates'][i][0] if (type(self._DesignParameter['NMOSInTransmissionGate_0']['_DesignObj']._DesignParameter['_Met1Layer']['_XYCoordinates'][i][0]) == list) else self._DesignParameter['NMOSInTransmissionGate_0']['_DesignObj']._DesignParameter['_Met1Layer']['_XYCoordinates'][i])
		        XYList.append([((x + y) + z) for (x, y, z) in zip([(0 + self._DesignParameter['NMOSInTransmissionGate_0']['_XYCoordinates'][0][0]), (0 + self._DesignParameter['NMOSInTransmissionGate_0']['_XYCoordinates'][0][1])], xy, xy_offset)])
		self._DesignParameter['nmos_drain_via']['_XYCoordinates'] = XYList
		self._DesignParameter['PCCAM1_CDNS_6375475055632_1'] = self._SrefElementDeclaration(_DesignObj=ViaPoly2Met1._ViaPoly2Met1(_Name='PCCAM1_CDNS_6375475055632_1In{}'.format(_Name)))[0]
		self._DesignParameter['PCCAM1_CDNS_6375475055632_1']['_DesignObj']._CalculateViaPoly2Met1DesignParameter(**dict(_ViaPoly2Met1NumberOfCOX=max(1, (1 + int(((((((self._DesignParameter['NMOSInTransmissionGate_0']['_XYCoordinates'][0][0] + self._DesignParameter['NMOSInTransmissionGate_0']['_DesignObj']._DesignParameter['_POLayer']['_XYCoordinates'][(- 1)][0]) + (self._DesignParameter['NMOSInTransmissionGate_0']['_DesignObj']._DesignParameter['_POLayer']['_XWidth'] / 2)) - ((self._DesignParameter['NMOSInTransmissionGate_0']['_XYCoordinates'][0][0] + self._DesignParameter['NMOSInTransmissionGate_0']['_DesignObj']._DesignParameter['_POLayer']['_XYCoordinates'][0][0]) - (self._DesignParameter['NMOSInTransmissionGate_0']['_DesignObj']._DesignParameter['_POLayer']['_XWidth'] / 2))) - drc._CoMinSpace) - (2 * drc._CoMinEnclosureByPO)) / (drc._CoMinWidth + drc._CoMinSpace))))), _ViaPoly2Met1NumberOfCOY=1))
		self._DesignParameter['PCCAM1_CDNS_6375475055632_1']['_XYCoordinates'] = [[self._DesignParameter['NMOSInTransmissionGate_0']['_XYCoordinates'][0][0], max(((((self._DesignParameter['NMOSInTransmissionGate_0']['_XYCoordinates'][0][1] + self._DesignParameter['NMOSInTransmissionGate_0']['_DesignObj']._DesignParameter['_Met1Layer']['_XYCoordinates'][0][1]) + (self._DesignParameter['NMOSInTransmissionGate_0']['_DesignObj']._DesignParameter['_Met1Layer']['_YWidth'] / 2)) + drc._Metal1MinSpace21) + (self._DesignParameter['PCCAM1_CDNS_6375475055632_1']['_DesignObj']._DesignParameter['_Met1Layer']['_YWidth'] / 2)), ((((self._DesignParameter['nmos_drain_via']['_XYCoordinates'][0][1] + self._DesignParameter['nmos_drain_via']['_DesignObj']._DesignParameter['_Met1Layer']['_XYCoordinates'][0][1]) + (self._DesignParameter['nmos_drain_via']['_DesignObj']._DesignParameter['_Met1Layer']['_YWidth'] / 2)) + drc._Metal1MinSpace21) + (self._DesignParameter['PCCAM1_CDNS_6375475055632_1']['_DesignObj']._DesignParameter['_Met1Layer']['_YWidth'] / 2)))]]
		self._DesignParameter['nmos_input_vias'] = self._SrefElementDeclaration(_DesignObj=ViaStack._ViaStack(_Name='nmos_input_viasIn{}'.format(_Name)))[0]
		self._DesignParameter['nmos_input_vias']['_DesignObj']._CalculateStackMinimumEnclosureY(**dict(COX=2, COY=1, start_layer=1, end_layer=5))
		self._DesignParameter['nmos_input_vias']['_XYCoordinates'] = [[((((self._DesignParameter['NMOSInTransmissionGate_0']['_XYCoordinates'][0][0] + self._DesignParameter['NMOSInTransmissionGate_0']['_DesignObj']._DesignParameter['_Met1Layer']['_XYCoordinates'][1][0]) - (self._DesignParameter['NMOSInTransmissionGate_0']['_DesignObj']._DesignParameter['_Met1Layer']['_XWidth'] / 2)) - drc._MetalxMinSpace21) - (self._DesignParameter['nmos_input_vias']['_DesignObj']._DesignParameter['ViaMet42Met5']['_DesignObj']._DesignParameter['_Met5Layer']['_XWidth'] / 2)), self._DesignParameter['PCCAM1_CDNS_6375475055632_1']['_XYCoordinates'][0][1]]]
		self._DesignParameter['NMOSSubringInResistorBank_0'] = self._SrefElementDeclaration(_DesignObj=PSubRing.PSubRing(_Name='NMOSSubringInResistorBank_0In{}'.format(_Name)))[0]
		self._DesignParameter['NMOSSubringInResistorBank_0']['_DesignObj']._CalculateDesignParameter(**dict(height=(((((self._DesignParameter['PCCAM1_CDNS_6375475055632_1']['_XYCoordinates'][0][1] + self._DesignParameter['PCCAM1_CDNS_6375475055632_1']['_DesignObj']._DesignParameter['_Met1Layer']['_XYCoordinates'][0][1]) + (self._DesignParameter['PCCAM1_CDNS_6375475055632_1']['_DesignObj']._DesignParameter['_Met1Layer']['_YWidth'] / 2)) + drc._Metal1MinSpace3) - ((self._DesignParameter['NMOSInTransmissionGate_0']['_XYCoordinates'][0][1] + self._DesignParameter['NMOSInTransmissionGate_0']['_DesignObj']._DesignParameter['_ODLayer']['_XYCoordinates'][0][1]) - (self._DesignParameter['NMOSInTransmissionGate_0']['_DesignObj']._DesignParameter['_ODLayer']['_YWidth'] / 2))) + drc._OdMinSpace), width=(((((self._DesignParameter['NMOSInTransmissionGate_0']['_XYCoordinates'][0][0] + self._DesignParameter['NMOSInTransmissionGate_0']['_DesignObj']._DesignParameter['_ODLayer']['_XYCoordinates'][0][0]) + (self._DesignParameter['NMOSInTransmissionGate_0']['_DesignObj']._DesignParameter['_ODLayer']['_XWidth'] / 2)) + drc._OdMinSpace) - (((self._DesignParameter['nmos_input_vias']['_XYCoordinates'][0][0] + self._DesignParameter['nmos_input_vias']['_DesignObj']._DesignParameter['ViaMet12Met2']['_XYCoordinates'][0][0]) + self._DesignParameter['nmos_input_vias']['_DesignObj']._DesignParameter['ViaMet12Met2']['_DesignObj']._DesignParameter['_Met1Layer']['_XYCoordinates'][0][0]) - (self._DesignParameter['nmos_input_vias']['_DesignObj']._DesignParameter['ViaMet12Met2']['_DesignObj']._DesignParameter['_Met1Layer']['_XWidth'] / 2))) - drc._Metal1MinSpace3), contact=subring_contact))
		self._DesignParameter['NMOSSubringInResistorBank_0']['_XYCoordinates'] = [[(- 90.0), 454.0]]
		self._DesignParameter['NMOSSubringInResistorBank_0']['_DesignObj']._CalculateDesignParameter(**dict(height=((self._DesignParameter['NMOSSubringInResistorBank_0']['_DesignObj']._DesignParameter['bot']['_DesignObj']._DesignParameter['_Met1Layer']['_YWidth'] + (drc._Metal1MinSpace3 * 2)) + (((self._DesignParameter['PCCAM1_CDNS_6375475055632_1']['_XYCoordinates'][0][1] + self._DesignParameter['PCCAM1_CDNS_6375475055632_1']['_DesignObj']._DesignParameter['_Met1Layer']['_XYCoordinates'][0][1]) + (self._DesignParameter['PCCAM1_CDNS_6375475055632_1']['_DesignObj']._DesignParameter['_Met1Layer']['_YWidth'] / 2)) - min(((self._DesignParameter['NMOSInTransmissionGate_0']['_XYCoordinates'][0][1] + self._DesignParameter['NMOSInTransmissionGate_0']['_DesignObj']._DesignParameter['_Met1Layer']['_XYCoordinates'][0][1]) - (self._DesignParameter['NMOSInTransmissionGate_0']['_DesignObj']._DesignParameter['_Met1Layer']['_YWidth'] / 2)), (((self._DesignParameter['nmos_source_via']['_XYCoordinates'][0][1] + self._DesignParameter['nmos_source_via']['_DesignObj']._DesignParameter['ViaMet12Met2']['_XYCoordinates'][0][1]) + self._DesignParameter['nmos_source_via']['_DesignObj']._DesignParameter['ViaMet12Met2']['_DesignObj']._DesignParameter['_Met1Layer']['_XYCoordinates'][0][1]) - (self._DesignParameter['nmos_source_via']['_DesignObj']._DesignParameter['ViaMet12Met2']['_DesignObj']._DesignParameter['_Met1Layer']['_YWidth'] / 2))))), width=(((((((self._DesignParameter['NMOSInTransmissionGate_0']['_XYCoordinates'][0][0] + self._DesignParameter['NMOSInTransmissionGate_0']['_DesignObj']._DesignParameter['_ODLayer']['_XYCoordinates'][0][0]) + (self._DesignParameter['NMOSInTransmissionGate_0']['_DesignObj']._DesignParameter['_ODLayer']['_XWidth'] / 2)) + drc._OdMinSpace) + (self._DesignParameter['NMOSSubringInResistorBank_0']['_DesignObj']._DesignParameter['right']['_DesignObj']._DesignParameter['_PPLayer']['_XWidth'] / 2)) - (((self._DesignParameter['nmos_input_vias']['_XYCoordinates'][0][0] + self._DesignParameter['nmos_input_vias']['_DesignObj']._DesignParameter['ViaMet12Met2']['_XYCoordinates'][0][0]) + self._DesignParameter['nmos_input_vias']['_DesignObj']._DesignParameter['ViaMet12Met2']['_DesignObj']._DesignParameter['_Met1Layer']['_XYCoordinates'][0][0]) - (self._DesignParameter['nmos_input_vias']['_DesignObj']._DesignParameter['ViaMet12Met2']['_DesignObj']._DesignParameter['_Met1Layer']['_XWidth'] / 2))) + drc._Metal1MinSpace3) + (self._DesignParameter['NMOSSubringInResistorBank_0']['_DesignObj']._DesignParameter['left']['_DesignObj']._DesignParameter['_Met1Layer']['_XWidth'] / 2)), contact=subring_contact))
		self._DesignParameter['NMOSSubringInResistorBank_0']['_XYCoordinates'] = [[((((((self._DesignParameter['NMOSInTransmissionGate_0']['_XYCoordinates'][0][0] + self._DesignParameter['NMOSInTransmissionGate_0']['_DesignObj']._DesignParameter['_ODLayer']['_XYCoordinates'][0][0]) + (self._DesignParameter['NMOSInTransmissionGate_0']['_DesignObj']._DesignParameter['_ODLayer']['_XWidth'] / 2)) + drc._OdMinSpace) + (self._DesignParameter['NMOSSubringInResistorBank_0']['_DesignObj']._DesignParameter['right']['_DesignObj']._DesignParameter['_PPLayer']['_XWidth'] / 2)) + (((((self._DesignParameter['nmos_input_vias']['_XYCoordinates'][0][0] + self._DesignParameter['nmos_input_vias']['_DesignObj']._DesignParameter['ViaMet12Met2']['_XYCoordinates'][0][0]) + self._DesignParameter['nmos_input_vias']['_DesignObj']._DesignParameter['ViaMet12Met2']['_DesignObj']._DesignParameter['_Met1Layer']['_XYCoordinates'][0][0]) - (self._DesignParameter['nmos_input_vias']['_DesignObj']._DesignParameter['ViaMet12Met2']['_DesignObj']._DesignParameter['_Met1Layer']['_XWidth'] / 2)) - drc._Metal1MinSpace3) - (self._DesignParameter['NMOSSubringInResistorBank_0']['_DesignObj']._DesignParameter['left']['_DesignObj']._DesignParameter['_Met1Layer']['_XWidth'] / 2))) / 2), ((((self._DesignParameter['PCCAM1_CDNS_6375475055632_1']['_XYCoordinates'][0][1] + self._DesignParameter['PCCAM1_CDNS_6375475055632_1']['_DesignObj']._DesignParameter['_Met1Layer']['_XYCoordinates'][0][1]) + (self._DesignParameter['PCCAM1_CDNS_6375475055632_1']['_DesignObj']._DesignParameter['_Met1Layer']['_YWidth'] / 2)) + min(((self._DesignParameter['NMOSInTransmissionGate_0']['_XYCoordinates'][0][1] + self._DesignParameter['NMOSInTransmissionGate_0']['_DesignObj']._DesignParameter['_Met1Layer']['_XYCoordinates'][0][1]) - (self._DesignParameter['NMOSInTransmissionGate_0']['_DesignObj']._DesignParameter['_Met1Layer']['_YWidth'] / 2)), (((self._DesignParameter['nmos_source_via']['_XYCoordinates'][0][1] + self._DesignParameter['nmos_source_via']['_DesignObj']._DesignParameter['ViaMet12Met2']['_XYCoordinates'][0][1]) + self._DesignParameter['nmos_source_via']['_DesignObj']._DesignParameter['ViaMet12Met2']['_DesignObj']._DesignParameter['_Met1Layer']['_XYCoordinates'][0][1]) - (self._DesignParameter['nmos_source_via']['_DesignObj']._DesignParameter['ViaMet12Met2']['_DesignObj']._DesignParameter['_Met1Layer']['_YWidth'] / 2)))) / 2)]]
		path_list = []
		xy_offset = [0, 0]
		if (len(self._DesignParameter['NMOSInTransmissionGate_0']['_DesignObj']._DesignParameter['_POLayer']['_XYCoordinates']) == 1):
		    mode = 'vertical'
		    _width = self._DesignParameter['NMOSInTransmissionGate_0']['_DesignObj']._DesignParameter['_POLayer']['_XWidth']
		elif (self._DesignParameter['NMOSInTransmissionGate_0']['_DesignObj']._DesignParameter['_POLayer']['_XYCoordinates'][0][0] == self._DesignParameter['NMOSInTransmissionGate_0']['_DesignObj']._DesignParameter['_POLayer']['_XYCoordinates'][(- 1)][0]):
		    mode = 'horizontal'
		    _width = self._DesignParameter['NMOSInTransmissionGate_0']['_DesignObj']._DesignParameter['_POLayer']['_XWidth']
		elif (self._DesignParameter['NMOSInTransmissionGate_0']['_DesignObj']._DesignParameter['_POLayer']['_XYCoordinates'][0][1] == self._DesignParameter['NMOSInTransmissionGate_0']['_DesignObj']._DesignParameter['_POLayer']['_XYCoordinates'][(- 1)][1]):
		    mode = 'vertical'
		    _width = self._DesignParameter['NMOSInTransmissionGate_0']['_DesignObj']._DesignParameter['_POLayer']['_XWidth']
		else:
		    print('Invalid Target Input')
		if (mode == 'vertical'):
		    xy_with_offset = []
		    target_y_value = [[(+ self._DesignParameter['PCCAM1_CDNS_6375475055632_1']['_XYCoordinates'][0][0]), (+ self._DesignParameter['PCCAM1_CDNS_6375475055632_1']['_XYCoordinates'][0][1])]][0][1]
		    for i in range(len(self._DesignParameter['NMOSInTransmissionGate_0']['_DesignObj']._DesignParameter['_POLayer']['_XYCoordinates'])):
		        xy_with_offset.append([(x + y) for (x, y) in zip([(0 + self._DesignParameter['NMOSInTransmissionGate_0']['_XYCoordinates'][0][0]), (0 + self._DesignParameter['NMOSInTransmissionGate_0']['_XYCoordinates'][0][1])], self._DesignParameter['NMOSInTransmissionGate_0']['_DesignObj']._DesignParameter['_POLayer']['_XYCoordinates'][i])])
		    for i in range(len(xy_with_offset)):
		        path_list.append([xy_with_offset[i], [xy_with_offset[i][0], target_y_value]])
		elif (mode == 'horizontal'):
		    xy_with_offset = []
		    target_x_value = [[(+ self._DesignParameter['PCCAM1_CDNS_6375475055632_1']['_XYCoordinates'][0][0]), (+ self._DesignParameter['PCCAM1_CDNS_6375475055632_1']['_XYCoordinates'][0][1])]][0][0]
		    for i in range(len(self._DesignParameter['NMOSInTransmissionGate_0']['_DesignObj']._DesignParameter['_POLayer']['_XYCoordinates'])):
		        xy_with_offset.append([(x + y) for (x, y) in zip([(0 + self._DesignParameter['NMOSInTransmissionGate_0']['_XYCoordinates'][0][0]), (0 + self._DesignParameter['NMOSInTransmissionGate_0']['_XYCoordinates'][0][1])], self._DesignParameter['NMOSInTransmissionGate_0']['_DesignObj']._DesignParameter['_POLayer']['_XYCoordinates'][i])])
		    for i in range(len(xy_with_offset)):
		        path_list.append([xy_with_offset[i], [target_x_value, xy_with_offset[i][1]]])
		for i in range(len(path_list)):
		    path_list[i][0] = [(xy + offset) for (xy, offset) in zip(path_list[i][0], xy_offset)]
		self._DesignParameter['nmos_gate'] = self._PathElementDeclaration(_Layer=DesignParameters._LayerMapping['POLY'][0], _Datatype=DesignParameters._LayerMapping['POLY'][1], _Width=_width)
		self._DesignParameter['nmos_gate']['_XYCoordinates'] = path_list
		self._DesignParameter['POLY_path_21'] = self._PathElementDeclaration(_Layer=DesignParameters._LayerMapping['POLY'][0], _Datatype=DesignParameters._LayerMapping['POLY'][1], _Width=self._DesignParameter['PCCAM1_CDNS_6375475055632_1']['_DesignObj']._DesignParameter['_POLayer']['_YWidth'])
		self._DesignParameter['POLY_path_21']['_XYCoordinates'] = [[[((self._DesignParameter['NMOSInTransmissionGate_0']['_XYCoordinates'][0][0] + self._DesignParameter['NMOSInTransmissionGate_0']['_DesignObj']._DesignParameter['_POLayer']['_XYCoordinates'][0][0]) - (self._DesignParameter['NMOSInTransmissionGate_0']['_DesignObj']._DesignParameter['_POLayer']['_XWidth'] / 2)), self._DesignParameter['PCCAM1_CDNS_6375475055632_1']['_XYCoordinates'][0][1]], [((self._DesignParameter['NMOSInTransmissionGate_0']['_XYCoordinates'][0][0] + self._DesignParameter['NMOSInTransmissionGate_0']['_DesignObj']._DesignParameter['_POLayer']['_XYCoordinates'][(- 1)][0]) + (self._DesignParameter['NMOSInTransmissionGate_0']['_DesignObj']._DesignParameter['_POLayer']['_XWidth'] / 2)), self._DesignParameter['PCCAM1_CDNS_6375475055632_1']['_XYCoordinates'][0][1]]]]
		self._DesignParameter['PMOSSubringInResistorBank_0'] = self._SrefElementDeclaration(_DesignObj=NSubRing.NSubRing(_Name='PMOSSubringInResistorBank_0In{}'.format(_Name)))[0]
		self._DesignParameter['PMOSSubringInResistorBank_0']['_DesignObj']._CalculateDesignParameter(**dict(height=5000, width=5000, contact=subring_contact))
		self._DesignParameter['PMOSSubringInResistorBank_0']['_XYCoordinates'] = [[(- 90.0), 1822.0]]
		self._DesignParameter['PMOSInTransmissionGate_0'] = self._SrefElementDeclaration(_DesignObj=PMOSWithDummy._PMOS(_Name='PMOSInTransmissionGate_0In{}'.format(_Name)))[0]
		self._DesignParameter['PMOSInTransmissionGate_0']['_DesignObj']._CalculatePMOSDesignParameter(**dict(_PMOSNumberofGate=number_of_gate, _PMOSChannelWidth=pmos_width, _PMOSChannellength=30, _PMOSDummy=True, _GateSpacing=None, _SDWidth=None, _XVT='SLVT', _PCCrit=None))
		self._DesignParameter['PMOSInTransmissionGate_0']['_XYCoordinates'] = [[self._DesignParameter['NMOSInTransmissionGate_0']['_XYCoordinates'][0][0], ((((((((((self._DesignParameter['NMOSSubringInResistorBank_0']['_XYCoordinates'][0][1] + self._DesignParameter['NMOSSubringInResistorBank_0']['_DesignObj']._DesignParameter['top']['_XYCoordinates'][0][1]) + self._DesignParameter['NMOSSubringInResistorBank_0']['_DesignObj']._DesignParameter['top']['_DesignObj']._DesignParameter['_ODLayer']['_XYCoordinates'][0][1]) + (self._DesignParameter['NMOSSubringInResistorBank_0']['_DesignObj']._DesignParameter['top']['_DesignObj']._DesignParameter['_ODLayer']['_YWidth'] / 2)) + (self._DesignParameter['PMOSSubringInResistorBank_0']['_DesignObj']._DesignParameter['nw_bot']['_YWidth'] / 2)) + (self._DesignParameter['PMOSSubringInResistorBank_0']['_DesignObj']._DesignParameter['bot']['_DesignObj']._DesignParameter['_Met1Layer']['_YWidth'] / 2)) + drc._Metal1MinSpace3) + self._DesignParameter['PCCAM1_CDNS_6375475055632_1']['_DesignObj']._DesignParameter['_Met1Layer']['_YWidth']) + drc._Metal1MinSpace21) + (- (self._DesignParameter['PMOSInTransmissionGate_0']['_DesignObj']._DesignParameter['_Met1Layer']['_XYCoordinates'][0][1] - (self._DesignParameter['PMOSInTransmissionGate_0']['_DesignObj']._DesignParameter['_Met1Layer']['_YWidth'] / 2)))) + drc._NwMinEnclosurePactive2)]]
		pmos_coy = max(1, (1 + int((((self._DesignParameter['PMOSInTransmissionGate_0']['_DesignObj']._DesignParameter['_Met1Layer']['_YWidth'] - drc._VIAxMinSpace) - (2 * drc._VIAxMinEnclosureByMetx)) / (drc._VIAxMinWidth + drc._VIAxMinSpace)))))
		self._DesignParameter['pmos_source_via'] = self._SrefElementDeclaration(_DesignObj=ViaStack._ViaStack(_Name='pmos_source_viaIn{}'.format(_Name)))[0]
		self._DesignParameter['pmos_source_via']['_DesignObj']._CalculateStackMinimumEnclosureX(**dict(COX=1, COY=pmos_coy, start_layer=1, end_layer=3))
		self._DesignParameter['pmos_source_via']['_XYCoordinates'] = None
		XYList = []
		xy_offset = (0, int(((drc._VIAxMinWidth + drc._VIAxMinSpace) / 4)))
		for i in range(len(self._DesignParameter['PMOSInTransmissionGate_0']['_DesignObj']._DesignParameter['_METAL1PINDrawing']['_XYCoordinates'])):
		    if ((i % 2) == 0):
		        xy = (self._DesignParameter['PMOSInTransmissionGate_0']['_DesignObj']._DesignParameter['_METAL1PINDrawing']['_XYCoordinates'][i][0] if (type(self._DesignParameter['PMOSInTransmissionGate_0']['_DesignObj']._DesignParameter['_METAL1PINDrawing']['_XYCoordinates'][i][0]) == list) else self._DesignParameter['PMOSInTransmissionGate_0']['_DesignObj']._DesignParameter['_METAL1PINDrawing']['_XYCoordinates'][i])
		        XYList.append([((x + y) + z) for (x, y, z) in zip([(0 + self._DesignParameter['PMOSInTransmissionGate_0']['_XYCoordinates'][0][0]), (0 + self._DesignParameter['PMOSInTransmissionGate_0']['_XYCoordinates'][0][1])], xy, xy_offset)])
		self._DesignParameter['pmos_source_via']['_XYCoordinates'] = XYList
		self._DesignParameter['pmos_drain_via'] = self._SrefElementDeclaration(_DesignObj=ViaMet12Met2._ViaMet12Met2(_Name='pmos_drain_viaIn{}'.format(_Name)))[0]
		self._DesignParameter['pmos_drain_via']['_DesignObj']._CalculateViaMet12Met2DesignParameterMinimumEnclosureX(**dict(_ViaMet12Met2NumberOfCOX=1, _ViaMet12Met2NumberOfCOY=pmos_coy))
		self._DesignParameter['pmos_drain_via']['_XYCoordinates'] = None
		XYList = []
		xy_offset = (0, (- int(((drc._VIAxMinWidth + drc._VIAxMinSpace) / 4))))
		for i in range(len(self._DesignParameter['PMOSInTransmissionGate_0']['_DesignObj']._DesignParameter['_METAL1PINDrawing']['_XYCoordinates'])):
		    if ((i % 2) == 1):
		        xy = (self._DesignParameter['PMOSInTransmissionGate_0']['_DesignObj']._DesignParameter['_METAL1PINDrawing']['_XYCoordinates'][i][0] if (type(self._DesignParameter['PMOSInTransmissionGate_0']['_DesignObj']._DesignParameter['_METAL1PINDrawing']['_XYCoordinates'][i][0]) == list) else self._DesignParameter['PMOSInTransmissionGate_0']['_DesignObj']._DesignParameter['_METAL1PINDrawing']['_XYCoordinates'][i])
		        XYList.append([((x + y) + z) for (x, y, z) in zip([(0 + self._DesignParameter['PMOSInTransmissionGate_0']['_XYCoordinates'][0][0]), (0 + self._DesignParameter['PMOSInTransmissionGate_0']['_XYCoordinates'][0][1])], xy, xy_offset)])
		self._DesignParameter['pmos_drain_via']['_XYCoordinates'] = XYList
		self._DesignParameter['PCCAM1_CDNS_6375475055632_0'] = self._SrefElementDeclaration(_DesignObj=ViaPoly2Met1._ViaPoly2Met1(_Name='PCCAM1_CDNS_6375475055632_0In{}'.format(_Name)))[0]
		self._DesignParameter['PCCAM1_CDNS_6375475055632_0']['_DesignObj']._CalculateViaPoly2Met1DesignParameter(**dict(_ViaPoly2Met1NumberOfCOX=max(1, (1 + int(((((((self._DesignParameter['PMOSInTransmissionGate_0']['_XYCoordinates'][0][0] + self._DesignParameter['PMOSInTransmissionGate_0']['_DesignObj']._DesignParameter['_POLayer']['_XYCoordinates'][(- 1)][0]) + (self._DesignParameter['PMOSInTransmissionGate_0']['_DesignObj']._DesignParameter['_POLayer']['_XWidth'] / 2)) - ((self._DesignParameter['PMOSInTransmissionGate_0']['_XYCoordinates'][0][0] + self._DesignParameter['PMOSInTransmissionGate_0']['_DesignObj']._DesignParameter['_POLayer']['_XYCoordinates'][0][0]) - (self._DesignParameter['PMOSInTransmissionGate_0']['_DesignObj']._DesignParameter['_POLayer']['_XWidth'] / 2))) - drc._CoMinSpace) - (2 * drc._CoMinEnclosureByPO)) / (drc._CoMinWidth + drc._CoMinSpace))))), _ViaPoly2Met1NumberOfCOY=1))
		self._DesignParameter['PCCAM1_CDNS_6375475055632_0']['_XYCoordinates'] = [[self._DesignParameter['PMOSInTransmissionGate_0']['_XYCoordinates'][0][0], ((min(((self._DesignParameter['pmos_drain_via']['_XYCoordinates'][0][1] + self._DesignParameter['pmos_drain_via']['_DesignObj']._DesignParameter['_Met1Layer']['_XYCoordinates'][0][1]) - (self._DesignParameter['pmos_drain_via']['_DesignObj']._DesignParameter['_Met1Layer']['_YWidth'] / 2)), ((self._DesignParameter['PMOSInTransmissionGate_0']['_XYCoordinates'][0][1] + self._DesignParameter['PMOSInTransmissionGate_0']['_DesignObj']._DesignParameter['_Met1Layer']['_XYCoordinates'][0][1]) - (self._DesignParameter['PMOSInTransmissionGate_0']['_DesignObj']._DesignParameter['_Met1Layer']['_YWidth'] / 2))) - drc._Metal1MinSpace21) - (self._DesignParameter['PCCAM1_CDNS_6375475055632_0']['_DesignObj']._DesignParameter['_Met1Layer']['_YWidth'] / 2))]]
		path_list = []
		xy_offset = [0, 0]
		if (len(self._DesignParameter['PMOSInTransmissionGate_0']['_DesignObj']._DesignParameter['_POLayerPINDrawing']['_XYCoordinates']) == 1):
		    mode = 'vertical'
		    _width = self._DesignParameter['PMOSInTransmissionGate_0']['_DesignObj']._DesignParameter['_POLayerPINDrawing']['_XWidth']
		elif (self._DesignParameter['PMOSInTransmissionGate_0']['_DesignObj']._DesignParameter['_POLayerPINDrawing']['_XYCoordinates'][0][0] == self._DesignParameter['PMOSInTransmissionGate_0']['_DesignObj']._DesignParameter['_POLayerPINDrawing']['_XYCoordinates'][(- 1)][0]):
		    mode = 'horizontal'
		    _width = self._DesignParameter['PMOSInTransmissionGate_0']['_DesignObj']._DesignParameter['_POLayerPINDrawing']['_XWidth']
		elif (self._DesignParameter['PMOSInTransmissionGate_0']['_DesignObj']._DesignParameter['_POLayerPINDrawing']['_XYCoordinates'][0][1] == self._DesignParameter['PMOSInTransmissionGate_0']['_DesignObj']._DesignParameter['_POLayerPINDrawing']['_XYCoordinates'][(- 1)][1]):
		    mode = 'vertical'
		    _width = self._DesignParameter['PMOSInTransmissionGate_0']['_DesignObj']._DesignParameter['_POLayerPINDrawing']['_XWidth']
		else:
		    print('Invalid Target Input')
		if (mode == 'vertical'):
		    xy_with_offset = []
		    target_y_value = [[(+ self._DesignParameter['PCCAM1_CDNS_6375475055632_0']['_XYCoordinates'][0][0]), (+ self._DesignParameter['PCCAM1_CDNS_6375475055632_0']['_XYCoordinates'][0][1])]][0][1]
		    for i in range(len(self._DesignParameter['PMOSInTransmissionGate_0']['_DesignObj']._DesignParameter['_POLayerPINDrawing']['_XYCoordinates'])):
		        xy_with_offset.append([(x + y) for (x, y) in zip([(0 + self._DesignParameter['PMOSInTransmissionGate_0']['_XYCoordinates'][0][0]), (0 + self._DesignParameter['PMOSInTransmissionGate_0']['_XYCoordinates'][0][1])], self._DesignParameter['PMOSInTransmissionGate_0']['_DesignObj']._DesignParameter['_POLayerPINDrawing']['_XYCoordinates'][i])])
		    for i in range(len(xy_with_offset)):
		        path_list.append([xy_with_offset[i], [xy_with_offset[i][0], target_y_value]])
		elif (mode == 'horizontal'):
		    xy_with_offset = []
		    target_x_value = [[(+ self._DesignParameter['PCCAM1_CDNS_6375475055632_0']['_XYCoordinates'][0][0]), (+ self._DesignParameter['PCCAM1_CDNS_6375475055632_0']['_XYCoordinates'][0][1])]][0][0]
		    for i in range(len(self._DesignParameter['PMOSInTransmissionGate_0']['_DesignObj']._DesignParameter['_POLayerPINDrawing']['_XYCoordinates'])):
		        xy_with_offset.append([(x + y) for (x, y) in zip([(0 + self._DesignParameter['PMOSInTransmissionGate_0']['_XYCoordinates'][0][0]), (0 + self._DesignParameter['PMOSInTransmissionGate_0']['_XYCoordinates'][0][1])], self._DesignParameter['PMOSInTransmissionGate_0']['_DesignObj']._DesignParameter['_POLayerPINDrawing']['_XYCoordinates'][i])])
		    for i in range(len(xy_with_offset)):
		        path_list.append([xy_with_offset[i], [target_x_value, xy_with_offset[i][1]]])
		for i in range(len(path_list)):
		    path_list[i][0] = [(xy + offset) for (xy, offset) in zip(path_list[i][0], xy_offset)]
		self._DesignParameter['pmos_gate'] = self._PathElementDeclaration(_Layer=DesignParameters._LayerMapping['POLY'][0], _Datatype=DesignParameters._LayerMapping['POLY'][1], _Width=_width)
		self._DesignParameter['pmos_gate']['_XYCoordinates'] = path_list
		self._DesignParameter['POLY_path_0'] = self._PathElementDeclaration(_Layer=DesignParameters._LayerMapping['POLY'][0], _Datatype=DesignParameters._LayerMapping['POLY'][1], _Width=self._DesignParameter['PCCAM1_CDNS_6375475055632_0']['_DesignObj']._DesignParameter['_POLayer']['_YWidth'])
		self._DesignParameter['POLY_path_0']['_XYCoordinates'] = [[[((self._DesignParameter['PMOSInTransmissionGate_0']['_XYCoordinates'][0][0] + self._DesignParameter['PMOSInTransmissionGate_0']['_DesignObj']._DesignParameter['_POLayer']['_XYCoordinates'][0][0]) - (self._DesignParameter['PMOSInTransmissionGate_0']['_DesignObj']._DesignParameter['_POLayer']['_XWidth'] / 2)), (self._DesignParameter['PCCAM1_CDNS_6375475055632_0']['_XYCoordinates'][0][1] + self._DesignParameter['PCCAM1_CDNS_6375475055632_0']['_DesignObj']._DesignParameter['_POLayer']['_XYCoordinates'][0][1])], [((self._DesignParameter['PMOSInTransmissionGate_0']['_XYCoordinates'][0][0] + self._DesignParameter['PMOSInTransmissionGate_0']['_DesignObj']._DesignParameter['_POLayer']['_XYCoordinates'][(- 1)][0]) + (self._DesignParameter['PMOSInTransmissionGate_0']['_DesignObj']._DesignParameter['_POLayer']['_XWidth'] / 2)), (self._DesignParameter['PCCAM1_CDNS_6375475055632_0']['_XYCoordinates'][0][1] + self._DesignParameter['PCCAM1_CDNS_6375475055632_0']['_DesignObj']._DesignParameter['_POLayer']['_XYCoordinates'][0][1])]]]
		path_list = []
		xy_offset = [0, 0]
		if (len(self._DesignParameter['nmos_drain_via']['_XYCoordinates']) == 1):
		    mode = 'vertical'
		    _width = self._DesignParameter['pmos_drain_via']['_DesignObj']._DesignParameter['_Met2Layer']['_XWidth']
		elif (self._DesignParameter['nmos_drain_via']['_XYCoordinates'][0][0] == self._DesignParameter['nmos_drain_via']['_XYCoordinates'][(- 1)][0]):
		    mode = 'horizontal'
		    _width = self._DesignParameter['pmos_drain_via']['_DesignObj']._DesignParameter['_Met2Layer']['_XWidth']
		elif (self._DesignParameter['nmos_drain_via']['_XYCoordinates'][0][1] == self._DesignParameter['nmos_drain_via']['_XYCoordinates'][(- 1)][1]):
		    mode = 'vertical'
		    _width = self._DesignParameter['pmos_drain_via']['_DesignObj']._DesignParameter['_Met2Layer']['_XWidth']
		else:
		    print('Invalid Target Input')
		if (mode == 'vertical'):
		    xy_with_offset = []
		    target_y_value = [[(+ self._DesignParameter['pmos_drain_via']['_XYCoordinates'][0][0]), (+ self._DesignParameter['pmos_drain_via']['_XYCoordinates'][0][1])]][0][1]
		    for i in range(len(self._DesignParameter['nmos_drain_via']['_XYCoordinates'])):
		        xy_with_offset.append([(x + y) for (x, y) in zip([0, 0], self._DesignParameter['nmos_drain_via']['_XYCoordinates'][i])])
		    for i in range(len(xy_with_offset)):
		        path_list.append([xy_with_offset[i], [xy_with_offset[i][0], target_y_value]])
		elif (mode == 'horizontal'):
		    xy_with_offset = []
		    target_x_value = [[(+ self._DesignParameter['pmos_drain_via']['_XYCoordinates'][0][0]), (+ self._DesignParameter['pmos_drain_via']['_XYCoordinates'][0][1])]][0][0]
		    for i in range(len(self._DesignParameter['nmos_drain_via']['_XYCoordinates'])):
		        xy_with_offset.append([(x + y) for (x, y) in zip([0, 0], self._DesignParameter['nmos_drain_via']['_XYCoordinates'][i])])
		    for i in range(len(xy_with_offset)):
		        path_list.append([xy_with_offset[i], [target_x_value, xy_with_offset[i][1]]])
		for i in range(len(path_list)):
		    path_list[i][0] = [(xy + offset) for (xy, offset) in zip(path_list[i][0], xy_offset)]
		self._DesignParameter['met2_vertical'] = self._PathElementDeclaration(_Layer=DesignParameters._LayerMapping['METAL2'][0], _Datatype=DesignParameters._LayerMapping['METAL2'][1], _Width=_width)
		self._DesignParameter['met2_vertical']['_XYCoordinates'] = path_list
		input_coy = max(1, (1 + int((((((((self._DesignParameter['PCCAM1_CDNS_6375475055632_0']['_XYCoordinates'][0][1] + self._DesignParameter['PCCAM1_CDNS_6375475055632_0']['_DesignObj']._DesignParameter['_Met1Layer']['_XYCoordinates'][0][1]) - (self._DesignParameter['PCCAM1_CDNS_6375475055632_0']['_DesignObj']._DesignParameter['_Met1Layer']['_YWidth'] / 2)) - ((self._DesignParameter['PCCAM1_CDNS_6375475055632_1']['_XYCoordinates'][0][1] + self._DesignParameter['PCCAM1_CDNS_6375475055632_1']['_DesignObj']._DesignParameter['_Met1Layer']['_XYCoordinates'][0][1]) + (self._DesignParameter['PCCAM1_CDNS_6375475055632_1']['_DesignObj']._DesignParameter['_Met1Layer']['_YWidth'] / 2))) - (drc._MetalxMinSpace2 * 2)) - drc._VIAxMinSpace) - (2 * drc._VIAxMinEnclosureByMetx)) / (drc._VIAxMinWidth + drc._VIAxMinSpace)))))
		self._DesignParameter['input_vias'] = self._SrefElementDeclaration(_DesignObj=ViaStack._ViaStack(_Name='input_viasIn{}'.format(_Name)))[0]
		self._DesignParameter['input_vias']['_DesignObj']._CalculateStackMinimumEnclosureX(**dict(COX=1, COY=input_coy, start_layer=2, end_layer=4))
		self._DesignParameter['input_vias']['_XYCoordinates'] = None
		XYList = []
		xy_offset = (0, (((((self._DesignParameter['pmos_drain_via']['_XYCoordinates'][0][1] + self._DesignParameter['pmos_drain_via']['_DesignObj']._DesignParameter['_Met2Layer']['_XYCoordinates'][0][1]) - (self._DesignParameter['pmos_drain_via']['_DesignObj']._DesignParameter['_Met2Layer']['_YWidth'] / 2)) - ((self._DesignParameter['nmos_drain_via']['_XYCoordinates'][0][1] + self._DesignParameter['nmos_drain_via']['_DesignObj']._DesignParameter['_Met2Layer']['_XYCoordinates'][0][1]) + (self._DesignParameter['nmos_drain_via']['_DesignObj']._DesignParameter['_Met2Layer']['_YWidth'] / 2))) / 2) + (self._DesignParameter['nmos_drain_via']['_DesignObj']._DesignParameter['_Met2Layer']['_YWidth'] / 2)))
		for i in range(len(self._DesignParameter['nmos_drain_via']['_XYCoordinates'])):
		    xy = (self._DesignParameter['nmos_drain_via']['_XYCoordinates'][i][0] if (type(self._DesignParameter['nmos_drain_via']['_XYCoordinates'][i][0]) == list) else self._DesignParameter['nmos_drain_via']['_XYCoordinates'][i])
		    XYList.append([((x + y) + z) for (x, y, z) in zip([0, 0], xy, xy_offset)])
		self._DesignParameter['input_vias']['_XYCoordinates'] = XYList
		self._DesignParameter['METAL4_boundary_9'] = self._BoundaryElementDeclaration(_Layer=DesignParameters._LayerMapping['METAL4'][0], _Datatype=DesignParameters._LayerMapping['METAL4'][1], _XWidth=(self._DesignParameter['input_vias']['_XYCoordinates'][(- 1)][0] - self._DesignParameter['input_vias']['_XYCoordinates'][0][0]), _YWidth=self._DesignParameter['input_vias']['_DesignObj']._DesignParameter['ViaMet32Met4']['_DesignObj']._DesignParameter['_Met4Layer']['_YWidth'])
		self._DesignParameter['METAL4_boundary_9']['_XYCoordinates'] = [[((self._DesignParameter['input_vias']['_XYCoordinates'][0][0] + self._DesignParameter['input_vias']['_XYCoordinates'][(- 1)][0]) / 2), self._DesignParameter['input_vias']['_XYCoordinates'][0][1]]]
		self._DesignParameter['METAL1_path_0'] = self._PathElementDeclaration(_Layer=DesignParameters._LayerMapping['METAL1'][0], _Datatype=DesignParameters._LayerMapping['METAL1'][1], _Width=self._DesignParameter['PCCAM1_CDNS_6375475055632_1']['_DesignObj']._DesignParameter['_Met1Layer']['_YWidth'])
		self._DesignParameter['METAL1_path_0']['_XYCoordinates'] = [[[(+ self._DesignParameter['PCCAM1_CDNS_6375475055632_1']['_XYCoordinates'][0][0]), (+ self._DesignParameter['PCCAM1_CDNS_6375475055632_1']['_XYCoordinates'][0][1])], [(+ (((self._DesignParameter['nmos_input_vias']['_XYCoordinates'][0][0] + self._DesignParameter['nmos_input_vias']['_DesignObj']._DesignParameter['ViaMet42Met5']['_XYCoordinates'][0][0]) + self._DesignParameter['nmos_input_vias']['_DesignObj']._DesignParameter['ViaMet42Met5']['_DesignObj']._DesignParameter['_Met5Layer']['_XYCoordinates'][0][0]) - (self._DesignParameter['nmos_input_vias']['_DesignObj']._DesignParameter['ViaMet42Met5']['_DesignObj']._DesignParameter['_Met5Layer']['_XWidth'] / 2))), (+ ((self._DesignParameter['nmos_input_vias']['_XYCoordinates'][0][1] + self._DesignParameter['nmos_input_vias']['_DesignObj']._DesignParameter['ViaMet42Met5']['_XYCoordinates'][0][1]) + self._DesignParameter['nmos_input_vias']['_DesignObj']._DesignParameter['ViaMet42Met5']['_DesignObj']._DesignParameter['_Met5Layer']['_XYCoordinates'][0][1]))]]]
		self._DesignParameter['PMOSSubringInResistorBank_0']['_DesignObj']._CalculateDesignParameter(**dict(height=(self._DesignParameter['PMOSSubringInResistorBank_0']['_DesignObj']._DesignParameter['top']['_DesignObj']._DesignParameter['_Met1Layer']['_YWidth'] + (((max((((self._DesignParameter['pmos_source_via']['_XYCoordinates'][0][1] + self._DesignParameter['pmos_source_via']['_DesignObj']._DesignParameter['ViaMet12Met2']['_XYCoordinates'][0][1]) + self._DesignParameter['pmos_source_via']['_DesignObj']._DesignParameter['ViaMet12Met2']['_DesignObj']._DesignParameter['_Met2Layer']['_XYCoordinates'][0][1]) + (self._DesignParameter['pmos_source_via']['_DesignObj']._DesignParameter['ViaMet12Met2']['_DesignObj']._DesignParameter['_Met2Layer']['_YWidth'] / 2)), ((self._DesignParameter['PMOSInTransmissionGate_0']['_XYCoordinates'][0][1] + self._DesignParameter['PMOSInTransmissionGate_0']['_DesignObj']._DesignParameter['_Met1Layer']['_XYCoordinates'][0][1]) + (self._DesignParameter['PMOSInTransmissionGate_0']['_DesignObj']._DesignParameter['_Met1Layer']['_YWidth'] / 2))) + drc._Metal1MinSpace3) - ((self._DesignParameter['PCCAM1_CDNS_6375475055632_0']['_XYCoordinates'][0][1] + self._DesignParameter['PCCAM1_CDNS_6375475055632_0']['_DesignObj']._DesignParameter['_Met1Layer']['_XYCoordinates'][0][1]) - (self._DesignParameter['PCCAM1_CDNS_6375475055632_0']['_DesignObj']._DesignParameter['_Met1Layer']['_YWidth'] / 2))) + drc._Metal1MinSpace3)), width=(((((((self._DesignParameter['NMOSInTransmissionGate_0']['_XYCoordinates'][0][0] + self._DesignParameter['NMOSInTransmissionGate_0']['_DesignObj']._DesignParameter['_ODLayer']['_XYCoordinates'][0][0]) + (self._DesignParameter['NMOSInTransmissionGate_0']['_DesignObj']._DesignParameter['_ODLayer']['_XWidth'] / 2)) + drc._OdMinSpace) + (self._DesignParameter['NMOSSubringInResistorBank_0']['_DesignObj']._DesignParameter['right']['_DesignObj']._DesignParameter['_PPLayer']['_XWidth'] / 2)) - (((self._DesignParameter['nmos_input_vias']['_XYCoordinates'][0][0] + self._DesignParameter['nmos_input_vias']['_DesignObj']._DesignParameter['ViaMet12Met2']['_XYCoordinates'][0][0]) + self._DesignParameter['nmos_input_vias']['_DesignObj']._DesignParameter['ViaMet12Met2']['_DesignObj']._DesignParameter['_Met1Layer']['_XYCoordinates'][0][0]) - (self._DesignParameter['nmos_input_vias']['_DesignObj']._DesignParameter['ViaMet12Met2']['_DesignObj']._DesignParameter['_Met1Layer']['_XWidth'] / 2))) + drc._Metal1MinSpace3) + (self._DesignParameter['NMOSSubringInResistorBank_0']['_DesignObj']._DesignParameter['left']['_DesignObj']._DesignParameter['_Met1Layer']['_XWidth'] / 2)), contact=subring_contact))
		self._DesignParameter['PMOSSubringInResistorBank_0']['_XYCoordinates'] = [[self._DesignParameter['NMOSSubringInResistorBank_0']['_XYCoordinates'][0][0], ((((max((((self._DesignParameter['pmos_source_via']['_XYCoordinates'][0][1] + self._DesignParameter['pmos_source_via']['_DesignObj']._DesignParameter['ViaMet12Met2']['_XYCoordinates'][0][1]) + self._DesignParameter['pmos_source_via']['_DesignObj']._DesignParameter['ViaMet12Met2']['_DesignObj']._DesignParameter['_Met1Layer']['_XYCoordinates'][0][1]) + (self._DesignParameter['pmos_source_via']['_DesignObj']._DesignParameter['ViaMet12Met2']['_DesignObj']._DesignParameter['_Met1Layer']['_YWidth'] / 2)), ((self._DesignParameter['PMOSInTransmissionGate_0']['_XYCoordinates'][0][1] + self._DesignParameter['PMOSInTransmissionGate_0']['_DesignObj']._DesignParameter['_Met1Layer']['_XYCoordinates'][0][1]) + (self._DesignParameter['PMOSInTransmissionGate_0']['_DesignObj']._DesignParameter['_Met1Layer']['_YWidth'] / 2))) + drc._Metal1MinSpace3) + ((self._DesignParameter['PCCAM1_CDNS_6375475055632_0']['_XYCoordinates'][0][1] + self._DesignParameter['PCCAM1_CDNS_6375475055632_0']['_DesignObj']._DesignParameter['_Met1Layer']['_XYCoordinates'][0][1]) - (self._DesignParameter['PCCAM1_CDNS_6375475055632_0']['_DesignObj']._DesignParameter['_Met1Layer']['_YWidth'] / 2))) - drc._Metal1MinSpace3) / 2)]]
		self._DesignParameter['nwell'] = self._BoundaryElementDeclaration(_Layer=DesignParameters._LayerMapping['NWELL'][0], _Datatype=DesignParameters._LayerMapping['NWELL'][1], _XWidth=((self._DesignParameter['PMOSSubringInResistorBank_0']['_XYCoordinates'][0][0] + self._DesignParameter['PMOSSubringInResistorBank_0']['_DesignObj']._DesignParameter['nw_right']['_XYCoordinates'][0][0]) - (self._DesignParameter['PMOSSubringInResistorBank_0']['_XYCoordinates'][0][0] + self._DesignParameter['PMOSSubringInResistorBank_0']['_DesignObj']._DesignParameter['nw_left']['_XYCoordinates'][0][0])), _YWidth=((self._DesignParameter['PMOSSubringInResistorBank_0']['_XYCoordinates'][0][1] + self._DesignParameter['PMOSSubringInResistorBank_0']['_DesignObj']._DesignParameter['nw_top']['_XYCoordinates'][0][1]) - (self._DesignParameter['PMOSSubringInResistorBank_0']['_XYCoordinates'][0][1] + self._DesignParameter['PMOSSubringInResistorBank_0']['_DesignObj']._DesignParameter['nw_bot']['_XYCoordinates'][0][1])))
		self._DesignParameter['nwell']['_XYCoordinates'] = [[(+ self._DesignParameter['PMOSSubringInResistorBank_0']['_XYCoordinates'][0][0]), (+ self._DesignParameter['PMOSSubringInResistorBank_0']['_XYCoordinates'][0][1])]]
		self._DesignParameter['pmos_input_vias'] = self._SrefElementDeclaration(_DesignObj=ViaStack._ViaStack(_Name='pmos_input_viasIn{}'.format(_Name)))[0]
		self._DesignParameter['pmos_input_vias']['_DesignObj']._CalculateStackMinimumEnclosureY(**dict(COX=2, COY=1, start_layer=1, end_layer=5))
		self._DesignParameter['pmos_input_vias']['_XYCoordinates'] = [[((((self._DesignParameter['PMOSInTransmissionGate_0']['_XYCoordinates'][0][0] + self._DesignParameter['PMOSInTransmissionGate_0']['_DesignObj']._DesignParameter['_Met1Layer']['_XYCoordinates'][1][0]) - (self._DesignParameter['PMOSInTransmissionGate_0']['_DesignObj']._DesignParameter['_Met1Layer']['_XWidth'] / 2)) - drc._MetalxMinSpace21) - (self._DesignParameter['pmos_input_vias']['_DesignObj']._DesignParameter['ViaMet42Met5']['_DesignObj']._DesignParameter['_Met5Layer']['_XWidth'] / 2)), self._DesignParameter['PCCAM1_CDNS_6375475055632_0']['_XYCoordinates'][0][1]]]
		self._DesignParameter['METAL1_path_1'] = self._PathElementDeclaration(_Layer=DesignParameters._LayerMapping['METAL1'][0], _Datatype=DesignParameters._LayerMapping['METAL1'][1], _Width=self._DesignParameter['PCCAM1_CDNS_6375475055632_0']['_DesignObj']._DesignParameter['_Met1Layer']['_YWidth'])
		self._DesignParameter['METAL1_path_1']['_XYCoordinates'] = [[[(+ self._DesignParameter['PCCAM1_CDNS_6375475055632_0']['_XYCoordinates'][0][0]), (+ self._DesignParameter['PCCAM1_CDNS_6375475055632_0']['_XYCoordinates'][0][1])], [(+ (((self._DesignParameter['pmos_input_vias']['_XYCoordinates'][0][0] + self._DesignParameter['pmos_input_vias']['_DesignObj']._DesignParameter['ViaMet42Met5']['_XYCoordinates'][0][0]) + self._DesignParameter['pmos_input_vias']['_DesignObj']._DesignParameter['ViaMet42Met5']['_DesignObj']._DesignParameter['_Met5Layer']['_XYCoordinates'][0][0]) - (self._DesignParameter['pmos_input_vias']['_DesignObj']._DesignParameter['ViaMet42Met5']['_DesignObj']._DesignParameter['_Met5Layer']['_XWidth'] / 2))), (+ ((self._DesignParameter['pmos_input_vias']['_XYCoordinates'][0][1] + self._DesignParameter['pmos_input_vias']['_DesignObj']._DesignParameter['ViaMet42Met5']['_XYCoordinates'][0][1]) + self._DesignParameter['pmos_input_vias']['_DesignObj']._DesignParameter['ViaMet42Met5']['_DesignObj']._DesignParameter['_Met5Layer']['_XYCoordinates'][0][1]))]]]
		self._DesignParameter['VDD_vias'] = self._SrefElementDeclaration(_DesignObj=ViaStack._ViaStack(_Name='VDD_viasIn{}'.format(_Name)))[0]
		self._DesignParameter['VDD_vias']['_DesignObj']._CalculateStack(**dict(COX=max(1, (1 + int((((self._DesignParameter['PMOSSubringInResistorBank_0']['_DesignObj']._DesignParameter['met_top']['_XWidth'] - drc._VIAxMinSpace) - (2 * drc._VIAxMinEnclosureByMetx)) / (drc._VIAxMinWidth + drc._VIAxMinSpace))))), COY=1, start_layer=1, end_layer=3))
		self._DesignParameter['VDD_vias']['_XYCoordinates'] = [[(+ (self._DesignParameter['PMOSSubringInResistorBank_0']['_XYCoordinates'][0][0] + self._DesignParameter['PMOSSubringInResistorBank_0']['_DesignObj']._DesignParameter['top']['_XYCoordinates'][0][0])), (+ (self._DesignParameter['PMOSSubringInResistorBank_0']['_XYCoordinates'][0][1] + self._DesignParameter['PMOSSubringInResistorBank_0']['_DesignObj']._DesignParameter['top']['_XYCoordinates'][0][1]))]]
		self._DesignParameter['M2V2M3_CDNS_6375475055619_0'] = self._SrefElementDeclaration(_DesignObj=ViaMet22Met3._ViaMet22Met3(_Name='M2V2M3_CDNS_6375475055619_0In{}'.format(_Name)))[0]
		self._DesignParameter['M2V2M3_CDNS_6375475055619_0']['_DesignObj']._CalculateViaMet22Met3DesignParameterMinimumEnclosureY(**dict(_ViaMet22Met3NumberOfCOX=1, _ViaMet22Met3NumberOfCOY=nmos_coy))
		self._DesignParameter['M2V2M3_CDNS_6375475055619_0']['_XYCoordinates'] = [[(self._DesignParameter['NMOSSubringInResistorBank_0']['_XYCoordinates'][0][0] + self._DesignParameter['NMOSSubringInResistorBank_0']['_DesignObj']._DesignParameter['right']['_XYCoordinates'][0][0]), self._DesignParameter['nmos_source_via']['_XYCoordinates'][0][1]]]
		self._DesignParameter['METAL3_path_0'] = self._PathElementDeclaration(_Layer=DesignParameters._LayerMapping['METAL3'][0], _Datatype=DesignParameters._LayerMapping['METAL3'][1], _Width=self._DesignParameter['nmos_source_via']['_DesignObj']._DesignParameter['ViaMet22Met3']['_DesignObj']._DesignParameter['_Met3Layer']['_YWidth'])
		self._DesignParameter['METAL3_path_0']['_XYCoordinates'] = [[[(+ self._DesignParameter['nmos_source_via']['_XYCoordinates'][0][0]), (+ self._DesignParameter['nmos_source_via']['_XYCoordinates'][0][1])], [(+ ((self._DesignParameter['M2V2M3_CDNS_6375475055619_0']['_XYCoordinates'][0][0] + self._DesignParameter['M2V2M3_CDNS_6375475055619_0']['_DesignObj']._DesignParameter['_Met3Layer']['_XYCoordinates'][0][0]) + (self._DesignParameter['M2V2M3_CDNS_6375475055619_0']['_DesignObj']._DesignParameter['_Met3Layer']['_XWidth'] / 2))), (+ (self._DesignParameter['M2V2M3_CDNS_6375475055619_0']['_XYCoordinates'][0][1] + self._DesignParameter['M2V2M3_CDNS_6375475055619_0']['_DesignObj']._DesignParameter['_Met3Layer']['_XYCoordinates'][0][1]))]]]
		self._DesignParameter['M2V2M3_CDNS_6375475055623_0'] = self._SrefElementDeclaration(_DesignObj=ViaMet22Met3._ViaMet22Met3(_Name='M2V2M3_CDNS_6375475055623_0In{}'.format(_Name)))[0]
		self._DesignParameter['M2V2M3_CDNS_6375475055623_0']['_DesignObj']._CalculateViaMet22Met3DesignParameterMinimumEnclosureY(**dict(_ViaMet22Met3NumberOfCOX=1, _ViaMet22Met3NumberOfCOY=pmos_coy))
		self._DesignParameter['M2V2M3_CDNS_6375475055623_0']['_XYCoordinates'] = [[self._DesignParameter['M2V2M3_CDNS_6375475055619_0']['_XYCoordinates'][0][0], self._DesignParameter['pmos_source_via']['_XYCoordinates'][0][1]]]
		self._DesignParameter['METAL2_path_0'] = self._PathElementDeclaration(_Layer=DesignParameters._LayerMapping['METAL2'][0], _Datatype=DesignParameters._LayerMapping['METAL2'][1], _Width=170)
		self._DesignParameter['METAL2_path_0']['_XYCoordinates'] = [[[(+ (self._DesignParameter['M2V2M3_CDNS_6375475055619_0']['_XYCoordinates'][0][0] + self._DesignParameter['M2V2M3_CDNS_6375475055619_0']['_DesignObj']._DesignParameter['_Met3Layer']['_XYCoordinates'][0][0])), (+ ((self._DesignParameter['M2V2M3_CDNS_6375475055619_0']['_XYCoordinates'][0][1] + self._DesignParameter['M2V2M3_CDNS_6375475055619_0']['_DesignObj']._DesignParameter['_Met3Layer']['_XYCoordinates'][0][1]) - (self._DesignParameter['M2V2M3_CDNS_6375475055619_0']['_DesignObj']._DesignParameter['_Met3Layer']['_YWidth'] / 2)))], [(+ (self._DesignParameter['M2V2M3_CDNS_6375475055623_0']['_XYCoordinates'][0][0] + self._DesignParameter['M2V2M3_CDNS_6375475055623_0']['_DesignObj']._DesignParameter['_Met3Layer']['_XYCoordinates'][0][0])), (+ ((self._DesignParameter['M2V2M3_CDNS_6375475055623_0']['_XYCoordinates'][0][1] + self._DesignParameter['M2V2M3_CDNS_6375475055623_0']['_DesignObj']._DesignParameter['_Met3Layer']['_XYCoordinates'][0][1]) + (self._DesignParameter['M2V2M3_CDNS_6375475055623_0']['_DesignObj']._DesignParameter['_Met3Layer']['_YWidth'] / 2)))]]]
		